import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'hi' | 'gu';
  setLanguage: (lang: 'en' | 'hi' | 'gu') => void;
  t: (key: string) => string;
  isTransitioning: boolean;
  localizeDigitsInText: (text: string) => string;
  formatNumber: (num: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Comprehensive translations
const translations = {
  en: {
    // Navigation
    home: 'Home',
    introduction: 'Introduction',
    learn: 'Learn',
    realWorld: 'Real World',
    simpleEquations: 'Simple Equations - Addition',
    simpleEquationsTitle: 'Simple Equations - Addition',
    exponentsTitle: 'Laws of Exponents',
    // Laws of Exponents hero (for Learn page)
    expHeroTitle: 'Laws of Exponents',
    expHeroLine1: 'Learn the fundamental rules for working with exponents efficiently.',
    expHeroLine2: 'Master these laws to simplify complex exponential expressions!',
    // Laws of Exponents - Section
    law1Title: 'Law 1: Multiplying Powers with Same Base',
    law1Formula: 'aᵐ × aⁿ = aᵐ⁺ⁿ',
    law1Description: 'When multiplying powers with the same base, add the exponents.',
    law1Example: '2³ × 2² = 2³⁺² = 2⁵ = 32',
    law2Title: 'Law 2: Dividing Powers with Same Base',
    law2Formula: 'aᵐ ÷ aⁿ = aᵐ⁻ⁿ (where m > n)',
    law2Description: 'When dividing powers with the same base, subtract the exponents.',
    law2Example: '5⁴ ÷ 5² = 5⁴⁻² = 5² = 25',
    law3Title: 'Law 3: Power of a Power',
    law3Formula: '(aᵐ)ⁿ = aᵐⁿ',
    law3Description: 'When raising a power to another power, multiply the exponents.',
    law3Example: '(3²)³ = 3²×³ = 3⁶ = 729',
    law4Title: 'Law 4: Multiplying Powers with Same Exponent',
    law4Formula: 'aᵐ × bᵐ = (ab)ᵐ',
    law4Description: 'When multiplying powers with the same exponent, multiply the bases.',
    law4Example: '2³ × 5³ = (2 × 5)³ = 10³ = 1,000',
    law5Title: 'Law 5: Dividing Powers with Same Exponent',
    law5Formula: 'aᵐ ÷ bᵐ = (a/b)ᵐ',
    law5Description: 'When dividing powers with the same exponent, divide the bases.',
    law5Example: '8² ÷ 2² = (8/2)² = 4² = 16',
    law6Title: 'Law 6: Exponent Zero',
    law6Formula: 'a⁰ = 1 (where a ≠ 0)',
    law6Description: 'Any non-zero number raised to the power of zero equals 1.',
    law6Example: '5⁰ = 1, 10⁰ = 1, 100⁰ = 1',
    lawSummary: 'Summary',
    lawSummaryText: 'These six laws form the foundation for all exponent calculations!',
    exampleLabel: 'Example',
    // Law 1 Steps
    law1_step1_text: '2³ × 2²',
    law1_step1_explanation: 'Same base (2)',
    law1_step2_text: '(2×2×2) × (2×2)',
    law1_step2_explanation: 'Expand the powers',
    law1_step3_text: '2×2×2×2×2',
    law1_step3_explanation: 'Count total 2\'s (5 times)',
    law1_step4_text: '2⁵ = 2³⁺²',
    law1_step4_explanation: 'Add exponents: 3 + 2 = 5',
    law1_step5_text: '= 32',
    law1_step5_explanation: 'Final answer',
    // Law 2 Steps
    law2_step1_text: '5⁴ ÷ 5²',
    law2_step1_explanation: 'Same base (5)',
    law2_step2_text: '(5×5×5×5) ÷ (5×5)',
    law2_step2_explanation: 'Expand the powers',
    law2_step3_text: '5×5',
    law2_step3_explanation: 'Cancel common factors',
    law2_step4_text: '5² = 5⁴⁻²',
    law2_step4_explanation: 'Subtract exponents: 4 - 2 = 2',
    law2_step5_text: '= 25',
    law2_step5_explanation: 'Final answer',
    // Law 3 Steps
    law3_step1_text: '(3²)³',
    law3_step1_explanation: 'Power of a power',
    law3_step2_text: '3² × 3² × 3²',
    law3_step2_explanation: '3² multiplied 3 times',
    law3_step3_text: '3²⁺²⁺²',
    law3_step3_explanation: 'Add exponents',
    law3_step4_text: '3⁶ = 3²×³',
    law3_step4_explanation: 'Multiply exponents: 2 × 3 = 6',
    law3_step5_text: '= 729',
    law3_step5_explanation: 'Final answer',
    // Law 4 Steps
    law4_step1_text: '2³ × 5³',
    law4_step1_explanation: 'Same exponent (3)',
    law4_step2_text: '(2×2×2) × (5×5×5)',
    law4_step2_explanation: 'Expand the powers',
    law4_step3_text: '(2×5) × (2×5) × (2×5)',
    law4_step3_explanation: 'Regroup factors',
    law4_step4_text: '6 × 6 × 6 = 6³',
    law4_step4_explanation: 'Combine bases: (2×5)³',
    law4_step5_text: '= 1,000',
    law4_step5_explanation: 'Final answer',
    // Law 5 Steps
    law5_step1_text: '8² ÷ 2²',
    law5_step1_explanation: 'Same exponent (2)',
    law5_step2_text: '(8×8) ÷ (2×2)',
    law5_step2_explanation: 'Expand the powers',
    law5_step3_text: '(8÷2) × (8÷2)',
    law5_step3_explanation: 'Divide pairs',
    law5_step4_text: '4 × 4 = 4²',
    law5_step4_explanation: 'Combine: (8÷2)²',
    law5_step5_text: '= 16',
    law5_step5_explanation: 'Final answer',
    // Law 6 Steps
    law6_step1_text: '5³ ÷ 5³',
    law6_step1_explanation: 'Same base and exponent',
    law6_step2_text: '5³⁻³',
    law6_step2_explanation: 'Subtract exponents',
    law6_step3_text: '5⁰',
    law6_step3_explanation: 'Exponent becomes 0',
    law6_step4_text: '(5×5×5) ÷ (5×5×5) = 1',
    law6_step4_explanation: 'Also equals 1 by division',
    law6_step5_text: '∴ 5⁰ = 1',
    law6_step5_explanation: 'Any number⁰ = 1',
    interactivePreview: 'Interactive Preview',
    // Learn Page Controls
    showSteps: 'Show Steps',
    reset: 'Reset',
    playing: 'Playing...',
    previousLaw: 'Previous Law',
    nextLaw: 'Next Law',
    quickNavigation: 'Quick Navigation',
    lawCounter: 'Law {current} of {total}',
    clickToSeeSteps: 'Click "Show Steps" to see the step-by-step solution',
    // Real World Applications
    clickToSeeDetails: 'Click to see details',
    realWorldHeroTitle: 'Laws of Exponents in Real Life',
    realWorldHeroDescription: 'See how the laws of exponents are used to solve complex problems in science, finance, and everyday calculations!',
    // Law 1 Applications
    law1RealWorldTitle: 'Law 1: Multiplying Powers with Same Base',
    law1App1Title: 'Area Scaling in Architecture',
    law1App1Desc: 'If a wall\'s area doubles in two directions (length and height), exponents add up to show total surface growth (e.g., m² × m³ = m⁵).',
    law1App2Title: 'Compound Growth in Finance',
    law1App2Desc: 'When interest is compounded multiple times in a year, the exponent terms add up to represent total compounding periods.',
    law1App3Title: 'Data Storage Expansion',
    law1App3Desc: 'In computer systems, combining memory banks (each being 2ⁿ capacity) adds their exponents to find total addressable space.',
    // Law 1 Application Details
    law1App1OriginalNumber: 'm² × m³',
    law1App1ExponentialForm: 'm² × m³ = m²⁺³ = m⁵',
    law1App1Result: 'm⁵ (total surface growth)',
    law1App1FunFact: 'Architects use this law to calculate surface area growth when dimensions scale proportionally!',
    law1App2OriginalNumber: 'P(1 + r/n)^(n×t)',
    law1App2ExponentialForm: 'Interest compounded n times: (1 + r/n)^(n×t)',
    law1App2Result: 'Total compounding periods: n×t',
    law1App2FunFact: 'Compound interest demonstrates exponential growth, where exponents accumulate over time!',
    law1App3OriginalNumber: '2ⁿ + 2ᵐ = 2ⁿ⁺ᵐ',
    law1App3ExponentialForm: '2ⁿ × 2ᵐ = 2ⁿ⁺ᵐ (when combining memory)',
    law1App3Result: 'Total addressable space increases exponentially!',
    law1App3FunFact: 'Computer memory addresses use base-2 exponents; combining banks adds their address space!',
    // Law 2 Applications
    law2RealWorldTitle: 'Law 2: Dividing Powers with Same Base',
    law2App1Title: 'Physics – Force per Unit Area (Pressure)',
    law2App1Desc: 'When dividing energy or force values represented by powers, the exponents subtract (e.g., N·m² / m² = N).',
    law2App2Title: 'Data Transfer Rate',
    law2App2Desc: 'In computing, dividing total data by time (like bytes/sec) involves subtracting exponents of units.',
    law2App3Title: 'Scaling Down Models',
    law2App3Desc: 'In architecture or design, reducing model sizes involves subtracting scale factors in powers (e.g., 10⁶ ÷ 10³ = 10³).',
    // Law 2 Application Details
    law2App1OriginalNumber: 'N·m² / m²',
    law2App1ExponentialForm: 'N·m² ÷ m² = N·m²⁻² = N',
    law2App1Result: 'N (Force per unit area = Pressure)',
    law2App1FunFact: 'Pressure calculations in physics simplify by subtracting exponents when dividing like units!',
    law2App2OriginalNumber: 'bytes / seconds',
    law2App2ExponentialForm: '2³⁰ bytes ÷ 2⁰ seconds = bytes/sec',
    law2App2Result: 'Data transfer rate: bytes per second',
    law2App2FunFact: 'Network speeds are calculated using exponent subtraction when dividing data by time units!',
    law2App3OriginalNumber: '10⁶ ÷ 10³',
    law2App3ExponentialForm: '10⁶ ÷ 10³ = 10⁶⁻³ = 10³',
    law2App3Result: '10³ (scaled down by 1000x)',
    law2App3FunFact: 'Architectural models use exponent subtraction to calculate scale reductions accurately!',
    // Law 鲁3 Applications
    law3RealWorldTitle: 'Law 3: Power of a Power',
    law3App1Title: 'Genetics – Cell Division',
    law3App1Desc: 'Each cell divides exponentially multiple times; total divisions follow (2^m)^n = 2^(m×n).',
    law3App2Title: 'Computer Science – Nested Loops',
    law3App2Desc: 'Algorithm complexity with nested iterations increases multiplicatively in exponent form.',
    law3App3Title: 'Sound Engineering',
    law3App3Desc: 'Decibel scaling uses exponential power laws; applying the same gain multiple times multiplies exponents.',
    // Law 3 Application Details
    law3App1OriginalNumber: '(2^m)^n',
    law3App1ExponentialForm: '(2^m)^n = 2^(m×n)',
    law3App1Result: '2^(m×n) total cell divisions',
    law3App1FunFact: 'Cell division follows exponential patterns; nested divisions multiply exponents dramatically!',
    law3App2OriginalNumber: 'O(n^m)^k',
    law3App2ExponentialForm: 'O((n^m)^k) = O(n^(m×k))',
    law3App2Result: 'O(n^(m×k)) complexity',
    law3App2FunFact: 'Nested loop complexity grows exponentially; each nesting level multiplies the exponent!',
    law3App3OriginalNumber: '(gain^m)^n',
    law3App3ExponentialForm: '(gain^m)^n = gain^(m×n)',
    law3App3Result: 'gain^(m×n) total amplification',
    law3App3FunFact: 'Sound engineers use power-of-power law to calculate total gain when applying amplification stages!',
    // Law 4 Applications
    law4RealWorldTitle: 'Law 4: Multiplying Powers with Same Exponents',
    law4App1Title: 'Physics – Volume Calculation',
    law4App1Desc: 'For a rectangular box: (length × width × height)³ = (lwh)³ — same exponent applied across all sides.',
    law4App2Title: 'Economics – Combined Growth Factors',
    law4App2Desc: 'When two economies grow at the same rate, multiplying them uses the same exponent (growth rate).',
    law4App3Title: 'Computer Graphics',
    law4App3Desc: 'Scaling an image uniformly in both x and y dimensions uses the same power across variables.',
    // Law 4 Application Details
    law4App1OriginalNumber: '(l × w × h)³',
    law4App1ExponentialForm: 'l³ × w³ × h³ = (lwh)³',
    law4App1Result: '(lwh)³ cubic units',
    law4App1FunFact: 'Volume calculations simplify when all dimensions scale with the same exponent!',
    law4App2OriginalNumber: 'GDP₁^r × GDP₂^r',
    law4App2ExponentialForm: 'GDP₁^r × GDP₂^r = (GDP₁ × GDP₂)^r',
    law4App2Result: '(GDP₁ × GDP₂)^r combined growth',
    law4App2FunFact: 'Economic models use same-exponent multiplication to combine growth factors efficiently!',
    law4App3OriginalNumber: 'x² × y²',
    law4App3ExponentialForm: 'x² × y² = (xy)²',
    law4App3Result: '(xy)² uniform scaling',
    law4App3FunFact: 'Image processing uses this law for uniform scaling, maintaining aspect ratios!',
    // Law 5 Applications
    law5RealWorldTitle: 'Law 5: Dividing Powers with Same Exponents',
    law5App1Title: 'Density or Concentration',
    law5App1Desc: 'Density = mass/volume; both can grow proportionally with same exponents (e.g., scaling models).',
    law5App2Title: 'Economy Ratios',
    law5App2Desc: 'Comparing GDPs of countries growing at the same rate (power) gives ratios that maintain exponent equality.',
    law5App3Title: 'Physics – Resistance & Conductivity',
    law5App3Desc: 'When both resistance and conductivity vary exponentially with temperature, their ratio simplifies using same exponents.',
    // Law 5 Application Details
    law5App1OriginalNumber: 'mass^r / volume^r',
    law5App1ExponentialForm: 'mass^r ÷ volume^r = (mass/volume)^r',
    law5App1Result: '(mass/volume)^r = density^r',
    law5App1FunFact: 'Density calculations remain consistent when both mass and volume scale proportionally!',
    law5App2OriginalNumber: 'GDP_A^r / GDP_B^r',
    law5App2ExponentialForm: 'GDP_A^r ÷ GDP_B^r = (GDP_A/GDP_B)^r',
    law5App2Result: '(GDP_A/GDP_B)^r ratio',
    law5App2FunFact: 'Economists compare country growth ratios efficiently using same-exponent division!',
    law5App3OriginalNumber: 'R^T / C^T',
    law5App3ExponentialForm: 'Resistance^T ÷ Conductivity^T = (R/C)^T',
    law5App3Result: '(R/C)^T simplified ratio',
    law5App3FunFact: 'Physics equations simplify dramatically when both terms have matching temperature exponents!',
    // Law 6 Applications
    law6RealWorldTitle: 'Law 6: Numbers with Exponent Zero',
    law6App1Title: 'Computer Science – Base Case in Algorithms',
    law6App1Desc: 'When recursion reaches zero power, result is 1 → used in factorials, powers, etc.',
    law6App2Title: 'Physics – Steady State Conditions',
    law6App2Desc: 'When a variable stops changing (power difference = 0), system reaches unity (1× scale).',
    law6App3Title: 'Mathematics – Initialization',
    law6App3Desc: 'Any non-zero quantity raised to zero represents a "starting point" or baseline value in modeling.',
    // Law 6 Application Details
    law6App1OriginalNumber: 'n^0 in recursion',
    law6App1ExponentialForm: 'n^0 = 1 (base case)',
    law6App1Result: '1 (identity value)',
    law6App1FunFact: 'Recursive algorithms use 0-exponent as the base case, always returning 1!',
    law6App2OriginalNumber: 'variable^(m-m)',
    law6App2ExponentialForm: 'variable^(m-m) = variable^0 = 1',
    law6App2Result: '1 (steady state reached)',
    law6App2FunFact: 'When power differences reach zero, systems achieve steady state at unity scale!',
    law6App3OriginalNumber: 'initial_value^0',
    law6App3ExponentialForm: 'initial_value^0 = 1',
    law6App3Result: '1 (baseline initialization)',
    law6App3FunFact: 'Mathematical models initialize at 1, representing the starting point for calculations!',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 Introduction',
    tabExponents: '11.2 Exponents',
    massOfEarth: 'Mass of Earth',
    massOfUranus: 'Mass of Uranus',
    distancesInSpace: 'Distances in Space',
    hugeNumbersReadable: 'Huge numbers made readable with exponents',
    powerOf3: '5 to the power of 3',
    powerOf4: '3 to the power of 4',
    powerOf6: '2 to the power of 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 Exponents — Basic Concepts',
    visualExponentialForm: 'Visual Exponential Form',
    base: 'Base',
    baseDescription: 'The number being multiplied',
    exponent: 'Exponent',
    exponentDescription: 'How many times to multiply',
    power: 'Power',
    powerDescription: 'The result',
    specialName: 'Special Name',
    squared: 'Squared',
    tenSquared: '"10 squared"',
    cubed: 'Cubed',
    tenCubed: '"10 cubed"',
    primeFactorization: 'Prime Factorization',
    primeFactorizationDesc: 'Express factors compactly using exponents',
    negativeBases: 'Negative Bases',
    generalNotation: 'General Notation',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'Important Points',
    pointAnyBase: 'Any base can be used — not just 10',
    pointExponentialForm: 'Exponential form makes large numbers easier to work with',
    pointPrimeFactorization: 'Prime factorization is compact with exponents',
    
    // Home Page
    masterSimpleEquations: 'Master Simple Equations',
    masterClass7Mathematics: 'Master Class 7 Mathematics with interactive learning, practice exercises, and engaging games based on NCERT curriculum',
    startLearning: 'Start Learning',
    whatYoullLearn: 'What You\'ll Learn',
    comprehensiveTools: 'Comprehensive tools designed to make learning simple equations engaging and effective',
    introductionDesc: 'Learn the basics of simple equations with interactive examples',
    learnDesc: 'Step-by-step explanations with visual aids',
    practiceDesc: 'Solve exercises and check your solutions',
    realWorldDesc: 'See how equations apply in everyday life',
    practiceProblems: 'Practice Problems',
    interactiveExamples: 'Interactive Examples',
    readyToMaster: 'Ready to Master Simple Equations?',
    joinThousands: 'Join thousands of students and teachers who are making mathematics engaging and accessible.',
    startYourJourney: 'Start Your Journey',
    
    // Common
    correct: 'Correct!',
    incorrect: 'Try again!',
    learning: 'Learning',
    practice: 'Practice',
    assessment: 'Assessment',
    selectEquation: 'Select Equation:',
    yourAnswer: 'Your Answer:',
    submit: 'Submit',
    hint: 'Hint',
    progress: 'Progress:',
    accuracy: 'Accuracy',
    avgTime: 'Avg Time',
    correctAnswers: 'Correct',
    incorrectAnswers: 'Incorrect',
    totalExercises: 'Total',
    excellent: 'Excellent!',
    goodJob: 'Good Job!',
    keepTrying: 'Keep Trying!',
    showSolution: 'Show Solution',
    hideSolution: 'Hide Solution',
    reset: 'Reset',
    stepByStepSolution: 'Step-by-Step Solution:',
    nextStep: 'Next Step',
    complete: 'Complete',
    
    // Real World
    realWorldApps: 'Real World Applications',
    selectCategory: 'Select Category:',
    difficulty: 'Difficulty:',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    equation: 'Equation:',
    solution: 'Solution:',
    context: 'Context:',
    shopping: 'Shopping',
    cooking: 'Cooking',
    construction: 'Construction',
    sports: 'Sports',
    finance: 'Finance',
    science: 'Science',
    
    // Learn Section
    linearEquations: 'Linear Equations',
    linearEquationsDesc: 'Linear equations are equations where the highest power of the variable is 1. They can be solved using basic algebraic operations like addition, subtraction, multiplication, and division.',
    solvingByAddition: 'Solving by Addition',
    solvingByAdditionDesc: 'When we have subtraction in an equation, we add the same number to both sides to isolate the variable. This maintains the balance of the equation.',
    solvingBySubtraction: 'Solving by Subtraction',
    solvingBySubtractionDesc: 'When we have addition in an equation, we subtract the same number from both sides to isolate the variable. This maintains the balance of the equation.',
    solvingByMultiplication: 'Solving by Multiplication',
    solvingByMultiplicationDesc: 'When we have division in an equation, we multiply both sides by the same number to isolate the variable. This maintains the balance of the equation.',
    solvingByDivision: 'Solving by Division',
    solvingByDivisionDesc: 'When we have multiplication in an equation, we divide both sides by the same number to isolate the variable. This maintains the balance of the equation.',
    originalEquation: 'Original equation',
    originalEquationWithSubtraction: 'Original equation with subtraction',
    originalEquationWithAddition: 'Original equation with addition',
    originalEquationWithDivision: 'Original equation with division',
    originalEquationWithMultiplication: 'Original equation with multiplication',
    subtractFromBothSides: 'Subtract 5 from both sides',
    addToBothSides: 'Add 3 to both sides to isolate x',
    subtractFromBothSidesToIsolate: 'Subtract 4 from both sides to isolate x',
    multiplyBothSides: 'Multiply both sides by 3 to isolate x',
    divideBothSides: 'Divide both sides by 3 to isolate x',
    simplifyToFindAnswer: 'Simplify to find the answer',
    simplifyStep: 'Simplify: 5 - 5 = 0 and 12 - 5 = 7',
    verifySolution: 'Verify the solution by substituting x = 7',
    simplifyAdditionStep: 'Simplify: -3 + 3 = 0 and 8 + 3 = 11',
    verifyAdditionSolution: 'Verify the solution by substituting x = 11',
    simplifySubtractionStep: 'Simplify: 4 - 4 = 0 and 7 - 4 = 3',
    verifySubtractionSolution: 'Verify the solution by substituting x = 3',
    simplifyMultiplicationStep: 'Simplify: 3/3 = 1 and 4 × 3 = 12',
    verifyMultiplicationSolution: 'Verify the solution by substituting x = 12',
    simplifyDivisionStep: 'Simplify: 3x ÷ 3 = x and 15 ÷ 3 = 5',
    verifyDivisionSolution: 'Verify the solution by substituting x = 5',
    linearEquationExample: 'Linear Equation Example',
    additionMethodExample: 'Addition Method Example',
    subtractionMethodExample: 'Subtraction Method Example',
    multiplicationMethodExample: 'Multiplication Method Example',
    divisionMethodExample: 'Division Method Example',
    solving: 'Solving:',
    play: 'Play',
    pause: 'Pause',
    previous: 'Previous',
    next: 'Next',
    
    // Practice Mode
    practiceMode: 'Practice Mode',
    question: 'Question',
    skippedQuestions: 'Skipped Questions',
    notAttempted: 'Not Attempted',
    totalQuestions: 'Total Questions',
    finalGrade: 'Final Grade',
    accuracyRate: 'Accuracy Rate',
    avgTimePerQuestion: 'Avg Time/Question',
    questionByQuestionReview: 'Question by Question Review',
    startNewSession: 'Start New Session',
    loadingQuestions: 'Loading questions...',
    showAnswer: 'Show Answer',
    hideAnswer: 'Hide Answer',
    tryAgain: 'Try Again',
    skip: 'Skip',
    skipped: 'Skipped',
    sessionComplete: 'Session Complete!',
    sessionSummary: 'Here\'s your complete session summary',
    correctAnswer: 'Correct Answer',
    check: 'Check',
    notAttempt: 'Not Attempt',
    
    // Practice Questions
    q1_prompt: 'Using Law 1: Calculate 2³ × 2²',
    q1_explanation: 'Law 1: aᵐ × aⁿ = aᵐ⁺ⁿ. So 2³ × 2² = 2³⁺² = 2⁵ = 32',
    q2_prompt: 'Using Law 2: Calculate 5⁴ ÷ 5²',
    q2_explanation: 'Law 2: aᵐ ÷ aⁿ = aᵐ⁻ⁿ. So 5⁴ ÷ 5² = 5⁴⁻² = 5² = 25',
    q3_prompt: 'Using Law 3: Calculate (3²)³',
    q3_explanation: 'Law 3: (aᵐ)ⁿ = aᵐⁿ. So (3²)³ = 3²×³ = 3⁶ = 729',
    q4_prompt: 'Using Law 4: Calculate 2³ × 5³',
    q4_explanation: 'Law 4: aᵐ × bᵐ = (ab)ᵐ. So 2³ × 5³ = (2 × 5)³ = 10³ = 1,000',
    q5_prompt: 'Using Law 5: Calculate 8² ÷ 2²',
    q5_explanation: 'Law 5: aᵐ ÷ bᵐ = (a/b)ᵐ. So 8² ÷ 2² = (8/2)² = 4² = 16',
    q6_prompt: 'Using Law 6: Calculate 7⁰',
    q6_explanation: 'Law 6: a⁰ = 1 (for any non-zero a). So 7⁰ = 1',
    
    // Practice Questions
    practice_q1: 'Solve: x + 7 = 15',
    practice_q2: 'Solve: x + 4 = 12',
    practice_q3: 'Solve: x + 3 = 21',
    practice_q4: 'Solve: x + 2 = 8',
    practice_q5: 'Solve: x + 3 = 11',
    practice_q6: 'Solve: x + 5 = 9',
    practice_q7: 'Solve: x + 6 = 18',
    practice_q8: 'Solve: x + 2 = 7',
    practice_q9: 'Solve: x + 8 = 33',
    practice_q10: 'Solve: x + 7 = 13',
    practice_q11: 'Solve: x + 3 = 8',
    practice_q12: 'Solve: x + 12 = 30',
    
    // Exponents - Section 1: Introduction
    exp_intro_title: 'Why Do We Need Exponents?',
    exp_intro_text: 'Very large numbers are difficult to work with:',
    exp_problem_1: 'Hard to Read: 5,970,000,000,000,000,000,000,000 kg',
    exp_problem_2: 'Hard to Understand: How big is this number?',
    exp_problem_3: 'Hard to Compare: Which is bigger - Earth or Uranus?',
    exp_intro_solution: 'Solution: Use exponents to write numbers in a shorter, simpler form!',
    exp_example_title: 'Real-World Example',
    exp_example_before: 'Mass of Earth = 5,970,000,000,000,000,000,000,000 kg',
    exp_example_after: 'Mass of Earth = 5.97 × 10²⁴ kg',
    exp_example_benefit: 'Much easier to read and compare!',
    exp_before: 'Before',
    exp_after: 'After',
    
    // Exponents - Section 2: What Are Exponents
    exp_what_are_title: 'What Are Exponents?',
    exp_what_are_text: 'Exponents let us write repeated multiplication in a compact way.',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'Repeated multiplication',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'Exponential form',
    exp_main_example: 'Main Example',
    exp_term_base: 'Base',
    exp_term_base_def: 'The number being multiplied',
    exp_term_base_ex: 'In 10⁴, base = 10',
    exp_term_exp: 'Exponent',
    exp_term_exp_def: 'How many times to multiply the base',
    exp_term_exp_ex: 'In 10⁴, exponent = 4',
    exp_term_power: 'Power',
    exp_term_power_def: 'The whole expression',
    exp_term_power_ex: '10⁴ is read as "10 to the power of 4"',
    exp_key_terms: 'Key Terms to Remember:',
    
    // Exponents - Section 3: Working with Examples
    exp_examples_title: 'Working with Examples',
    exp_conversion_text: 'Let\'s see how numbers are converted to exponential form:',
    exp_example: 'Example',
    exp_step1: 'Step 1: Write as multiplication',
    exp_step2: 'Step 2: Write in exponential form',
    exp_base: 'Base',
    exp_exponent: 'Exponent',
    exp_read_as: 'Read as',
    exp_ex1_reading: '10 raised to the power of 3',
    exp_ex2_reading: '3 raised to the power of 4',
    exp_ex3_reading: '5 cubed',
    exp_ex4_reading: '2 raised to the power of 5',
    
    // Exponents - Section 4: Special Names
    exp_special_title: 'Special Names',
    exp_special_intro: 'Some exponents have special names that you\'ll use often:',
    exp_squared: 'Squared',
    exp_squared_read: 'squared',
    exp_cubed: 'Cubed',
    exp_cubed_read: 'cubed',
    exp_special_note: 'These special names come from geometry - squared from area of a square, cubed from volume of a cube!',
    exp_power_of: 'Power of',
    exp_fun_fact: 'Fun Fact',
    
    // Exponents - Section 5: Interactive Practice
    exp_practice_title: 'Interactive Practice',
    exp_interactive_intro: 'Try it yourself! Change the base and exponent to see how exponents work:',
    exp_expanded: 'Expanded Form',
    exp_exponential_form: 'Exponential Form',
    exp_result: 'Result',
    exp_reading_title: 'Reading',
    exp_raised_to: 'raised to the power of',
    exp_or: 'or',
    
    // Exponents - Common Terms
    of: 'of',
    example: 'Example',
    formula: 'Formula',
    explanation: 'Explanation'
  },
  hi: {
    // Navigation
    home: 'होम',
    introduction: 'परिचय',
    learn: 'सीखें',
    realWorld: 'वास्तविक दुनिया',
    simpleEquations: 'सरल समीकरण - जोड़',
    simpleEquationsTitle: 'सरल समीकरण - जोड़',
    exponentsTitle: 'घातांक के नियम',
    // Laws of Exponents hero (for Learn page)
    expHeroTitle: 'घातांक के नियम',
    expHeroLine1: 'घातांकों के साथ काम करने के लिए मौलिक नियमों को सीखें।',
    expHeroLine2: 'जटिल घातांकीय अभिव्यक्तियों को सरल बनाने के लिए इन नियमों में महारत हासिल करें!',
    // Laws of Exponents - Section
    law1Title: 'नियम 1: समान आधार वाली घातों का गुणन',
    law1Formula: 'aᵐ × aⁿ = aᵐ⁺ⁿ',
    law1Description: 'समान आधार वाली घातों को गुणा करते समय, घातांकों को जोड़ें।',
    law1Example: '2³ × 2² = 2³⁺² = 2⁵ = 32',
    law2Title: 'नियम 2: समान आधार वाली घातों का भाग',
    law2Formula: 'aᵐ ÷ aⁿ = aᵐ⁻ⁿ (जहाँ m > n)',
    law2Description: 'समान आधार वाली घातों को भाग देते समय, घातांकों को घटाएं।',
    law2Example: '5⁴ ÷ 5² = 5⁴⁻² = 5² = 25',
    law3Title: 'नियम 3: घात की घात',
    law3Formula: '(aᵐ)ⁿ = aᵐⁿ',
    law3Description: 'एक घात को दूसरी घात तक बढ़ाते समय, घातांकों को गुणा करें।',
    law3Example: '(3²)³ = 3²×³ = 3⁶ = 729',
    law4Title: 'नियम 4: समान घातांक वाली घातों का गुणन',
    law4Formula: 'aᵐ × bᵐ = (ab)ᵐ',
    law4Description: 'समान घातांक वाली घातों को गुणा करते समय, आधारों को गुणा करें।',
    law4Example: '2³ × 5³ = (2 × 5)³ = 10³ = 1,000',
    law5Title: 'नियम 5: समान घातांक वाली घातों का भाग',
    law5Formula: 'aᵐ ÷ bᵐ = (a/b)ᵐ',
    law5Description: 'समान घातांक वाली घातों को भाग देते समय, आधारों को भाग दें।',
    îlaw5Example: '8² ÷ 2² = (8/2)² = 4² = 16',
    law6Title: 'नियम 6: घातांक शून्य',
    law6Formula: 'a⁰ = 1 (जहाँ a ≠ 0)',
    law6Description: 'शून्य के अलावा किसी भी संख्या की शून्य घात एक के बराबर होती है।',
    law6Example: '5⁰ = 1, 10⁰ = 1, 100⁰ = 1',
    lawSummary: 'सारांश',
    exampleLabel: 'उदाहरण',
    lawSummaryText: 'ये छह नियम सभी घातांक गणनाओं की नींव बनाते हैं!',
    // Law 1 Steps
    law1_step1_text: '2³ × 2²',
    law1_step1_explanation: 'समान आधार (2)',
    law1_step2_text: '(2×2×2) × (2×2)',
    law1_step2_explanation: 'घातों का विस्तार करें',
    law1_step3_text: '2×2×2×2×2',
    law1_step3_explanation: 'कुल 2 की गिनती करें (5 बार)',
    law1_step4_text: '2⁵ = 2³⁺²',
    law1_step4_explanation: 'घातांक जोड़ें: 3 + 2 = 5',
    law1_step5_text: '= 32',
    law1_step5_explanation: 'अंतिम उत्तर',
    // Law 2 Steps
    law2_step1_text: '5⁴ ÷ 5²',
    law2_step1_explanation: 'समान आधार (5)',
    law2_step2_text: '(5×5×5×5) ÷ (5×5)',
    law2_step2_explanation: 'घातों का विस्तार करें',
    law2_step3_text: '5×5',
    law2_step3_explanation: 'सामान्य गुणनखंडों को रद्द करें',
    law2_step4_text: '5² = 5⁴⁻²',
    law2_step4_explanation: 'घातांक घटाएं: 4 - 2 = 2',
    law2_step5_text: '= 25',
    law2_step5_explanation: 'अंतिम उत्तर',
    // Law 3 Steps
    law3_step1_text: '(3²)³',
    law3_step1_explanation: 'घात की घात',
    law3_step2_text: '3² × 3² × 3²',
    law3_step2_explanation: '3² को 3 बार गुणा',
    law3_step3_text: '3²⁺²⁺²',
    law3_step3_explanation: 'घातांक जोड़ें',
    law3_step4_text: '3⁶ = 3²×³',
    law3_step4_explanation: 'घातांक गुणा करें: 2 × 3 = 6',
    law3_step5_text: '= 729',
    law3_step5_explanation: 'अंतिम उत्तर',
    // Law 4 Steps
    law4_step1_text: '2³ × 5³',
    law4_step1_explanation: 'समान घातांक (3)',
    law4_step2_text: '(2×2×2) × (5×5×5)',
    law4_step2_explanation: 'घातों का विस्तार करें',
    law4_step3_text: '(2×5) × (2×5) × (2×5)',
    law4_step3_explanation: 'गुणनखंडों को पुनर्व्यवस्थित करें',
    law4_step4_text: '6 × 6 × 6 = 6³',
    law4_step4_explanation: 'आधारों को मिलाएं: (2×5)³',
    law4_step5_text: '= 1,000',
    law4_step5_explanation: 'अंतिम उत्तर',
    // Law 5 Steps
    law5_step1_text: '8² ÷ 2²',
    law5_step1_explanation: 'समान घातांक (2)',
    law5_step2_text: '(8×8) ÷ (2×2)',
    law5_step2_explanation: 'घातों का विस्तार करें',
    law5_step3_text: '(8÷2) × (8÷2)',
    law5_step3_explanation: 'जोड़े बांटें',
    law5_step4_text: '4 × 4 = 4²',
    law5_step4_explanation: 'मिलाएं: (8÷2)²',
    law5_step5_text: '= 16',
    law5_step5_explanation: 'अंतिम उत्तर',
    // Law 6 Steps
    law6_step1_text: '5³ ÷ 5³',
    law6_step1_explanation: 'समान आधार और घातांक',
    law6_step2_text: '5³⁻³',
    law6_step2_explanation: 'घातांक घटाएं',
    law6_step3_text: '5⁰',
    law6_step3_explanation: 'घातांक 0 हो जाता है',
    law6_step4_text: '(5×5×5) ÷ (5×5×5) = 1',
    law6_step4_explanation: 'भाग द्वारा भी 1 के बराबर',
    law6_step5_text: '∴ 5⁰ = 1',
    law6_step5_explanation: 'कोई भी संख्या⁰ = 1',
    interactivePreview: 'इंटरैक्टिव पूर्वावलोकन',
    // Learn Page Controls
    showSteps: 'चरण दिखाएं',
    reset: 'रीसेट',
    playing: 'चल रहा है...',
    previousLaw: 'पिछला नियम',
    nextLaw: 'अगला नियम',
    quickNavigation: 'त्वरित नेविगेशन',
    lawCounter: 'नियम {current} का {total}',
    clickToSeeSteps: 'चरण-दर-चरण समाधान देखने के लिए "चरण दिखाएं" पर क्लिक करें',
    // Real World Applications
    clickToSeeDetails: 'विवरण देखने के लिए क्लिक करें',
    realWorldHeroTitle: 'वास्तविक जीवन में घातांक के नियम',
    realWorldHeroDescription: 'देखें कि घातांक के नियम विज्ञान, वित्त और रोजमर्रा की गणनाओं में जटिल समस्याओं को हल करने के लिए कैसे उपयोग किए जाते हैं!',
    // Law 1 Applications
    law1RealWorldTitle: 'नियम 1: समान आधार वाली घातों का गुणन',
    law1App1Title: 'स्थापत्य में क्षेत्रफल स्केलिंग',
    law1App1Desc: 'यदि दीवार का क्षेत्रफल दो दिशाओं में दोगुना हो जाता है (लंबाई और ऊंचाई), तो घातांक कुल सतह वृद्धि दिखाने के लिए जुड़ते हैं (उदा., m² × m³ = m⁵).',
    law1App2Title: 'वित्त में चक्रवृद्धि वृद्धि',
    law1App2Desc: 'जब ब्याज वर्ष में कई बार संयोजित होता है, तो घातांक पद कुल संयोजन अवधि का प्रतिनिधित्व करने के लिए जुड़ते हैं।',
    law1App3Title: 'डेटा स्टोरेज विस्तार',
    law1App3Desc: 'कंप्यूटर सिस्टम में, मेमोरी बैंकों को जोड़ना (प्रत्येक 2ⁿ क्षमता) उनके घातांक जोड़ता है कुल पता योग्य स्थान खोजने के लिए।',
    // Law 2 Applications
    law2RealWorldTitle: 'नियम 2: समान आधार वाली घातों का भाग',
    law2App1Title: 'भौतिकी – प्रति इकाई क्षेत्रफल बल (दबाव)',
    law2App1Desc: 'घातों द्वारा प्रतिनिधित्व ऊर्जा या बल मूल्यों को विभाजित करते समय, घातांक घटाते हैं (उदा., N·m² / m² = N).',
    law2App2Title: 'डेटा ट्रांसफर दर',
    law2App2Desc: 'कंप्यूटिंग में, समय से कुल डेटा को विभाजित करना (जैसे bytes/sec) इकाइयों के घातांकों को घटाना शामिल करता है।',
    law2App3Title: 'मॉडल स्केलिंग डाउन',
    law2App3Desc: 'स्थापत्य या डिजाइन में, मॉडल आकार को कम करना घातों में स्केल कारकों को घटाना शामिल करता है (उदा., 10⁶ ÷ 10³ = 10³).',
    // Law 3 Applications
    law3RealWorldTitle: 'नियम 3: घात की घात',
    law3App1Title: 'आनुवंशिकी – कोशिका विभाजन',
    law3App1Desc: 'प्रत्येक कोशिका कई बार घातांकीय रूप से विभाजित होती है; कुल विभाजन (2^m)^n = 2^(m×n) का अनुसरण करते हैं।',
    law3App2Title: 'कंप्यूटर विज्ञान – नेस्टेड लूप्स',
    law3App2Desc: 'नेस्टेड पुनरावृत्तियों के साथ एल्गोरिदम जटिलता घातांक रूप में गुणात्मक रूप से बढ़ती है।',
    law3App3Title: 'ध्वनि इंजीनियरिंग',
    law3App3Desc: 'डेसिबल स्केलिंग घातांकीय शक्ति नियमों का उपयोग करती है; एक ही लाभ को कई बार लागू करना घातांकों को गुणा करता है।',
    // Law 4 Applications
    law4RealWorldTitle: 'नियम 4: समान घातांक वाली घातों का गुणन',
    law4App1Title: 'भौतिकी – आयतन गणना',
    law4App1Desc: 'आयताकार बॉक्स के लिए: (लंबाई × चौड़ाई × ऊंचाई)³ = (lwh)³ — सभी पक्षों में समान घातांक लागू किया गया।',
    law4App2Title: 'अर्थशास्त्र – संयुक्त वृद्धि कारक',
    law4App2Desc: 'जब दो अर्थव्यवस्थाएं समान दर पर बढ़ती हैं, तो उन्हें गुणा करना समान घातांक (वृद्धि दर) का उपयोग करता है।',
    law4App3Title: 'कंप्यूटर ग्राफिक्स',
    law4App3Desc: 'एक छवि को दोनों x और y आयामों में समान रूप से स्केल करना चरों में समान शक्ति का उपयोग करता है।',
    // Law 5 Applications
    law5RealWorldTitle: 'नियम 5: समान घातांक वाली घातों का भाग',
    law5App1Title: 'घनत्व या सांद्रता',
    law5App1Desc: 'घनत्व = द्रव्यमान/आयतन; दोनों समान घातांकों के साथ आनुपातिक रूप से बढ़ सकते हैं (उदा., स्केलिंग मॉडल)।',
    law5App2Title: 'अर्थव्यवस्था अनुपात',
    law5App2Desc: 'समान दर पर बढ़ने वाले देशों की GDPs की तुलना करना (शक्ति) अनुपात देता है जो घातांक समानता बनाए रखता है।',
    law5App3Title: 'भौतिकी – प्रतिरोध और चालकता',
    law5App3Desc: 'जब प्रतिरोध और चालकता दोनों तापमान के साथ घातांकीय रूप से भिन्न होते हैं, तो उनका अनुपात समान घातांकों का उपयोग करके सरल हो जाता है।',
    // Law 6 Applications
    law6RealWorldTitle: 'नियम 6: शून्य घातांक वाली संख्याएं',
    law6App1Title: 'कंप्यूटर विज्ञान – एल्गोरिदम में आधार मामला',
    law6App1Desc: 'जब पुनरावृत्ति शून्य शक्ति तक पहुंचती है, तो परिणाम 1 होता है → फैक्टोरियल्स, शक्तियों आदि में उपयोग किया जाता है।',
    law6App2Title: 'भौतिकी – स्थिर अवस्था स्थितियां',
    law6App2Desc: 'जब एक चर बदलना बंद कर देता है (शक्ति अंतर = 0), तो सिस्टम एकता (1× स्केल) तक पहुंचता है।',
    law6App3Title: 'गणित – आरंभीकरण',
    law6App3Desc: 'शून्य तक उठाई गई कोई भी गैर-शून्य मात्रा मॉडलिंग में एक "प्रारंभिक बिंदु" या बेसलाइन मूल्य का प्रतिनिधित्व करती है।',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 परिचय',
    tabExponents: '11.2 घातांक',
    massOfEarth: 'पृथ्वी का द्रव्यमान',
    massOfUranus: 'यूरेनस का द्रव्यमान',
    distancesInSpace: 'अंतरिक्ष में दूरियाँ',
    hugeNumbersReadable: 'घातांकों से बड़ी संख्याएँ पढ़ने योग्य बनती हैं',
    powerOf3: '5 की घात 3',
    powerOf4: '3 की घात 4',
    powerOf6: '2 की घात 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 घातांक — मूल अवधारणाएँ',
    visualExponentialForm: 'दृश्य घातांकीय रूप',
    base: 'आधार',
    baseDescription: 'वह संख्या जिसे गुणा किया जा रहा है',
    exponent: 'घातांक',
    exponentDescription: 'कितनी बार गुणा करना है',
    power: 'घात',
    powerDescription: 'परिणाम',
    specialName: 'विशेष नाम',
    squared: 'वर्ग',
    tenSquared: '"10 का वर्ग"',
    cubed: 'घन',
    tenCubed: '"10 का घन"',
    primeFactorization: 'अभाज्य गुणनखंडन',
    primeFactorizationDesc: 'घातांकों का उपयोग करके गुणनखंडों को संक्षिप्त रूप से व्यक्त करें',
    negativeBases: 'ऋणात्मक आधार',
    generalNotation: 'सामान्य संकेतन',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'महत्वपूर्ण बिंदु',
    pointAnyBase: 'कोई भी आधार उपयोग किया जा सकता है — केवल 10 ही नहीं',
    pointExponentialForm: 'घातांकीय रूप बड़ी संख्याओं के साथ काम करना आसान बनाता है',
    pointPrimeFactorization: 'अभाज्य गुणनखंडन घातांकों के साथ संक्षिप्त होता है',
    
    // Home Page
    masterSimpleEquations: 'सरल समीकरणों में महारत हासिल करें',
    masterClass7Mathematics: 'एनसीईआरटी पाठ्यक्रम के आधार पर इंटरैक्टिव सीखने, अभ्यास अभ्यास और आकर्षक गेम के साथ कक्षा 7 गणित में महारत हासिल करें',
    startLearning: 'सीखना शुरू करें',
    whatYoullLearn: 'आप क्या सीखेंगे',
    comprehensiveTools: 'सरल समीकरणों को सीखने को आकर्षक और प्रभावी बनाने के लिए डिज़ाइन किए गए व्यापक उपकरण',
    introductionDesc: 'इंटरैक्टिव उदाहरणों के साथ सरल समीकरणों की मूल बातें सीखें',
    learnDesc: 'दृश्य सहायता के साथ चरण-दर-चरण स्पष्टीकरण',
    practiceDesc: 'अभ्यास हल करें और अपने समाधान जांचें',
    realWorldDesc: 'देखें कि समीकरण रोजमर्रा की जिंदगी में कैसे लागू होते हैं',
    practiceProblems: 'अभ्यास समस्याएं',
    interactiveExamples: 'इंटरैक्टिव उदाहरण',
    readyToMaster: 'सरल समीकरणों में महारत हासिल करने के लिए तैयार हैं?',
    joinThousands: 'हजारों छात्रों और शिक्षकों में शामिल हों जो गणित को आकर्षक और सुलभ बना रहे हैं।',
    startYourJourney: 'अपनी यात्रा शुरू करें',
    
    // Common
    correct: 'सही!',
    incorrect: 'फिर कोशिश करें!',
    learning: 'सीखना',
    practice: 'अभ्यास',
    assessment: 'मूल्यांकन',
    selectEquation: 'समीकरण चुनें:',
    yourAnswer: 'आपका उत्तर:',
    submit: 'जमा करें',
    hint: 'संकेत',
    progress: 'प्रगति:',
    accuracy: 'सटीकता',
    avgTime: 'औसत समय',
    correctAnswers: 'सही',
    incorrectAnswers: 'गलत',
    totalExercises: 'कुल',
    excellent: 'उत्कृष्ट!',
    goodJob: 'अच्छा काम!',
    keepTrying: 'कोशिश करते रहें!',
    showSolution: 'समाधान दिखाएं',
    hideSolution: 'समाधान छुपाएं',
    reset: 'रीसेट',
    stepByStepSolution: 'चरण-दर-चरण समाधान:',
    nextStep: 'अगला चरण',
    complete: 'पूर्ण',
    
    // Real World
    realWorldApps: 'वास्तविक दुनिया के अनुप्रयोग',
    selectCategory: 'श्रेणी चुनें:',
    difficulty: 'कठिनाई:',
    beginner: 'शुरुआती',
    intermediate: 'मध्यम',
    advanced: 'उन्नत',
    equation: 'समीकरण:',
    solution: 'समाधान:',
    context: 'संदर्भ:',
    shopping: 'खरीदारी',
    cooking: 'खाना पकाना',
    construction: 'निर्माण',
    sports: 'खेल',
    finance: 'वित्त',
    science: 'विज्ञान',
    
    // Learn Section
    linearEquations: 'रैखिक समीकरण',
    linearEquationsDesc: 'रैखिक समीकरण वे समीकरण हैं जहाँ चर की सबसे बड़ी घात 1 है।',
    solvingByAddition: 'जोड़ द्वारा हल करना',
    solvingByAdditionDesc: 'जब हमारे पास समीकरण में घटाव होता है, तो हम चर को अलग करने के लिए दोनों पक्षों में समान संख्या जोड़ते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingBySubtraction: 'घटाव द्वारा हल करना',
    solvingBySubtractionDesc: 'जब हमारे पास समीकरण में जोड़ होता है, तो हम चर को अलग करने के लिए दोनों पक्षों से समान संख्या घटाते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingByMultiplication: 'गुणा द्वारा हल करना',
    solvingByMultiplicationDesc: 'जब हमारे पास समीकरण में भाग होता है, तो हम चर को अलग करने के लिए दोनों पक्षों को समान संख्या से गुणा करते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingByDivision: 'भाग द्वारा हल करना',
    solvingByDivisionDesc: 'जब हमारे पास समीकरण में गुणा होता है, तो हम चर को अलग करने के लिए दोनों पक्षों को समान संख्या से भाग देते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    originalEquation: 'मूल समीकरण',
    originalEquationWithSubtraction: 'घटाव के साथ मूल समीकरण',
    originalEquationWithAddition: 'जोड़ के साथ मूल समीकरण',
    originalEquationWithDivision: 'भाग के साथ मूल समीकरण',
    originalEquationWithMultiplication: 'गुणा के साथ मूल समीकरण',
    subtractFromBothSides: 'दोनों पक्षों से 5 घटाएं',
    addToBothSides: 'x को अलग करने के लिए दोनों पक्षों में 3 जोड़ें',
    subtractFromBothSidesToIsolate: 'x को अलग करने के लिए दोनों पक्षों से 4 घटाएं',
    multiplyBothSides: 'x को अलग करने के लिए दोनों पक्षों को 3 से गुणा करें',
    divideBothSides: 'x को अलग करने के लिए दोनों पक्षों को 3 से भाग दें',
    simplifyToFindAnswer: 'उत्तर ज्ञात करने के लिए सरल करें',
    simplifyStep: 'सरल करें: 5 - 5 = 0 और 12 - 5 = 7',
    verifySolution: 'x = 7 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyAdditionStep: 'सरल करें: -3 + 3 = 0 और 8 + 3 = 11',
    verifyAdditionSolution: 'x = 11 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifySubtractionStep: 'सरल करें: 4 - 4 = 0 और 7 - 4 = 3',
    verifySubtractionSolution: 'x = 3 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyMultiplicationStep: 'सरल करें: 3/3 = 1 और 4 × 3 = 12',
    verifyMultiplicationSolution: 'x = 12 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyDivisionStep: 'सरल करें: 3x ÷ 3 = x और 15 ÷ 3 = 5',
    verifyDivisionSolution: 'x = 5 प्रतिस्थापित करके समाधान सत्यापित करें',
    linearEquationExample: 'रैखिक समीकरण उदाहरण',
    additionMethodExample: 'जोड़ विधि उदाहरण',
    subtractionMethodExample: 'घटाव विधि उदाहरण',
    multiplicationMethodExample: 'गुणा विधि उदाहरण',
    divisionMethodExample: 'भाग विधि उदाहरण',
    solving: 'हल करना:',
    play: 'चलाएं',
    pause: 'रोकें',
    previous: 'पिछला',
    next: 'अगला',
    
    // Practice Mode
    practiceMode: 'अभ्यास मोड',
    question: 'प्रश्न',
    skippedQuestions: 'छोड़े गए प्रश्न',
    notAttempted: 'प्रयास नहीं किया',
    totalQuestions: 'कुल प्रश्न',
    finalGrade: 'अंतिम ग्रेड',
    accuracyRate: 'सटीकता दर',
    avgTimePerQuestion: 'प्रति प्रश्न औसत समय',
    questionByQuestionReview: 'प्रश्न दर प्रश्न समीक्षा',
    startNewSession: 'नया सत्र शुरू करें',
    loadingQuestions: 'प्रश्न लोड हो रहे हैं...',
    showAnswer: 'उत्तर दिखाएं',
    hideAnswer: 'उत्तर छुपाएं',
    tryAgain: 'फिर कोशिश करें',
    skip: 'छोड़ें',
    skipped: 'छोड़ा गया',
    sessionComplete: 'सत्र पूरा!',
    sessionSummary: 'यहाँ आपका पूरा सत्र सारांश है',
    correctAnswer: 'सही उत्तर',
    check: 'जांच',
    notAttempt: 'प्रयास नहीं करें',
    
    // Practice Questions - Exponents
    q1_prompt: 'नियम 1 का उपयोग करें: 2³ × 2² की गणना करें',
    q1_explanation: 'नियम 1: aᵐ × aⁿ = aᵐ⁺ⁿ. इसलिए 2³ × 2² = 2³⁺² = 2⁵ = 32',
    q2_prompt: 'नियम 2 का उपयोग करें: 5⁴ ÷ 5² की गणना करें',
    q2_explanation: 'नियम 2: aᵐ ÷ aⁿ = aᵐ⁻ⁿ. इसलिए 5⁴ ÷ 5² = 5⁴⁻² = 5² = 25',
    q3_prompt: 'नियम 3 का उपयोग करें: (3²)³ की गणना करें',
    q3_explanation: 'नियम 3: (aᵐ)ⁿ = aᵐⁿ. इसलिए (3²)³ = 3²×³ = 3⁶ = 729',
    q4_prompt: 'नियम 4 का उपयोग करें: 2³ × 5³ की गणना करें',
    q4_explanation: 'नियम 4: aᵐ × bᵐ = (ab)ᵐ. इसलिए 2³ × 5³ = (2 × 5)³ = 10³ = 1,000',
    q5_prompt: 'नियम 5 का उपयोग करें: 8² ÷ 2² की गणना करें',
    q5_explanation: 'नियम 5: aᵐ ÷ bᵐ = (a/b)ᵐ. इसलिए 8² ÷ 2² = (8/2)² = 4² = 16',
    q6_prompt: 'नियम 6 का उपयोग करें: 7⁰ की गणना करें',
    q6_explanation: 'नियम 6: a⁰ = 1 (किसी भी गैर-शून्य a के लिए). इसलिए 7⁰ = 1',
    
    // Practice Questions
    practice_q1: 'हल करें: x + 7 = 15',
    practice_q2: 'हल करें: x + 4 = 12',
    practice_q3: 'हल करें: x + 3 = 21',
    practice_q4: 'हल करें: x + 2 = 8',
    practice_q5: 'हल करें: x + 3 = 11',
    practice_q6: 'हल करें: x + 5 = 9',
    practice_q7: 'हल करें: x + 6 = 18',
    practice_q8: 'हल करें: x + 2 = 7',
    practice_q9: 'हल करें: x + 8 = 33',
    practice_q10: 'हल करें: x + 7 = 13',
    practice_q11: 'हल करें: x + 3 = 8',
    practice_q12: 'हल करें: x + 12 = 30',
    
    // Exponents
    exp_intro_title: 'घातांक क्यों चाहिए?',
    exp_intro_text: 'बहुत बड़ी संख्याओं के साथ काम करना मुश्किल है:',
    exp_problem_1: 'पढ़ना मुश्किल: 5,970,000,000,000,000,000,000,000 किलो',
    exp_problem_2: 'समझना मुश्किल: यह संख्या कितनी बड़ी है?',
    exp_problem_3: 'तुलना करना मुश्किल: कौन बड़ा है - पृथ्वी या यूरेनस?',
    exp_intro_solution: 'समाधान: संख्याओं को छोटे, सरल रूप में लिखने के लिए घातांक का उपयोग करें!',
    exp_example_title: 'वास्तविक दुनिया का उदाहरण',
    exp_example_before: 'पृथ्वी का द्रव्यमान = 5,970,000,000,000,000,000,000,000 किलो',
    exp_example_after: 'पृथ्वी का द्रव्यमान = 5.97 × 10²⁴ किलो',
    exp_example_benefit: 'पढ़ने और तुलना करने में बहुत आसान!',
    exp_before: 'पहले',
    exp_after: 'बाद में',
    exp_what_are_title: 'घातांक क्या हैं?',
    exp_what_are_text: 'घातांक हमें दोहरा गुणन को संक्षिप्त तरीके से लिखने देते हैं।',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'दोहरा गुणन',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'घातांक रूप',
    exp_main_example: 'मुख्य उदाहरण',
    exp_term_base: 'आधार',
    exp_term_base_def: 'गुणा होने वाली संख्या',
    exp_term_base_ex: '10⁴ में, आधार = 10',
    exp_term_exp: 'घातांक',
    exp_term_exp_def: 'आधार को कितनी बार गुणा करना है',
    exp_term_exp_ex: '10⁴ में, घातांक = 4',
    exp_term_power: 'घात',
    exp_term_power_def: 'पूरी अभिव्यक्ति',
    exp_term_power_ex: '10⁴ को "10 की घात 4" पढ़ा जाता है',
    exp_key_terms: 'याद रखने योग्य मुख्य शब्द:',
    exp_examples_title: 'उदाहरणों के साथ कार्य',
    exp_conversion_text: 'देखते हैं कि संख्याओं को घातांक रूप में कैसे परिवर्तित किया जाता है:',
    exp_example: 'उदाहरण',
    exp_step1: 'चरण 1: गुणन के रूप में लिखें',
    exp_step2: 'चरण 2: घातांक रूप में लिखें',
    exp_base: 'आधार',
    exp_exponent: 'घातांक',
    exp_read_as: 'पढ़ें',
    exp_ex1_reading: '10 की घात 3',
    exp_ex2_reading: '3 की घात 4',
    exp_ex3_reading: '5 घन',
    exp_ex4_reading: '2 की घात 5',
    exp_special_title: 'विशेष नाम',
    exp_special_intro: 'कुछ घातांकों के विशेष नाम हैं जिनका आप अक्सर उपयोग करेंगे:',
    exp_squared: 'वर्ग',
    exp_squared_read: 'वर्ग',
    exp_cubed: 'घन',
    exp_cubed_read: 'घन',
    exp_special_note: 'ये विशेष नाम ज्यामिति से आते हैं - वर्ग वर्ग के क्षेत्रफल से, घन घन के आयतन से!',
    exp_power_of: 'घात',
    exp_fun_fact: 'रोचक तथ्य',
    exp_practice_title: 'इंटरैक्टिव अभ्यास',
    exp_interactive_intro: 'खुद आजमाएं! घातांक कैसे काम करते हैं देखने के लिए आधार और घातांक को बदलें:',
    exp_expanded: 'विस्तारित रूप',
    exp_exponential_form: 'घातांक रूप',
    exp_result: 'परिणाम',
    exp_reading_title: 'पढ़ना',
    exp_raised_to: 'की घात',
    exp_or: 'या',
    of: 'का',
    example: 'उदाहरण',
    formula: 'सूत्र',
    explanation: 'स्पष्टीकरण'
  },
  gu: {
    // Navigation
    home: 'ઘર',
    introduction: 'પરિચય',
    learn: 'શીખો',
    realWorld: 'વાસ્તવિક વિશ્વ',
    simpleEquations: 'સરળ સમીકરણો - ઉમેરણ',
    simpleEquationsTitle: 'સરળ સમીકરણો - ઉમેરણ',
    exponentsTitle: 'ઘાતાંકના નિયમો',
    // Laws of Exponents hero (for Learn page)
    expHeroTitle: 'ઘાતાંકના નિયમો',
    expHeroLine1: 'ઘાતાંકો સાથે કામ કરવા માટેના મૂળભૂત નિયમો શીખો.',
    expHeroLine2: 'જટિલ ઘાતાંકીય અભિવ્યક્તિઓને સરળ બનાવવા માટે આ નિયમોમાં નિપુણતા મેળવો!',
    // Laws of Exponents - Section
    law1Title: 'નિયમ 1: સમાન આધારવાળી ઘાતોનો ગુણાકાર',
    law1Formula: 'aᵐ × aⁿ = aᵐ⁺ⁿ',
    law1Description: 'સમાન આધારવાળી ઘાતોનો ગુણાકાર કરતી વખતે, ઘાતાંકો ઉમેરો.',
    law1Example: '2³ × 2² = 2³⁺² = 2⁵ = 32',
    law2Title: 'નિયમ 2: સમાન આધારવાળી ઘાતોનો ભાગાકાર',
    law2Formula: 'aᵐ ÷ aⁿ = aᵐ⁻ⁿ (જ્યાં m > n)',
    law2Description: 'સમાન આધારવાળી ઘાતોનો ભાગાકાર કરતી વખતે, ઘાતાંકો બાદ કરો.',
    law2Example: '5⁴ ÷ 5² = 5⁴⁻² = 5² = 25',
    law3Title: 'નિયમ 3: ઘાતની ઘાત',
    law3Formula: '(aᵐ)ⁿ = aᵐⁿ',
    law3Description: 'એક ઘાતને બીજી ઘાત સુધી વધારતી વખતે, ઘાતાંકોનો ગુણાકાર કરો.',
    law3Example: '(3²)³ = 3²×³ = 3⁶ = 729',
    law4Title: 'નિયમ 4: સમાન ઘાતાંકવાળી ઘાતોનો ગુણાકાર',
    law4Formula: 'aᵐ × bᵐ = (ab)ᵐ',
    law4Description: 'સમાન ઘાતાંકવાળી ઘાતોનો ગુણાકાર કરતી વખતે, આધારોનો ગુણાકાર કરો.',
    law4Example: '2³ × 5³ = (2 × 5)³ = 10³ = 1,000',
    law5Title: 'નિયમ 5: સમાન ઘાતાંકવાળી ઘાતોનો ભાગાકાર',
    law5Formula: 'aᵐ ÷ bᵐ = (a/b)ᵐ',
    law5Description: 'સમાન ઘાતાંકવાળી ઘાતોનો ભાગાકાર કરતી વખતે, આધારોનો ભાગાકાર કરો.',
    law5Example: '8² ÷ 2² = (8/2)² = 4² = 16',
    law6Title: 'નિયમ 6: ઘાતાંક શૂન્ય',
    law6Formula: 'a⁰ = 1 (જ્યાં a ≠ 0)',
    law6Description: 'કોઈ પણ બિન-શૂન્ય સંખ્યાની શૂન્ય ઘાત એક બરાબર હોય છે.',
    law6Example: '5⁰ = 1, 10⁰ = 1, 100⁰ = 1',
    lawSummary: 'સારાંશ',
    exampleLabel: 'ઉદાહરણ',
    lawSummaryText: 'આ છ નિયમો બધી ઘાતાંક ગણતરીઓનો પાયો બનાવે છે!',
    // Law 1 Steps
    law1_step1_text: '2³ × 2²',
    law1_step1_explanation: 'સમાન આધાર (2)',
    law1_step2_text: '(2×2×2) × (2×2)',
    law1_step2_explanation: 'ઘાતોનો વિસ્તાર કરો',
    law1_step3_text: '2×2×2×2×2',
    law1_step3_explanation: 'કુલ 2 ની ગણતરી કરો (5 વખત)',
    law1_step4_text: '2⁵ = 2³⁺²',
    law1_step4_explanation: 'ઘાતાંક ઉમેરો: 3 + 2 = 5',
    law1_step5_text: '= 32',
    law1_step5_explanation: 'અંતિમ જવાબ',
    // Law 2 Steps
    law2_step1_text: '5⁴ ÷ 5²',
    law2_step1_explanation: 'સમાન આધાર (5)',
    law2_step2_text: '(5×5×5×5) ÷ (5×5)',
    law2_step2_explanation: 'ઘાતોનો વિસ્તાર કરો',
    law2_step3_text: '5×5',
    law2_step3_explanation: 'સામાન્ય અવયવો રદ્દ કરો',
    law2_step4_text: '5² = 5⁴⁻²',
    law2_step4_explanation: 'ઘાતાંક બાદ કરો: 4 - 2 = 2',
    law2_step5_text: '= 25',
    law2_step5_explanation: 'અંતિમ જવાબ',
    // Law 3 Steps
    law3_step1_text: '(3²)³',
    law3_step1_explanation: 'ઘાતની ઘાત',
    law3_step2_text: '3² × 3² × 3²',
    law3_step2_explanation: '3² ને 3 વખત ગુણાકાર',
    law3_step3_text: '3²⁺²⁺²',
    law3_step3_explanation: 'ઘાતાંક ઉમેરો',
    law3_step4_text: '3⁶ = 3²×³',
    law3_step4_explanation: 'ઘાતાંક ગુણાકાર: 2 × 3 = 6',
    law3_step5_text: '= 729',
    law3_step5_explanation: 'અંતિમ જવાબ',
    // Law 4 Steps
    law4_step1_text: '2³ × 5³',
    law4_step1_explanation: 'સમાન ઘાતાંક (3)',
    law4_step2_text: '(2×2×2) × (5×5×5)',
    law4_step2_explanation: 'ઘાતોનો વિસ્તાર કરો',
    law4_step3_text: '(2×5) × (2×5) × (2×5)',
    law4_step3_explanation: 'અવયવોનું પુનઃગઠન',
    law4_step4_text: '6 × 6 × 6 = 6³',
    law4_step4_explanation: 'આધારો જોડો: (2×5)³',
    law4_step5_text: '= 1,000',
    law4_step5_explanation: 'અંતિમ જવાબ',
    // Law 5 Steps
    law5_step1_text: '8² ÷ 2²',
    law5_step1_explanation: 'સમાન ઘાતાંક (2)',
    law5_step2_text: '(8×8) ÷ (2×2)',
    law5_step2_explanation: 'ઘાતોનો વિસ્તાર કરો',
    law5_step3_text: '(8÷2) × (8÷2)',
    law5_step3_explanation: 'જોડીઓ વિભાજીત કરો',
    law5_step4_text: '4 × 4 = 4²',
    law5_step4_explanation: 'જોડો: (8÷2)²',
    law5_step5_text: '= 16',
    law5_step5_explanation: 'અંતિમ જવાબ',
    // Law 6 Steps
    law6_step1_text: '5³ ÷ 5³',
    law6_step1_explanation: 'સમાન આધાર અને ઘાતાંક',
    law6_step2_text: '5³⁻³',
    law6_step2_explanation: 'ઘાતાંક બાદ કરો',
    law6_step3_text: '5⁰',
    law6_step3_explanation: 'ઘાતાંક 0 થઈ જાય છે',
    law6_step4_text: '(5×5×5) ÷ (5×5×5) = 1',
    law6_step4_explanation: 'ભાગાકાર દ્વારા પણ 1 બરાબર',
    law6_step5_text: '∴ 5⁰ = 1',
    law6_step5_explanation: 'કોઈપણ સંખ્યા⁰ = 1',
    interactivePreview: 'ઇન્ટરેક્ટિવ પૂર્વાવલોકન',
    // Learn Page Controls
    showSteps: 'પગલાં બતાવો',
    reset: 'રીસેટ',
    playing: 'ચાલી રહ્યું છે...',
    previousLaw: 'પહેલાનો નિયમ',
    nextLaw: 'આગળનો નિયમ',
    quickNavigation: 'ઝડપી નેવિગેશન',
    lawCounter: 'નિયમ {current} ના {total}',
    clickToSeeSteps: 'પગલાં-દર-પગલાં ઉકેલ જોવા માટે "પગલાં બતાવો" પર ક્લિક કરો',
    // Real World Applications
    clickToSeeDetails: 'વિગતો જોવા માટે ક્લિક કરો',
    realWorldHeroTitle: 'વાસ્તવિક જીવનમાં ઘાતાંકના નિયમો',
    realWorldHeroDescription: 'જુઓ કે ઘાતાંકના નિયમો વિજ્ઞાન, ફાઇનાન્સ અને રોજિંદા ગણતરીઓમાં જટિલ સમસ્યાઓ હલ કરવા માટે કેવી રીતે ઉપયોગમાં લેવાય છે!',
    // Law 1 Applications
    law1RealWorldTitle: 'નિયમ 1: સમાન આધારવાળી ઘાતોનો ગુણાકાર',
    law1App1Title: 'સ્થાપત્યમાં ક્ષેત્રફળ સ્કેલિંગ',
    law1App1Desc: 'જો દીવાલનું ક્ષેત્રફળ બે દિશાઓમાં બમણું થઈ જાય છે (લંબાઈ અને ઊંચાઈ), તો ઘાતાંકો કુલ સપાટી વૃદ્ધિ બતાવવા માટે ઉમેરાય છે (દા.ત., m² × m³ = m⁵).',
    law1App2Title: 'ફાઇનાન્સમાં ચક્રવૃદ્ધિ વૃદ્ધિ',
    law1App2Desc: 'જ્યારે વ્યાજ વર્ષમાં કેટલીક વખત સંયોજિત થાય છે, ત્યારે ઘાતાંક પદો કુલ સંયોજન સમયગાળાનું પ્રતિનિધિત્વ કરવા માટે ઉમેરાય છે।',
    law1App3Title: 'ડેટા સ્ટોરેજ વિસ્તરણ',
    law1App3Desc: 'કમ્પ્યુટર સિસ્ટમોમાં, મેમરી બેંકો જોડવા (દરેક 2ⁿ ક્ષમતા) તેમના ઘાતાંકો ઉમેરે છે કુલ સરનામા યોગ્ય જગ્યા શોધવા માટે।',
    // Law 2 Applications
    law2RealWorldTitle: 'નિયમ 2: સમાન આધારવાળી ઘાતોનો ભાગાકાર',
    law2App1Title: 'ભૌતિકશાસ્ત્ર – પ્રતિ એકમ ક્ષેત્રફળ બળ (દબાણ)',
    law2App1Desc: 'ઘાતો દ્વારા પ્રતિનિધિત્વ ઊર્જા અથવા બળ મૂલ્યોને વિભાજીત કરતી વખતે, ઘાતાંકો બાદ કરે છે (દા.ત., N·m² / m² = N).',
    law2App2Title: 'ડેટા ટ્રાન્સફર દર',
    law2App2Desc: 'કમ્પ્યુટિંગમાં, સમય દ્વારા કુલ ડેટાને વિભાજીત કરવું (જેમ કે bytes/sec) એકમોના ઘાતાંકોને બાદ કરવાનો સમાવેશ કરે છે।',
    law2App3Title: 'મોડેલ સ્કેલિંગ ડાઉન',
    law2App3Desc: 'સ્થાપત્ય અથવા ડિઝાઇનમાં, મોડેલનાં કદને ઘટાડવું એ ઘાતોમાં સ્કેલ પરિબળોને બાદ કરવાનો સમાવેશ કરે છે (દા.ત., 10⁶ ÷ 10³ = 10³).',
    // Law 3 Applications
    law3RealWorldTitle: 'નિયમ 3: ઘાતની ઘાત',
    law3App1Title: 'જનીનીશાસ્ત્ર – કોષ વિભાજન',
    law3App1Desc: 'દરેક કોષ ઘણી વખત ઘાતાંકીય રીતે વિભાજિત થાય છે; કુલ વિભાજનો (2^m)^n = 2^(m×n) નો અનુસરણ કરે છે।',
    law3App2Title: 'કમ્પ્યુટર વિજ્ઞાન – નેસ્ટેડ લૂપ્સ',
    law3App2Desc: 'નેસ્ટેડ પુનરાવૃત્તિઓ સાથે એલ્ગોરિધમ જટિલતા ઘાતાંક સ્વરૂપમાં ગુણાત્મક રીતે વધે છે।',
    law3App3Title: 'ધ્વનિ ઇજનેરી',
    law3App3Desc: 'ડેસિબલ સ્કેલિંગ ઘાતાંકીય શક્તિ નિયમોનો ઉપયોગ કરે છે; તે જ લાભને ઘણી વખત લાગુ કરવું એ ઘાતાંકોનો ગુણાકાર કરે છે।',
    // Law 4 Applications
    law4RealWorldTitle: 'નિયમ 4: સમાન ઘાતાંકવાળી ઘાતોનો ગુણાકાર',
    law4App1Title: 'ભૌતિકશાસ્ત્ર – ઘનફળ ગણતરી',
    law4App1Desc: 'લંબચોરસ બોક્સ માટે: (લંબાઈ × પહોળાઈ × ઊંચાઈ)³ = (lwh)³ — બધા બાજુઓમાં સમાન ઘાતાંક લાગુ કરવામાં આવ્યો।',
    law4App2Title: 'અર્થશાસ્ત્ર – સંયુક્ત વૃદ્ધિ પરિબળો',
    law4App2Desc: 'જ્યારે બે અર્થવ્યવસ્થાઓ સમાન દરે વધે છે, ત્યારે તેમને ગુણાકાર કરવાનો સમાન ઘાતાંક (વૃદ્ધિ દર) નો ઉપયોગ કરે છે।',
    law4App3Title: 'કમ્પ્યુટર ગ્રાફિક્સ',
    law4App3Desc: 'એક છબીને x અને y બંને પરિમાણોમાં સમાન રીતે સ્કેલ કરવું એ ચલોમાં સમાન શક્તિનો ઉપયોગ કરે છે।',
    // Law 5 Applications
    law5RealWorldTitle: 'નિયમ 5: સમાન ઘાતાંકવાળી ઘાતોનો ભાગાકાર',
    law5App1Title: 'ઘનતા અથવા સાંદ્રતા',
    law5App1Desc: 'ઘનતા = દળ/ઘનફળ; બંને સમાન ઘાતાંકો સાથે પ્રમાણસર રીતે વધી શકે છે (દા.ત., સ્કેલિંગ મોડેલો)।',
    law5App2Title: 'અર્થવ્યવસ્થા ગુણોત્તર',
    law5App2Desc: 'સમાન દરે વધતા દેશોની GDPs ની તુલના કરવી (શક્તિ) ગુણોત્તર આપે છે જે ઘાતાંક સમાનતા જાળવી રાખે છે।',
    law5App3Title: 'ભૌતિકશાસ્ત્ર – પ્રતિરોધ અને વાહકતા',
    law5App3Desc: 'જ્યારે પ્રતિરોધ અને વાહકતા બંને તાપમાન સાથે ઘાતાંકીય રીતે બદલાય છે, ત્યારે તેમનો ગુણોત્તર સમાન ઘાતાંકોનો ઉપયોગ કરીને સરળ બને છે।',
    // Law 6 Applications
    law6RealWorldTitle: 'નિયમ 6: ઘાતાંક શૂન્ય સાથેની સંખ્યાઓ',
    law6App1Title: 'કમ્પ્યુટર વિજ્ઞાન – એલ્ગોરિધમોમાં આધાર કેસ',
    law6App1Desc: 'જ્યારે પુનરાવૃત્તિ શૂન્ય શક્તિ સુધી પહોંચે છે, ત્યારે પરિણામ 1 છે → ફેક્ટોરિયલ્સ, શક્તિઓ વગેરેમાં ઉપયોગમાં લેવાય છે।',
    law6App2Title: 'ભૌતિકશાસ્ત્ર – સ્થિર અવસ્થા સ્થિતિઓ',
    law6App2Desc: 'જ્યારે એક ચલ બદલવાનું બંધ કરે છે (શક્તિ તફાવત = 0), ત્યારે સિસ્ટમ એકતા (1× સ્કેલ) સુધી પહોંચે છે।',
    law6App3Title: 'ગણિત – પ્રારંભિકકરણ',
    law6App3Desc: 'શૂન્ય સુધી ઉઠાવેલી કોઈ પણ બિન-શૂન્ય માત્રા મોડેલિંગમાં એક "પ્રારંભિક બિંદુ" અથવા બેસલાઇન મૂલ્યનું પ્રતિનિધિત્વ કરે છે।',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 પરિચય',
    tabExponents: '11.2 ઘાતાંક',
    massOfEarth: 'પૃથ્વીનું દળ',
    massOfUranus: 'યુરેનસનું દળ',
    distancesInSpace: 'અવકાશમાં અંતર',
    hugeNumbersReadable: 'ઘાતાંકો સાથે મોટી સંખ્યાઓ વાંચવા યોગ્ય બને છે',
    powerOf3: '5 ની ઘાત 3',
    powerOf4: '3 ની ઘાત 4',
    powerOf6: '2 ની ઘાત 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 ઘાતાંક — મૂળભૂત ખ્યાલો',
    visualExponentialForm: 'વિઝ્યુઅલ ઘાતાંકીય સ્વરૂપ',
    base: 'આધાર',
    baseDescription: 'જે સંખ્યાનો ગુણાકાર થઈ રહ્યો છે',
    exponent: 'ઘાતાંક',
    exponentDescription: 'કેટલી વાર ગુણાકાર કરવો',
    power: 'ઘાત',
    powerDescription: 'પરિણામ',
    specialName: 'ખાસ નામ',
    squared: 'વર્ગ',
    tenSquared: '"10 નો વર્ગ"',
    cubed: 'ઘન',
    tenCubed: '"10 નો ઘન"',
    primeFactorization: 'અવિભાજ્ય અવયવીકરણ',
    primeFactorizationDesc: 'ઘાતાંકનો ઉપયોગ કરીને અવયવોને સંક્ષિપ્તમાં વ્યક્ત કરો',
    negativeBases: 'નકારાત્મક આધાર',
    generalNotation: 'સામાન્ય સંકેતલિપિ',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'મહત્વપૂર્ણ મુદ્દાઓ',
    pointAnyBase: 'કોઈપણ આધારનો ઉપયોગ કરી શકાય છે — ફક્ત 10 જ નહીં',
    pointExponentialForm: 'ઘાતાંકીય સ્વરૂપ મોટી સંખ્યાઓ સાથે કામ કરવાનું સરળ બનાવે છે',
    pointPrimeFactorization: 'અવિભાજ્ય અવયવીકરણ ઘાતાંક સાથે સંક્ષિપ્ત હોય છે',
    
    // Home Page
    masterSimpleEquations: 'સરળ સમીકરણોમાં નિપુણતા મેળવો',
    masterClass7Mathematics: 'એનસીઇઆરટી અભ્યાસક્રમના આધારે ઇન્ટરેક્ટિવ શીખવા, પ્રેક્ટિસ કસરતો અને આકર્ષક રમતો સાથે ધોરણ 7 ગણિતમાં નિપુણતા મેળવો',
    startLearning: 'શીખવાનું શરૂ કરો',
    whatYoullLearn: 'તમે શું શીખશો',
    comprehensiveTools: 'સરળ સમીકરણોને શીખવાનું આકર્ષક અને અસરકારક બનાવવા માટે ડિઝાઇન કરેલા વ્યાપક સાધનો',
    introductionDesc: 'ઇન્ટરેક્ટિવ ઉદાહરણો સાથે સરળ સમીકરણોની મૂળભૂત વાતો શીખો',
    learnDesc: 'વિઝ્યુઅલ સહાયતા સાથે પગલું-દર-પગલું સ્પષ્ટતા',
    practiceDesc: 'કસરતો હલ કરો અને તમારા ઉકેલો તપાસો',
    realWorldDesc: 'જુઓ કે સમીકરણો રોજિંદા જીવનમાં કેવી રીતે લાગુ પડે છે',
    practiceProblems: 'પ્રેક્ટિસ સમસ્યાઓ',
    interactiveExamples: 'ઇન્ટરેક્ટિવ ઉદાહરણો',
    readyToMaster: 'સરળ સમીકરણોમાં નિપુણતા મેળવવા માટે તૈયાર છો?',
    joinThousands: 'હજારો વિદ્યાર્થીઓ અને શિક્ષકોમાં જોડાઓ જે ગણિતને આકર્ષક અને સુલભ બનાવી રહ્યા છે.',
    startYourJourney: 'તમારી યાત્રા શરૂ કરો',
    
    // Common
    correct: 'સાચું!',
    incorrect: 'ફરી કોશિશ કરો!',
    learning: 'શીખવું',
    practice: 'પ્રેક્ટિસ',
    assessment: 'મૂલ્યાંકન',
    selectEquation: 'સમીકરણ પસંદ કરો:',
    yourAnswer: 'તમારો જવાબ:',
    submit: 'સબમિટ',
    hint: 'સંકેત',
    progress: 'પ્રગતિ:',
    accuracy: 'ચોકસાઈ',
    avgTime: 'સરેરાશ સમય',
    correctAnswers: 'સાચું',
    incorrectAnswers: 'ખોટું',
    totalExercises: 'કુલ',
    excellent: 'ઉત્તમ!',
    goodJob: 'સારું કામ!',
    keepTrying: 'કોશિશ કરતા રહો!',
    showSolution: 'ઉકેલ બતાવો',
    hideSolution: 'ઉકેલ છુપાવો',
    reset: 'રીસેટ',
    stepByStepSolution: 'પગલું-દર-પગલું ઉકેલ:',
    nextStep: 'આગળનું પગલું',
    complete: 'પૂર્ણ',
    
    // Real World
    realWorldApps: 'વાસ્તવિક વિશ્વના ઉપયોગો',
    selectCategory: 'શ્રેણી પસંદ કરો:',
    difficulty: 'મુશ્કેલી:',
    beginner: 'શરૂઆત',
    intermediate: 'મધ્યમ',
    advanced: 'અદ્યતન',
    equation: 'સમીકરણ:',
    solution: 'ઉકેલ:',
    context: 'સંદર્ભ:',
    shopping: 'ખરીદી',
    cooking: 'રસોઈ',
    construction: 'બાંધકામ',
    sports: 'રમત',
    finance: 'વિત્ત',
    science: 'વિજ્ઞાન',
    
    // Learn Section
    linearEquations: 'રેખીય સમીકરણો',
    linearEquationsDesc: 'રેખીય સમીકરણો એવા સમીકરણો છે જ્યાં ચલની સર્વોચ્ચ ઘાત 1 છે. તેમને જોડાણ, બાદબાકી, ગુણાકાર અને ભાગાકાર જેવી મૂળભૂત બીજગણિતીય ક્રિયાઓનો ઉપયોગ કરીને હલ કરી શકાય છે.',
    solvingByAddition: 'જોડાણ દ્વારા હલ કરવું',
    solvingByAdditionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં બાદબાકી હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓમાં સમાન સંખ્યા ઉમેરીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingBySubtraction: 'બાદબાકી દ્વારા હલ કરવું',
    solvingBySubtractionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં જોડાણ હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓમાંથી સમાન સંખ્યા બાદ કરીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingByMultiplication: 'ગુણાકાર દ્વારા હલ કરવું',
    solvingByMultiplicationDesc: 'જ્યારે આપણી પાસે સમીકરણમાં ભાગાકાર હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓને સમાન સંખ્યા વડે ગુણીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingByDivision: 'ભાગાકાર દ્વારા હલ કરવું',
    solvingByDivisionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં ગુણાકાર હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓને સમાન સંખ્યા વડે ભાગીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    originalEquation: 'મૂળ સમીકરણ',
    originalEquationWithSubtraction: 'બાદબાકી સાથે મૂળ સમીકરણ',
    originalEquationWithAddition: 'જોડાણ સાથે મૂળ સમીકરણ',
    originalEquationWithDivision: 'ભાગાકાર સાથે મૂળ સમીકરણ',
    originalEquationWithMultiplication: 'ગુણાકાર સાથે મૂળ સમીકરણ',
    subtractFromBothSides: 'બંને બાજુઓમાંથી 5 બાદ કરો',
    addToBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓમાં 3 ઉમેરો',
    subtractFromBothSidesToIsolate: 'x ને અલગ કરવા માટે બંને બાજુઓમાંથી 4 બાદ કરો',
    multiplyBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓને 3 વડે ગુણો',
    divideBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓને 3 વડે ભાગો',
    simplifyToFindAnswer: 'જવાબ શોધવા માટે સરળ બનાવો',
    simplifyStep: 'સરળ બનાવો: 5 - 5 = 0 અને 12 - 5 = 7',
    verifySolution: 'x = 7 મૂકીને ઉકેલ ચકાસો',
    simplifyAdditionStep: 'સરળ બનાવો: -3 + 3 = 0 અને 8 + 3 = 11',
    verifyAdditionSolution: 'x = 11 મૂકીને ઉકેલ ચકાસો',
    simplifySubtractionStep: 'સરળ બનાવો: 4 - 4 = 0 અને 7 - 4 = 3',
    verifySubtractionSolution: 'x = 3 મૂકીને ઉકેલ ચકાસો',
    simplifyMultiplicationStep: 'સરળ બનાવો: 3/3 = 1 અને 4 × 3 = 12',
    verifyMultiplicationSolution: 'x = 12 મૂકીને ઉકેલ ચકાસો',
    simplifyDivisionStep: 'સરળ બનાવો: 3x ÷ 3 = x અને 15 ÷ 3 = 5',
    verifyDivisionSolution: 'x = 5 મૂકીને ઉકેલ ચકાસો',
    linearEquationExample: 'રેખીય સમીકરણ ઉદાહરણ',
    additionMethodExample: 'જોડાણ પદ્ધતિ ઉદાહરણ',
    subtractionMethodExample: 'બાદબાકી પદ્ધતિ ઉદાહરણ',
    multiplicationMethodExample: 'ગુણાકાર પદ્ધતિ ઉદાહરણ',
    divisionMethodExample: 'ભાગાકાર પદ્ધતિ ઉદાહરણ',
    solving: 'હલ કરવું:',
    play: 'ચલાવો',
    pause: 'રોકો',
    previous: 'પાછલું',
    next: 'આગળનું',
    
    // Practice Mode
    practiceMode: 'પ્રેક્ટિસ મોડ',
    question: 'પ્રશ્ન',
    skippedQuestions: 'છોડેલા પ્રશ્નો',
    notAttempted: 'પ્રયાસ નથી કર્યો',
    totalQuestions: 'કુલ પ્રશ્નો',
    finalGrade: 'અંતિમ ગ્રેડ',
    accuracyRate: 'ચોકસાઈ દર',
    avgTimePerQuestion: 'પ્રતિ પ્રશ્ન સરેરાશ સમય',
    questionByQuestionReview: 'પ્રશ્ન દર પ્રશ્ન સમીક્ષા',
    startNewSession: 'નવો સત્ર શરૂ કરો',
    loadingQuestions: 'પ્રશ્નો લોડ થઈ રહ્યા છે...',
    showAnswer: 'જવાબ બતાવો',
    hideAnswer: 'જવાબ છુપાવો',
    tryAgain: 'ફરી કોશિશ કરો',
    skip: 'છોડો',
    skipped: 'છોડાયેલું',
    sessionComplete: 'સત્ર પૂર્ણ!',
    sessionSummary: 'અહીં તમારો સંપૂર્ણ સત્ર સારાંશ છે',
    correctAnswer: 'સાચો જવાબ',
    check: 'તપાસ',
    notAttempt: 'પ્રયાસ ન કરો',
    
    // Practice Questions - Exponents
    q1_prompt: 'નિયમ 1 નો ઉપયોગ કરો: 2³ × 2² ની ગણતરી કરો',
    q1_explanation: 'નિયમ 1: aᵐ × aⁿ = aᵐ⁺ⁿ. તેથી 2³ × 2² = 2³⁺² = 2⁵ = 32',
    q2_prompt: 'નિયમ 2 નો ઉપયોગ કરો: 5⁴ ÷ 5² ની ગણતરી કરો',
    q2_explanation: 'નિયમ 2: aᵐ ÷ aⁿ = aᵐ⁻ⁿ. તેથી 5⁴ ÷ 5² = 5⁴⁻² = 5² = 25',
    q3_prompt: 'નિયમ 3 નો ઉપયોગ કરો: (3²)³ ની ગણતરી કરો',
    q3_explanation: 'નિયમ 3: (aᵐ)ⁿ = aᵐⁿ. તેથી (3²)³ = 3²×³ = 3⁶ = 729',
    q4_prompt: 'નિયમ 4 નો ઉપયોગ કરો: 2³ × 5³ ની ગણતરી કરો',
    q4_explanation: 'નિયમ 4: aᵐ × bᵐ = (ab)ᵐ. તેથી 2³ × 5³ = (2 × 5)³ = 10³ = 1,000',
    q5_prompt: 'નિયમ 5 નો ઉપયોગ કરો: 8² ÷ 2² ની ગણતરી કરો',
    q5_explanation: 'નિયમ 5: aᵐ ÷ bᵐ = (a/b)ᵐ. તેથી 8² ÷ 2² = (8/2)² = 4² = 16',
    q6_prompt: 'નિયમ 6 નો ઉપયોગ કરો: 7⁰ ની ગણતરી કરો',
    q6_explanation: 'નિયમ 6: a⁰ = 1 (કોઈ પણ બિન-શૂન્ય a માટે). તેથી 7⁰ = 1',
    
    // Practice Questions
    practice_q1: 'હલ કરો: x + 7 = 15',
    practice_q2: 'હલ કરો: x + 4 = 12',
    practice_q3: 'હલ કરો: x + 3 = 21',
    practice_q4: 'હલ કરો: x + 2 = 8',
    practice_q5: 'હલ કરો: x + 3 = 11',
    practice_q6: 'હલ કરો: x + 5 = 9',
    practice_q7: 'હલ કરો: x + 6 = 18',
    practice_q8: 'હલ કરો: x + 2 = 7',
    practice_q9: 'હલ કરો: x + 8 = 33',
    practice_q10: 'હલ કરો: x + 7 = 13',
    practice_q11: 'હલ કરો: x + 3 = 8',
    practice_q12: 'હલ કરો: x + 12 = 30',
    
    // Exponents
    exp_intro_title: 'ઘાતાંકની જરૂર કેમ છે?',
    exp_intro_text: 'ખૂબ મોટી સંખ્યાઓ સાથે કામ કરવું મુશ્કેલ છે:',
    exp_problem_1: 'વાંચવું મુશ્કેલ: 5,970,000,000,000,000,000,000,000 કિલો',
    exp_problem_2: 'સમજવું મુશ્કેલ: આ સંખ્યા કેટલી મોટી છે?',
    exp_problem_3: 'સરખામણી કરવી મુશ્કેલ: કયું મોટું છે - પૃથ્વી કે યુરેનસ?',
    exp_intro_solution: 'ઉકેલ: સંખ્યાઓને ટૂંકા, સરળ સ્વરૂપમાં લખવા માટે ઘાતાંકનો ઉપયોગ કરો!',
    exp_example_title: 'વાસ્તવિક વિશ્વનું ઉદાહરણ',
    exp_example_before: 'પૃથ્વીનું વજન = 5,970,000,000,000,000,000,000,000 કિલો',
    exp_example_after: 'પૃથ્વીનું વજન = 5.97 × 10²⁴ કિલો',
    exp_example_benefit: 'વાંચવા અને સરખામણી કરવામાં ખૂબ સરળ!',
    exp_before: 'પહેલાં',
    exp_after: 'પછી',
    exp_what_are_title: 'ઘાતાંક શું છે?',
    exp_what_are_text: 'ઘાતાંક આપણને પુનરાવર્તિત ગુણાકારને સંક્ષિપ્ત રીતે લખવા દે છે.',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'પુનરાવર્તિત ગુણાકાર',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'ઘાતાંક સ્વરૂપ',
    exp_main_example: 'મુખ્ય ઉદાહરણ',
    exp_term_base: 'આધાર',
    exp_term_base_def: 'ગુણાકારમાં લેવાતી સંખ્યા',
    exp_term_base_ex: '10⁴ માં, આધાર = 10',
    exp_term_exp: 'ઘાતાંક',
    exp_term_exp_def: 'આધારને કેટલી વાર ગુણાકાર કરવો છે',
    exp_term_exp_ex: '10⁴ માં, ઘાતાંક = 4',
    exp_term_power: 'ઘાત',
    exp_term_power_def: 'સંપૂર્ણ અભિવ્યક્તિ',
    exp_term_power_ex: '10⁴ ને "10 ની ઘાત 4" તરીકે વાંચવામાં આવે છે',
    exp_key_terms: 'યાદ રાખવા યોગ્ય મુખ્ય શબ્દો:',
    exp_examples_title: 'ઉદાહરણો સાથે કામ',
    exp_conversion_text: 'જુઓ કે સંખ્યાઓને ઘાતાંક સ્વરૂપમાં કેવી રીતે બદલવામાં આવે છે:',
    exp_example: 'ઉદાહરણ',
    exp_step1: 'પગલું 1: ગુણાકાર તરીકે લખો',
    exp_step2: 'પગલું 2: ઘાતાંક સ્વરૂપમાં લખો',
    exp_base: 'આધાર',
    exp_exponent: 'ઘાતાંક',
    exp_read_as: 'વાંચો',
    exp_ex1_reading: '10 ની ઘાત 3',
    exp_ex2_reading: '3 ની ઘાત 4',
    exp_ex3_reading: '5 ઘન',
    exp_ex4_reading: '2 ની ઘાત 5',
    exp_special_title: 'વિશેષ નામો',
    exp_special_intro: 'કેટલાક ઘાતાંકોનાં વિશેષ નામો છે જેનો તમે ઘણી વાર ઉપયોગ કરશો:',
    exp_squared: 'વર્ગ',
    exp_squared_read: 'વર્ગ',
    exp_cubed: 'ઘન',
    exp_cubed_read: 'ઘન',
    exp_special_note: 'આ વિશેષ નામો ભૂમિતિમાંથી આવે છે - વર્ગ ચોરસના ક્ષેત્રફળમાંથી, ઘન ઘનના ઘનફળમાંથી!',
    exp_power_of: 'ઘાત',
    exp_fun_fact: 'રસપ્રદ તથ્ય',
    exp_practice_title: 'ઇન્ટરેક્ટિવ પ્રેક્ટિસ',
    exp_interactive_intro: 'જાતે અજમાવો! ઘાતાંક કેવી રીતે કામ કરે છે તે જોવા માટે આધાર અને ઘાતાંક બદલો:',
    exp_expanded: 'વિસ્તૃત સ્વરૂપ',
    exp_exponential_form: 'ઘાતાંક સ્વરૂપ',
    exp_result: 'પરિણામ',
    exp_reading_title: 'વાંચન',
    exp_raised_to: 'ની ઘાત',
    exp_or: 'અથવા',
    of: 'નું',
    example: 'ઉદાહરણ',
    formula: 'સૂત્ર',
    explanation: 'સ્પષ્ટતા'
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'hi' | 'gu'>(() => {
    // Load language from localStorage on initialization
    const savedLanguage = localStorage.getItem('selectedLanguage') as 'en' | 'hi' | 'gu' | null;
    return savedLanguage || 'en';
  });
  const [isTransitioning, setIsTransitioning] = useState(false);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const localizeDigitsInText = (text: string): string => {
    // For now, just return the text as-is
    // In a real implementation, this would convert digits to the appropriate script
    return text;
  };

  const formatNumber = (num: number): string => {
    return num.toString();
  };

  const handleSetLanguage = (lang: 'en' | 'hi' | 'gu') => {
    setIsTransitioning(true);
    // Save language to localStorage
    localStorage.setItem('selectedLanguage', lang);
    setTimeout(() => {
      setLanguage(lang);
      setIsTransitioning(false);
    }, 100); // Further reduced for smoother switching
  };

  const value: LanguageContextType = {
    language,
    setLanguage: handleSetLanguage,
    t,
    isTransitioning,
    localizeDigitsInText,
    formatNumber
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
