import { createContext, useContext, useMemo, useState, ReactNode } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'gu';

type LanguageContextValue = {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  isTransitioning: boolean;
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    headerTitle: 'Mode Tool',
    learn: 'Learn',
    practice: 'Practice',
    realWorld: 'Real World',
    data: 'Data',
    frequency: 'Frequency',
    modeLabel: 'Mode',
    visual: 'Visual',
    step1Title: 'Understanding Mode 💡',
    step1Desc: 'Mode is the value that occurs most often in a dataset.',
    step1Context: 'Small dataset',
    step2Title: 'Step-by-step counting 🧮',
    step2Desc: 'Count each value and pick those with the highest frequency.',
    step3Title: 'Large data (table) 📋',
    step3Desc: 'Use a table to find the highest frequency quickly.',
    step3Context: 'Margins 1..6',
    step4Title: 'Weekly shirt sizes 👕',
    step4Desc: 'Most sold size in a week is the mode.',
    step4Context: 'Sizes 90,95,100,105,110',
    step5Title: 'More than one mode 🔁',
    step5Desc: 'A dataset can be multi-modal if several values tie for top frequency.',
    step5Context: 'Multi-modal example',
    ex1Title: 'Small set mode',
    ex1Desc: 'Find the mode of 1,1,2,2,2,3,3,4,4',
    ex1Question: 'Mode = ?',
    ex2Title: 'Shirt sizes',
    ex2Desc: 'Sizes 90..110 cm with counts 8,22,32,37,6.',
    ex2Question: 'Which size is the mode?',
    ex3Title: 'Multiple modes',
    ex3Desc: 'Find all modes of 2,2,5,5,6,3,4,5,2',
    ex3Question: 'Modes (comma separated):',
    ex4Title: 'Test scores',
    ex4Desc: 'Find the most common test score in the class.',
    ex4Question: 'What is the mode of the test scores?',
    ex5Title: 'Movie ratings',
    ex5Desc: 'Identify the most frequently given rating.',
    ex5Question: 'Mode rating = ?',
    ex6Title: 'Daily temperatures',
    ex6Desc: 'Find the most recurring temperature value.',
    ex6Question: 'What is the mode temperature?',
    rw1Title: 'Most popular shirt size',
    rw1Desc: 'Stock to match the most demanded size (mode).',
    rw1Context: 'Sizes 90,95,100,105,110 (cm)',
    rw2Title: 'Door height caution',
    rw2Desc: 'Mode may not suit safety/clearance decisions.',
    rw2Context: 'Kids and adults using a door',
    rw3Title: 'Canteen chapatis',
    rw3Desc: 'Mode gives the common need; totals require sums/means.',
    rw3Context: 'Chapatis per person',
    rw4Title: 'Shoe sizes in a store',
    rw4Desc: 'The most sold shoe size helps retailers stock inventory efficiently.',
    rw4Context: 'Shoe sizes 6, 7, 8, 9, 10',
    rw5Title: 'Favorite ice cream flavor',
    rw5Desc: 'Survey results show the most popular flavor choice using mode.',
    rw5Context: 'Flavors: Vanilla, Chocolate, Strawberry, Mango',
    rw6Title: 'Bus timings usage',
    rw6Desc: 'The most frequently used bus timing is the mode, useful for scheduling.',
    rw6Context: 'Peak hours: 7AM, 8AM, 9AM, 6PM',
    question: 'Question',
    previous: 'Previous',
    next: 'Next',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset',
    submitAnswers: 'Submit answers',
    score: 'Score',
    attempts: 'Attempts',
    showSolution: 'Show solution',
    hideSolution: 'Hide solution',
    solutionSteps: 'Solution steps:',
    showHint: 'Show hint',
    hint: 'Hint',
    enterYourAnswer: 'Enter your answer',
    stepCountEachValue: 'Count each value.',
    stepPickHighestFrequency: 'Pick value with highest frequency (3).',
    stepFindMaxCount: 'Find max count (37).',
    stepMapToSize: 'Map to size',
    stepMultipleModesCounts: '2 occurs 3 times, 5 occurs 3 times.',
    stepBothAreModes: 'Both are modes',
    hintCountFrequencies: 'Count frequencies',
    hintPickLargestCount: 'Pick the largest count',
    definitionLabel: 'Definition',
    bulletPopular: 'Useful for finding the most popular choice',
    bulletMultipleModes: 'There can be more than one mode (bi/multi‑modal)',
    modeDefText: 'Mode is the value that occurs most frequently in a dataset.',
    formulaLabel: 'Formula',
    whereFrequency: 'where f(x) is the frequency (count) of value x',
    exampleUsingFormula: 'Example using the formula',
    givenData: 'Given data',
    frequencyFx: 'Frequency f(x)',
    argMaxResult: 'arg max',
    becauseHighestFreq: 'because it has the highest frequency',
    thereforeMo: 'Therefore, Mo =',
    tryThisQuestion: 'Try this question',
    findModeOfData: 'Find the mode of the data',
    valueLabel: 'Value',
    frequencyLabel: 'Frequency',
    currentExample: 'Current example',
    modesLabelUI: 'Mode(s):'
  },
  hi: {
    headerTitle: 'मोड टूल',
    learn: 'सीखें',
    practice: 'अभ्यास',
    realWorld: 'वास्तविक जीवन',
    data: 'डेटा',
    frequency: 'आवृत्ति',
    modeLabel: 'मोड',
    visual: 'दृश्य',
    step1Title: 'मोड को समझें 💡',
    step1Desc: 'मोड वह मान है जो डेटा में सबसे अधिक बार आता है।',
    step1Context: 'छोटा डेटा सेट',
    step2Title: 'कदम-दर-कदम गिनती 🧮',
    step2Desc: 'हर मान की गिनती करें और सबसे अधिक आवृत्ति वाले चुनें।',
    step3Title: 'बड़ा डेटा (तालिका) 📋',
    step3Desc: 'सबसे अधिक आवृत्ति जल्दी खोजने के लिए तालिका उपयोग करें।',
    step3Context: 'अंतर 1..6',
    step4Title: 'साप्ताहिक शर्ट साइज 👕',
    step4Desc: 'एक सप्ताह में सबसे ज्यादा बिकने वाला साइज ही मोड है।',
    step4Context: 'साइज 90,95,100,105,110',
    step5Title: 'एक से अधिक मोड 🔁',
    step5Desc: 'यदि कई मानों की सर्वोच्च आवृत्ति समान है, तो डेटा बहु-मोडल है।',
    step5Context: 'मल्टी-मोडल उदाहरण',
    ex1Title: 'छोटा सेट मोड',
    ex1Desc: '1,1,2,2,2,3,3,4,4 का मोड निकालें',
    ex1Question: 'मोड = ?',
    ex2Title: 'शर्ट साइज',
    ex2Desc: 'साइज 90..110 सेमी, गणना 8,22,32,37,6',
    ex2Question: 'मोड कौन सा साइज है?',
    ex3Title: 'एकाधिक मोड',
    ex3Desc: '2,2,5,5,6,3,4,5,2 के सभी मोड बताएं',
    ex3Question: 'मोड (कॉमा से अलग):',
    ex4Title: 'परीक्षा अंक',
    ex4Desc: 'कक्षा में सबसे आम परीक्षा अंक खोजें।',
    ex4Question: 'परीक्षा अंकों का मोड क्या है?',
    ex5Title: 'फिल्म रेटिंग',
    ex5Desc: 'सबसे अधिक बार दी गई रेटिंग बताएं।',
    ex5Question: 'मोड रेटिंग = ?',
    ex6Title: 'दैनिक तापमान',
    ex6Desc: 'सबसे बार आने वाला तापमान मान खोजें।',
    ex6Question: 'मोड तापमान क्या है?',
    rw1Title: 'सबसे लोकप्रिय शर्ट साइज',
    rw1Desc: 'मांग के अनुसार साइज स्टॉक करें (मोड)।',
    rw1Context: 'साइज 90,95,100,105,110 (सेमी)',
    rw2Title: 'दरवाज़े की ऊँचाई सावधानी',
    rw2Desc: 'सुरक्षा/क्लीयरेंस के फैसले के लिए मोड उपयुक्त नहीं हो सकता।',
    rw2Context: 'बच्चे और वयस्क दरवाज़ा उपयोग कर रहे हैं',
    rw3Title: 'कैंटीन में चपातियाँ',
    rw3Desc: 'मोड सामान्य आवश्यकता देता है; कुल के लिए औसत/योग चाहिए।',
    rw3Context: 'प्रति व्यक्ति चपातियाँ',
    rw4Title: 'स्टोर में जूते का साइज',
    rw4Desc: 'सबसे अधिक बिकने वाला जूता साइज स्टॉक करने में मदद करता है।',
    rw4Context: 'जूते का साइज 6, 7, 8, 9, 10',
    rw5Title: 'पसंदीदा आइसक्रीम फ्लेवर',
    rw5Desc: 'सर्वे के परिणाम मोड का उपयोग करके सबसे लोकप्रिय स्वाद दिखाते हैं।',
    rw5Context: 'फ्लेवर: वनीला, चॉकलेट, स्ट्रॉबेरी, आम',
    rw6Title: 'बस का समय उपयोग',
    rw6Desc: 'सबसे अधिक उपयोग किया जाने वाला बस समय मोड है, शेड्यूलिंग के लिए उपयोगी।',
    rw6Context: 'व्यस्त समय: 7AM, 8AM, 9AM, 6PM',
    question: 'प्रश्न',
    previous: 'पिछला',
    next: 'अगला',
    play: 'चलाएँ',
    pause: 'रोकें',
    reset: 'रीसेट',
    submitAnswers: 'उत्तर जमा करें',
    score: 'स्कोर',
    attempts: 'प्रयास',
    showSolution: 'समाधान दिखाएँ',
    hideSolution: 'समाधान छिपाएँ',
    solutionSteps: 'समाधान के चरण:',
    showHint: 'संकेत दिखाएँ',
    hint: 'संकेत',
    enterYourAnswer: 'अपना उत्तर लिखें',
    stepCountEachValue: 'हर मान की गिनती करें।',
    stepPickHighestFrequency: 'सबसे अधिक आवृत्ति (3) वाला मान चुनें।',
    stepFindMaxCount: 'सबसे बड़ा काउंट (37) ढूँढें।',
    stepMapToSize: 'उसे साइज से जोड़ें',
    stepMultipleModesCounts: '2 तीन बार आता है, 5 तीन बार आता है।',
    stepBothAreModes: 'दोनों मोड हैं',
    hintCountFrequencies: 'आवृत्तियाँ गिनें',
    hintPickLargestCount: 'सबसे बड़ा काउंट चुनें',
    definitionLabel: 'परिभाषा',
    bulletPopular: 'सबसे लोकप्रिय विकल्प खोजने में उपयोगी',
    bulletMultipleModes: 'एक से अधिक मोड (द्वि/बहु‑मोडल) हो सकते हैं',
    modeDefText: 'मोड वह मान है जो डेटा में सबसे अधिक बार आता है।',
    formulaLabel: 'सूत्र',
    whereFrequency: 'जहाँ f(x) मान x की आवृत्ति (गिनती) है',
    exampleUsingFormula: 'सूत्र का उपयोग करते हुए उदाहरण',
    givenData: 'दिया गया डेटा',
    frequencyFx: 'आवृत्ति f(x)',
    argMaxResult: 'arg max',
    becauseHighestFreq: 'क्योंकि इसकी सबसे अधिक आवृत्ति है',
    thereforeMo: 'इसलिए, Mo =',
    tryThisQuestion: 'यह प्रश्न आज़माएँ',
    findModeOfData: 'डेटा का मोड ज्ञात करें',
    valueLabel: 'मान',
    frequencyLabel: 'आवृत्ति',
    currentExample: 'वर्तमान उदाहरण',
    modesLabelUI: 'मोड(स):'
  },
  gu: {
    headerTitle: 'મોડ સાધન',
    learn: 'શીખો',
    practice: 'અભ્યાસ',
    realWorld: 'વાસ્તવિક દુનિયા',
    data: 'ડેટા',
    frequency: 'આવર્તન',
    modeLabel: 'મોડ',
    visual: 'દ્રશ્ય',
    step1Title: 'મોડ સમજવું 💡',
    step1Desc: 'મોડ તે મૂલ્ય છે જે સૌથી વધુ વાર આવે છે.',
    step1Context: 'નાનું ડેટાસેટ',
    step2Title: 'પગલા-દર-પગલા ગણતરી 🧮',
    step2Desc: 'દરેક મૂલ્યની ગણતરી કરો અને સર્વોચ્ચ આવર્તનવાળું પસંદ કરો.',
    step3Title: 'મોટો ડેટા (ટેબલ) 📋',
    step3Desc: 'ઝડપથી સર્વોચ્ચ આવર્તન શોધવા ટેબલનો ઉપયોગ કરો.',
    step3Context: 'માર્જિન 1..6',
    step4Title: 'સાપ્તાહિક શર્ટ સાઇઝ 👕',
    step4Desc: 'અઠવાડિયામાં સૌથી વધુ વેચાતો સાઇઝ મોડ છે.',
    step4Context: 'સાઇઝ 90,95,100,105,110',
    step5Title: 'એકથી વધુ મોડ 🔁',
    step5Desc: 'જ્યારે અનેક મૂલ્યોનું સર્વોચ્ચ આવર્તન સમાન હોય.',
    step5Context: 'મલ્ટી-મોડલ ઉદાહરણ',
    ex1Title: 'નાનું સેટ મોડ',
    ex1Desc: '1,1,2,2,2,3,3,4,4 નો મોડ શોધો',
    ex1Question: 'મોડ = ?',
    ex2Title: 'શર્ટ સાઇઝ',
    ex2Desc: 'સાઇઝ 90..110 સેમી, ગણતરી 8,22,32,37,6',
    ex2Question: 'કયો સાઇઝ મોડ છે?',
    ex3Title: 'બહુવિધ મોડ',
    ex3Desc: '2,2,5,5,6,3,4,5,2 ના બધા મોડ જણાવો',
    ex3Question: 'મોડ (મૂષળથી અલગ):',
    ex4Title: 'પરીક્ષા ગુણ',
    ex4Desc: 'વર્ગમાં સૌથી સામાન્ય પરીક્ષા ગુણ શોધો.',
    ex4Question: 'પરીક્ષા ગુણનો મોડ શું છે?',
    ex5Title: 'ફિલ્મ રેટિંગ',
    ex5Desc: 'સૌથી વધુ વખત આપવામાં આવેલ રેટિંગ ઓળખો.',
    ex5Question: 'મોડ રેટિંગ = ?',
    ex6Title: 'દૈનિક તાપમાન',
    ex6Desc: 'સૌથી વધુ વાર આવતું તાપમાન મૂલ્ય શોધો.',
    ex6Question: 'મોડ તાપમાન શું છે?',
    rw1Title: 'સૌથી લોકપ્રિય શર્ટ સાઇઝ',
    rw1Desc: 'માગ મુજબ સાઇઝનો સ્ટોક રાખો (મોડ).',
    rw1Context: 'સાઇઝ 90,95,100,105,110 (સેમી)',
    rw2Title: 'દરવાજાની ઊંચાઈ સાવચેતી',
    rw2Desc: 'સુરક્ષા માટે મોડ યોગ્ય ન હોઈ શકે.',
    rw2Context: 'બાળકો અને વયસ્કો દરવાજો વાપરે છે',
    rw3Title: 'કૅન્ટીનમાં ચપાતી',
    rw3Desc: 'મોડ સામાન્ય જરૂરિયાત બતાવે; કુલ માટે સરવાળો/સરેરાશ જોઈએ.',
    rw3Context: 'દર વ્યક્તિ ચપાતી',
    rw4Title: 'સ્ટોરમાં જૂતાનો સાઇઝ',
    rw4Desc: 'સૌથી વધુ વેચાતો જૂતાનો સાઇઝ સ્ટોક કરવામાં મદદ કરે છે.',
    rw4Context: 'જૂતાના સાઇઝ 6, 7, 8, 9, 10',
    rw5Title: 'પસંદીદા આઈસ્ક્રીમ ફ્લેવર',
    rw5Desc: 'સર્વે પરિણામો મોડનો ઉપયોગ કરીને સૌથી લોકપ્રિય સ્વાદ બતાવે છે.',
    rw5Context: 'ફ્લેવર: વનીલા, ચોકલેટ, સ્ટ્રોબેરી, કેરી',
    rw6Title: 'બસ સમયનો ઉપયોગ',
    rw6Desc: 'સૌથી વધુ ઉપયોગમાં લેવાતો બસ સમય મોડ છે, શેડ્યૂલિંગ માટે ઉપયોગી.',
    rw6Context: 'પીક સમય: 7AM, 8AM, 9AM, 6PM',
    question: 'પ્રશ્ન',
    previous: 'પાછળ',
    next: 'આગળ',
    play: 'ચાલુ',
    pause: 'વિરામ',
    reset: 'રીસેટ',
    submitAnswers: 'જવાબ મોકલો',
    score: 'સ્કોર',
    attempts: 'પ્રયાસ',
    showSolution: 'ઉકેલ બતાવો',
    hideSolution: 'ઉકેલ છુપાવો',
    solutionSteps: 'ઉકેલના પગલાં:',
    showHint: 'ઇશારો બતાવો',
    hint: 'ઇશારો',
    enterYourAnswer: 'તમારો જવાબ લખો',
    stepCountEachValue: 'દરેક મૂલ્યની ગણતરી કરો.',
    stepPickHighestFrequency: 'સર્વોચ્ચ આવર્તન (3) ધરાવતું મૂલ્ય પસંદ કરો.',
    stepFindMaxCount: 'મહત્તમ ગણતરી (37) શોધો.',
    stepMapToSize: 'તેને સાઇઝ સાથે મિલાવો',
    stepMultipleModesCounts: '2 ત્રણ વખત આવે છે, 5 ત્રણ વખત આવે છે.',
    stepBothAreModes: 'બંને મોડ છે',
    hintCountFrequencies: 'આવર્તનોની ગણતરી કરો',
    hintPickLargestCount: 'સૌથી મોટો કાઉન્ટ પસંદ કરો',
    definitionLabel: 'વ્યાખ્યા',
    bulletPopular: 'સૌથી લોકપ્રિય વિકલ્પ શોધવામાં ઉપયોગી',
    bulletMultipleModes: 'એકથી વધુ મોડ (બાય/મલ્ટી‑મોડલ) હોઈ શકે',
    modeDefText: 'મોડ તે મૂલ્ય છે જે ડેટામાં સૌથી વધુ વાર આવે છે.',
    formulaLabel: 'સૂત્ર',
    whereFrequency: 'જ્યાં f(x) એ મૂલ્ય x ની આવર્તન (ગણતરી) છે',
    exampleUsingFormula: 'સૂત્ર વાપરીને ઉદાહરણ',
    givenData: 'આપેલ ડેટા',
    frequencyFx: 'આવર્તન f(x)',
    argMaxResult: 'arg max',
    becauseHighestFreq: 'કારણ કે તેની સૌથી વધુ આવર્તન છે',
    thereforeMo: 'તેથી, Mo =',
    tryThisQuestion: 'આ પ્રશ્ન અજમાવો',
    findModeOfData: 'ડેટાનો મોડ શોધો',
    valueLabel: 'મૂલ્ય',
    frequencyLabel: 'આવર્તન',
    currentExample: 'વર્તમાન ઉદાહરણ',
    modesLabelUI: 'મોડ(ઓ):'
  }
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('selectedLanguage');
    if (saved === 'en' || saved === 'hi' || saved === 'gu') return saved;
    return 'en';
  });
  const [isTransitioning, setIsTransitioning] = useState(false);
  const t = useMemo(()=> (key: string)=> translations[language][key] ?? key, [language]);

  const setLanguagePersist = (lang: SupportedLanguage) => {
    if (lang === language) return;
    localStorage.setItem('selectedLanguage', lang);
    setIsTransitioning(true);
    setTimeout(() => {
      setLanguage(lang);
      setTimeout(() => setIsTransitioning(false), 250);
    }, 120);
  };

  const value = useMemo(()=> ({ language, setLanguage: setLanguagePersist, t, isTransitioning }), [language, t, isTransitioning]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}


