import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'hi' | 'gu';
  setLanguage: (lang: 'en' | 'hi' | 'gu') => void;
  t: (key: string) => string;
  isTransitioning: boolean;
  localizeDigitsInText: (text: string) => string;
  formatNumber: (num: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Comprehensive translations
const translations = {
  en: {
    // Navigation
    home: 'Home',
    introduction: 'Introduction',
    learn: 'Learn',
    realWorld: 'Real World',
    simpleEquations: 'Simple Equations - Addition',
    simpleEquationsTitle: 'Simple Equations - Addition',
    exponentsTitle: 'Introduction to Exponents & Powers',
    // Exponents hero (for Learn page)
    expHeroTitle: 'Introduction to Exponents',
    expHeroLine1: 'Exponents are a powerful way to represent repeated multiplication.',
    expHeroLine2: 'They make large numbers easier to read, understand, and work with!',
    interactivePreview: 'Interactive Preview',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 Introduction',
    tabExponents: '11.2 Exponents',
    massOfEarth: 'Mass of Earth',
    massOfUranus: 'Mass of Uranus',
    distancesInSpace: 'Distances in Space',
    hugeNumbersReadable: 'Huge numbers made readable with exponents',
    powerOf3: '5 to the power of 3',
    powerOf4: '3 to the power of 4',
    powerOf6: '2 to the power of 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 Exponents — Basic Concepts',
    visualExponentialForm: 'Visual Exponential Form',
    base: 'Base',
    baseDescription: 'The number being multiplied',
    exponent: 'Exponent',
    exponentDescription: 'How many times to multiply',
    power: 'Power',
    powerDescription: 'The result',
    specialName: 'Special Name',
    squared: 'Squared',
    tenSquared: '"10 squared"',
    cubed: 'Cubed',
    tenCubed: '"10 cubed"',
    primeFactorization: 'Prime Factorization',
    primeFactorizationDesc: 'Express factors compactly using exponents',
    negativeBases: 'Negative Bases',
    generalNotation: 'General Notation',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'Important Points',
    pointAnyBase: 'Any base can be used — not just 10',
    pointExponentialForm: 'Exponential form makes large numbers easier to work with',
    pointPrimeFactorization: 'Prime factorization is compact with exponents',
    
    // Home Page
    masterSimpleEquations: 'Master Simple Equations',
    masterClass7Mathematics: 'Master Class 7 Mathematics with interactive learning, practice exercises, and engaging games based on NCERT curriculum',
    startLearning: 'Start Learning',
    whatYoullLearn: 'What You\'ll Learn',
    comprehensiveTools: 'Comprehensive tools designed to make learning simple equations engaging and effective',
    introductionDesc: 'Learn the basics of simple equations with interactive examples',
    learnDesc: 'Step-by-step explanations with visual aids',
    practiceDesc: 'Solve exercises and check your solutions',
    realWorldDesc: 'See how equations apply in everyday life',
    practiceProblems: 'Practice Problems',
    interactiveExamples: 'Interactive Examples',
    readyToMaster: 'Ready to Master Simple Equations?',
    joinThousands: 'Join thousands of students and teachers who are making mathematics engaging and accessible.',
    startYourJourney: 'Start Your Journey',
    
    // Common
    correct: 'Correct!',
    incorrect: 'Try again!',
    learning: 'Learning',
    practice: 'Practice',
    assessment: 'Assessment',
    selectEquation: 'Select Equation:',
    yourAnswer: 'Your Answer:',
    submit: 'Submit',
    hint: 'Hint',
    progress: 'Progress:',
    accuracy: 'Accuracy',
    avgTime: 'Avg Time',
    correctAnswers: 'Correct',
    incorrectAnswers: 'Incorrect',
    totalExercises: 'Total',
    excellent: 'Excellent!',
    goodJob: 'Good Job!',
    keepTrying: 'Keep Trying!',
    showSolution: 'Show Solution',
    hideSolution: 'Hide Solution',
    reset: 'Reset',
    stepByStepSolution: 'Step-by-Step Solution:',
    nextStep: 'Next Step',
    complete: 'Complete',
    
    // Real World
    realWorldApps: 'Real World Applications',
    selectCategory: 'Select Category:',
    difficulty: 'Difficulty:',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    equation: 'Equation:',
    solution: 'Solution:',
    context: 'Context:',
    shopping: 'Shopping',
    cooking: 'Cooking',
    construction: 'Construction',
    sports: 'Sports',
    finance: 'Finance',
    science: 'Science',
    
    // Learn Section
    linearEquations: 'Linear Equations',
    linearEquationsDesc: 'Linear equations are equations where the highest power of the variable is 1. They can be solved using basic algebraic operations like addition, subtraction, multiplication, and division.',
    solvingByAddition: 'Solving by Addition',
    solvingByAdditionDesc: 'When we have subtraction in an equation, we add the same number to both sides to isolate the variable. This maintains the balance of the equation.',
    solvingBySubtraction: 'Solving by Subtraction',
    solvingBySubtractionDesc: 'When we have addition in an equation, we subtract the same number from both sides to isolate the variable. This maintains the balance of the equation.',
    solvingByMultiplication: 'Solving by Multiplication',
    solvingByMultiplicationDesc: 'When we have division in an equation, we multiply both sides by the same number to isolate the variable. This maintains the balance of the equation.',
    solvingByDivision: 'Solving by Division',
    solvingByDivisionDesc: 'When we have multiplication in an equation, we divide both sides by the same number to isolate the variable. This maintains the balance of the equation.',
    originalEquation: 'Original equation',
    originalEquationWithSubtraction: 'Original equation with subtraction',
    originalEquationWithAddition: 'Original equation with addition',
    originalEquationWithDivision: 'Original equation with division',
    originalEquationWithMultiplication: 'Original equation with multiplication',
    subtractFromBothSides: 'Subtract 5 from both sides',
    addToBothSides: 'Add 3 to both sides to isolate x',
    subtractFromBothSidesToIsolate: 'Subtract 4 from both sides to isolate x',
    multiplyBothSides: 'Multiply both sides by 3 to isolate x',
    divideBothSides: 'Divide both sides by 3 to isolate x',
    simplifyToFindAnswer: 'Simplify to find the answer',
    simplifyStep: 'Simplify: 5 - 5 = 0 and 12 - 5 = 7',
    verifySolution: 'Verify the solution by substituting x = 7',
    simplifyAdditionStep: 'Simplify: -3 + 3 = 0 and 8 + 3 = 11',
    verifyAdditionSolution: 'Verify the solution by substituting x = 11',
    simplifySubtractionStep: 'Simplify: 4 - 4 = 0 and 7 - 4 = 3',
    verifySubtractionSolution: 'Verify the solution by substituting x = 3',
    simplifyMultiplicationStep: 'Simplify: 3/3 = 1 and 4 × 3 = 12',
    verifyMultiplicationSolution: 'Verify the solution by substituting x = 12',
    simplifyDivisionStep: 'Simplify: 3x ÷ 3 = x and 15 ÷ 3 = 5',
    verifyDivisionSolution: 'Verify the solution by substituting x = 5',
    linearEquationExample: 'Linear Equation Example',
    additionMethodExample: 'Addition Method Example',
    subtractionMethodExample: 'Subtraction Method Example',
    multiplicationMethodExample: 'Multiplication Method Example',
    divisionMethodExample: 'Division Method Example',
    solving: 'Solving:',
    play: 'Play',
    pause: 'Pause',
    previous: 'Previous',
    next: 'Next',
    
    // Practice Mode
    practiceMode: 'Practice Mode',
    question: 'Question',
    skippedQuestions: 'Skipped Questions',
    notAttempted: 'Not Attempted',
    totalQuestions: 'Total Questions',
    finalGrade: 'Final Grade',
    accuracyRate: 'Accuracy Rate',
    avgTimePerQuestion: 'Avg Time/Question',
    questionByQuestionReview: 'Question by Question Review',
    startNewSession: 'Start New Session',
    loadingQuestions: 'Loading questions...',
    showAnswer: 'Show Answer',
    hideAnswer: 'Hide Answer',
    tryAgain: 'Try Again',
    skip: 'Skip',
    skipped: 'Skipped',
    sessionComplete: 'Session Complete!',
    sessionSummary: 'Here\'s your complete session summary',
    correctAnswer: 'Correct Answer',
    check: 'Check',
    notAttempt: 'Not Attempt',
    
    // Practice Questions
    q1_prompt: 'Convert 10,000 to exponential form',
    q1_explanation: '10,000 = 10 × 10 × 10 × 10 = 10⁴',
    q2_prompt: 'What is 5³?',
    q2_explanation: '5³ = 5 × 5 × 5 = 125',
    q3_prompt: 'What is the base in 7⁴?',
    q3_explanation: 'In 7⁴, 7 is the base (the number being multiplied)',
    q4_prompt: 'What is the exponent in 2⁵?',
    q4_explanation: 'In 2⁵, 5 is the exponent (showing how many times 2 is multiplied)',
    q5_prompt: 'Calculate 3⁴',
    q5_explanation: '3⁴ = 3 × 3 × 3 × 3 = 81',
    q6_prompt: 'What is 100 in exponential form?',
    q6_explanation: '100 = 10 × 10 = 10²',
    
    // Practice Questions
    practice_q1: 'Solve: x + 7 = 15',
    practice_q2: 'Solve: x + 4 = 12',
    practice_q3: 'Solve: x + 3 = 21',
    practice_q4: 'Solve: x + 2 = 8',
    practice_q5: 'Solve: x + 3 = 11',
    practice_q6: 'Solve: x + 5 = 9',
    practice_q7: 'Solve: x + 6 = 18',
    practice_q8: 'Solve: x + 2 = 7',
    practice_q9: 'Solve: x + 8 = 33',
    practice_q10: 'Solve: x + 7 = 13',
    practice_q11: 'Solve: x + 3 = 8',
    practice_q12: 'Solve: x + 12 = 30',
    
    // Exponents - Section 1: Introduction
    exp_intro_title: 'Why Do We Need Exponents?',
    exp_intro_text: 'Very large numbers are difficult to work with:',
    exp_problem_1: 'Hard to Read: 5,970,000,000,000,000,000,000,000 kg',
    exp_problem_2: 'Hard to Understand: How big is this number?',
    exp_problem_3: 'Hard to Compare: Which is bigger - Earth or Uranus?',
    exp_intro_solution: 'Solution: Use exponents to write numbers in a shorter, simpler form!',
    exp_example_title: 'Real-World Example',
    exp_example_before: 'Mass of Earth = 5,970,000,000,000,000,000,000,000 kg',
    exp_example_after: 'Mass of Earth = 5.97 × 10²⁴ kg',
    exp_example_benefit: 'Much easier to read and compare!',
    exp_before: 'Before',
    exp_after: 'After',
    
    // Exponents - Section 2: What Are Exponents
    exp_what_are_title: 'What Are Exponents?',
    exp_what_are_text: 'Exponents let us write repeated multiplication in a compact way.',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'Repeated multiplication',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'Exponential form',
    exp_main_example: 'Main Example',
    exp_term_base: 'Base',
    exp_term_base_def: 'The number being multiplied',
    exp_term_base_ex: 'In 10⁴, base = 10',
    exp_term_exp: 'Exponent',
    exp_term_exp_def: 'How many times to multiply the base',
    exp_term_exp_ex: 'In 10⁴, exponent = 4',
    exp_term_power: 'Power',
    exp_term_power_def: 'The whole expression',
    exp_term_power_ex: '10⁴ is read as "10 to the power of 4"',
    exp_key_terms: 'Key Terms to Remember:',
    
    // Exponents - Section 3: Working with Examples
    exp_examples_title: 'Working with Examples',
    exp_conversion_text: 'Let\'s see how numbers are converted to exponential form:',
    exp_example: 'Example',
    exp_step1: 'Step 1: Write as multiplication',
    exp_step2: 'Step 2: Write in exponential form',
    exp_base: 'Base',
    exp_exponent: 'Exponent',
    exp_read_as: 'Read as',
    exp_ex1_reading: '10 raised to the power of 3',
    exp_ex2_reading: '3 raised to the power of 4',
    exp_ex3_reading: '5 cubed',
    exp_ex4_reading: '2 raised to the power of 5',
    
    // Exponents - Section 4: Special Names
    exp_special_title: 'Special Names',
    exp_special_intro: 'Some exponents have special names that you\'ll use often:',
    exp_squared: 'Squared',
    exp_squared_read: 'squared',
    exp_cubed: 'Cubed',
    exp_cubed_read: 'cubed',
    exp_special_note: 'These special names come from geometry - squared from area of a square, cubed from volume of a cube!',
    exp_power_of: 'Power of',
    exp_fun_fact: 'Fun Fact',
    
    // Exponents - Section 5: Interactive Practice
    exp_practice_title: 'Interactive Practice',
    exp_interactive_intro: 'Try it yourself! Change the base and exponent to see how exponents work:',
    exp_expanded: 'Expanded Form',
    exp_exponential_form: 'Exponential Form',
    exp_result: 'Result',
    exp_reading_title: 'Reading',
    exp_raised_to: 'raised to the power of',
    exp_or: 'or',
    
    // Exponents - Common Terms
    of: 'of',
    example: 'Example',
    formula: 'Formula',
    explanation: 'Explanation'
  },
  hi: {
    // Navigation
    home: 'होम',
    introduction: 'परिचय',
    learn: 'सीखें',
    realWorld: 'वास्तविक दुनिया',
    simpleEquations: 'सरल समीकरण - जोड़',
    simpleEquationsTitle: 'सरल समीकरण - जोड़',
    exponentsTitle: 'घातांक और घात का परिचय',
    // Exponents hero (for Learn page)
    expHeroTitle: 'घातांकों का परिचय',
    expHeroLine1: 'घातांक बार‑बार गुणा को दर्शाने का एक शक्तिशाली तरीका है।',
    expHeroLine2: 'ये बड़ी संख्याओं को पढ़ना, समझना और उनके साथ काम करना आसान बनाते हैं!',
    interactivePreview: 'इंटरैक्टिव पूर्वावलोकन',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 परिचय',
    tabExponents: '11.2 घातांक',
    massOfEarth: 'पृथ्वी का द्रव्यमान',
    massOfUranus: 'यूरेनस का द्रव्यमान',
    distancesInSpace: 'अंतरिक्ष में दूरियाँ',
    hugeNumbersReadable: 'घातांकों से बड़ी संख्याएँ पढ़ने योग्य बनती हैं',
    powerOf3: '5 की घात 3',
    powerOf4: '3 की घात 4',
    powerOf6: '2 की घात 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 घातांक — मूल अवधारणाएँ',
    visualExponentialForm: 'दृश्य घातांकीय रूप',
    base: 'आधार',
    baseDescription: 'वह संख्या जिसे गुणा किया जा रहा है',
    exponent: 'घातांक',
    exponentDescription: 'कितनी बार गुणा करना है',
    power: 'घात',
    powerDescription: 'परिणाम',
    specialName: 'विशेष नाम',
    squared: 'वर्ग',
    tenSquared: '"10 का वर्ग"',
    cubed: 'घन',
    tenCubed: '"10 का घन"',
    primeFactorization: 'अभाज्य गुणनखंडन',
    primeFactorizationDesc: 'घातांकों का उपयोग करके गुणनखंडों को संक्षिप्त रूप से व्यक्त करें',
    negativeBases: 'ऋणात्मक आधार',
    generalNotation: 'सामान्य संकेतन',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'महत्वपूर्ण बिंदु',
    pointAnyBase: 'कोई भी आधार उपयोग किया जा सकता है — केवल 10 ही नहीं',
    pointExponentialForm: 'घातांकीय रूप बड़ी संख्याओं के साथ काम करना आसान बनाता है',
    pointPrimeFactorization: 'अभाज्य गुणनखंडन घातांकों के साथ संक्षिप्त होता है',
    
    // Home Page
    masterSimpleEquations: 'सरल समीकरणों में महारत हासिल करें',
    masterClass7Mathematics: 'एनसीईआरटी पाठ्यक्रम के आधार पर इंटरैक्टिव सीखने, अभ्यास अभ्यास और आकर्षक गेम के साथ कक्षा 7 गणित में महारत हासिल करें',
    startLearning: 'सीखना शुरू करें',
    whatYoullLearn: 'आप क्या सीखेंगे',
    comprehensiveTools: 'सरल समीकरणों को सीखने को आकर्षक और प्रभावी बनाने के लिए डिज़ाइन किए गए व्यापक उपकरण',
    introductionDesc: 'इंटरैक्टिव उदाहरणों के साथ सरल समीकरणों की मूल बातें सीखें',
    learnDesc: 'दृश्य सहायता के साथ चरण-दर-चरण स्पष्टीकरण',
    practiceDesc: 'अभ्यास हल करें और अपने समाधान जांचें',
    realWorldDesc: 'देखें कि समीकरण रोजमर्रा की जिंदगी में कैसे लागू होते हैं',
    practiceProblems: 'अभ्यास समस्याएं',
    interactiveExamples: 'इंटरैक्टिव उदाहरण',
    readyToMaster: 'सरल समीकरणों में महारत हासिल करने के लिए तैयार हैं?',
    joinThousands: 'हजारों छात्रों और शिक्षकों में शामिल हों जो गणित को आकर्षक और सुलभ बना रहे हैं।',
    startYourJourney: 'अपनी यात्रा शुरू करें',
    
    // Common
    correct: 'सही!',
    incorrect: 'फिर कोशिश करें!',
    learning: 'सीखना',
    practice: 'अभ्यास',
    assessment: 'मूल्यांकन',
    selectEquation: 'समीकरण चुनें:',
    yourAnswer: 'आपका उत्तर:',
    submit: 'जमा करें',
    hint: 'संकेत',
    progress: 'प्रगति:',
    accuracy: 'सटीकता',
    avgTime: 'औसत समय',
    correctAnswers: 'सही',
    incorrectAnswers: 'गलत',
    totalExercises: 'कुल',
    excellent: 'उत्कृष्ट!',
    goodJob: 'अच्छा काम!',
    keepTrying: 'कोशिश करते रहें!',
    showSolution: 'समाधान दिखाएं',
    hideSolution: 'समाधान छुपाएं',
    reset: 'रीसेट',
    stepByStepSolution: 'चरण-दर-चरण समाधान:',
    nextStep: 'अगला चरण',
    complete: 'पूर्ण',
    
    // Real World
    realWorldApps: 'वास्तविक दुनिया के अनुप्रयोग',
    selectCategory: 'श्रेणी चुनें:',
    difficulty: 'कठिनाई:',
    beginner: 'शुरुआती',
    intermediate: 'मध्यम',
    advanced: 'उन्नत',
    equation: 'समीकरण:',
    solution: 'समाधान:',
    context: 'संदर्भ:',
    shopping: 'खरीदारी',
    cooking: 'खाना पकाना',
    construction: 'निर्माण',
    sports: 'खेल',
    finance: 'वित्त',
    science: 'विज्ञान',
    
    // Learn Section
    linearEquations: 'रैखिक समीकरण',
    linearEquationsDesc: 'रैखिक समीकरण वे समीकरण हैं जहाँ चर की सबसे बड़ी घात 1 है।',
    solvingByAddition: 'जोड़ द्वारा हल करना',
    solvingByAdditionDesc: 'जब हमारे पास समीकरण में घटाव होता है, तो हम चर को अलग करने के लिए दोनों पक्षों में समान संख्या जोड़ते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingBySubtraction: 'घटाव द्वारा हल करना',
    solvingBySubtractionDesc: 'जब हमारे पास समीकरण में जोड़ होता है, तो हम चर को अलग करने के लिए दोनों पक्षों से समान संख्या घटाते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingByMultiplication: 'गुणा द्वारा हल करना',
    solvingByMultiplicationDesc: 'जब हमारे पास समीकरण में भाग होता है, तो हम चर को अलग करने के लिए दोनों पक्षों को समान संख्या से गुणा करते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingByDivision: 'भाग द्वारा हल करना',
    solvingByDivisionDesc: 'जब हमारे पास समीकरण में गुणा होता है, तो हम चर को अलग करने के लिए दोनों पक्षों को समान संख्या से भाग देते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    originalEquation: 'मूल समीकरण',
    originalEquationWithSubtraction: 'घटाव के साथ मूल समीकरण',
    originalEquationWithAddition: 'जोड़ के साथ मूल समीकरण',
    originalEquationWithDivision: 'भाग के साथ मूल समीकरण',
    originalEquationWithMultiplication: 'गुणा के साथ मूल समीकरण',
    subtractFromBothSides: 'दोनों पक्षों से 5 घटाएं',
    addToBothSides: 'x को अलग करने के लिए दोनों पक्षों में 3 जोड़ें',
    subtractFromBothSidesToIsolate: 'x को अलग करने के लिए दोनों पक्षों से 4 घटाएं',
    multiplyBothSides: 'x को अलग करने के लिए दोनों पक्षों को 3 से गुणा करें',
    divideBothSides: 'x को अलग करने के लिए दोनों पक्षों को 3 से भाग दें',
    simplifyToFindAnswer: 'उत्तर ज्ञात करने के लिए सरल करें',
    simplifyStep: 'सरल करें: 5 - 5 = 0 और 12 - 5 = 7',
    verifySolution: 'x = 7 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyAdditionStep: 'सरल करें: -3 + 3 = 0 और 8 + 3 = 11',
    verifyAdditionSolution: 'x = 11 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifySubtractionStep: 'सरल करें: 4 - 4 = 0 और 7 - 4 = 3',
    verifySubtractionSolution: 'x = 3 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyMultiplicationStep: 'सरल करें: 3/3 = 1 और 4 × 3 = 12',
    verifyMultiplicationSolution: 'x = 12 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyDivisionStep: 'सरल करें: 3x ÷ 3 = x और 15 ÷ 3 = 5',
    verifyDivisionSolution: 'x = 5 प्रतिस्थापित करके समाधान सत्यापित करें',
    linearEquationExample: 'रैखिक समीकरण उदाहरण',
    additionMethodExample: 'जोड़ विधि उदाहरण',
    subtractionMethodExample: 'घटाव विधि उदाहरण',
    multiplicationMethodExample: 'गुणा विधि उदाहरण',
    divisionMethodExample: 'भाग विधि उदाहरण',
    solving: 'हल करना:',
    play: 'चलाएं',
    pause: 'रोकें',
    previous: 'पिछला',
    next: 'अगला',
    
    // Practice Mode
    practiceMode: 'अभ्यास मोड',
    question: 'प्रश्न',
    skippedQuestions: 'छोड़े गए प्रश्न',
    notAttempted: 'प्रयास नहीं किया',
    totalQuestions: 'कुल प्रश्न',
    finalGrade: 'अंतिम ग्रेड',
    accuracyRate: 'सटीकता दर',
    avgTimePerQuestion: 'प्रति प्रश्न औसत समय',
    questionByQuestionReview: 'प्रश्न दर प्रश्न समीक्षा',
    startNewSession: 'नया सत्र शुरू करें',
    loadingQuestions: 'प्रश्न लोड हो रहे हैं...',
    showAnswer: 'उत्तर दिखाएं',
    hideAnswer: 'उत्तर छुपाएं',
    tryAgain: 'फिर कोशिश करें',
    skip: 'छोड़ें',
    skipped: 'छोड़ा गया',
    sessionComplete: 'सत्र पूरा!',
    sessionSummary: 'यहाँ आपका पूरा सत्र सारांश है',
    correctAnswer: 'सही उत्तर',
    check: 'जांच',
    notAttempt: 'प्रयास नहीं करें',
    
    // Practice Questions - Exponents
    q1_prompt: '10,000 को घातांकीय रूप में बदलें',
    q1_explanation: '10,000 = 10 × 10 × 10 × 10 = 10⁴',
    q2_prompt: '5³ क्या है?',
    q2_explanation: '5³ = 5 × 5 × 5 = 125',
    q3_prompt: '7⁴ में आधार क्या है?',
    q3_explanation: '7⁴ में, 7 आधार है (जिस संख्या को गुणा किया जा रहा है)',
    q4_prompt: '2⁵ में घातांक क्या है?',
    q4_explanation: '2⁵ में, 5 घातांक है (दिखाता है कि 2 कितनी बार गुणा होता है)',
    q5_prompt: '3⁴ की गणना करें',
    q5_explanation: '3⁴ = 3 × 3 × 3 × 3 = 81',
    q6_prompt: '100 घातांकीय रूप में क्या है?',
    q6_explanation: '100 = 10 × 10 = 10²',
    
    // Practice Questions
    practice_q1: 'हल करें: x + 7 = 15',
    practice_q2: 'हल करें: x + 4 = 12',
    practice_q3: 'हल करें: x + 3 = 21',
    practice_q4: 'हल करें: x + 2 = 8',
    practice_q5: 'हल करें: x + 3 = 11',
    practice_q6: 'हल करें: x + 5 = 9',
    practice_q7: 'हल करें: x + 6 = 18',
    practice_q8: 'हल करें: x + 2 = 7',
    practice_q9: 'हल करें: x + 8 = 33',
    practice_q10: 'हल करें: x + 7 = 13',
    practice_q11: 'हल करें: x + 3 = 8',
    practice_q12: 'हल करें: x + 12 = 30',
    
    // Exponents
    exp_intro_title: 'घातांक क्यों चाहिए?',
    exp_intro_text: 'बहुत बड़ी संख्याओं के साथ काम करना मुश्किल है:',
    exp_problem_1: 'पढ़ना मुश्किल: 5,970,000,000,000,000,000,000,000 किलो',
    exp_problem_2: 'समझना मुश्किल: यह संख्या कितनी बड़ी है?',
    exp_problem_3: 'तुलना करना मुश्किल: कौन बड़ा है - पृथ्वी या यूरेनस?',
    exp_intro_solution: 'समाधान: संख्याओं को छोटे, सरल रूप में लिखने के लिए घातांक का उपयोग करें!',
    exp_example_title: 'वास्तविक दुनिया का उदाहरण',
    exp_example_before: 'पृथ्वी का द्रव्यमान = 5,970,000,000,000,000,000,000,000 किलो',
    exp_example_after: 'पृथ्वी का द्रव्यमान = 5.97 × 10²⁴ किलो',
    exp_example_benefit: 'पढ़ने और तुलना करने में बहुत आसान!',
    exp_before: 'पहले',
    exp_after: 'बाद में',
    exp_what_are_title: 'घातांक क्या हैं?',
    exp_what_are_text: 'घातांक हमें दोहरा गुणन को संक्षिप्त तरीके से लिखने देते हैं।',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'दोहरा गुणन',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'घातांक रूप',
    exp_main_example: 'मुख्य उदाहरण',
    exp_term_base: 'आधार',
    exp_term_base_def: 'गुणा होने वाली संख्या',
    exp_term_base_ex: '10⁴ में, आधार = 10',
    exp_term_exp: 'घातांक',
    exp_term_exp_def: 'आधार को कितनी बार गुणा करना है',
    exp_term_exp_ex: '10⁴ में, घातांक = 4',
    exp_term_power: 'घात',
    exp_term_power_def: 'पूरी अभिव्यक्ति',
    exp_term_power_ex: '10⁴ को "10 की घात 4" पढ़ा जाता है',
    exp_key_terms: 'याद रखने योग्य मुख्य शब्द:',
    exp_examples_title: 'उदाहरणों के साथ कार्य',
    exp_conversion_text: 'देखते हैं कि संख्याओं को घातांक रूप में कैसे परिवर्तित किया जाता है:',
    exp_example: 'उदाहरण',
    exp_step1: 'चरण 1: गुणन के रूप में लिखें',
    exp_step2: 'चरण 2: घातांक रूप में लिखें',
    exp_base: 'आधार',
    exp_exponent: 'घातांक',
    exp_read_as: 'पढ़ें',
    exp_ex1_reading: '10 की घात 3',
    exp_ex2_reading: '3 की घात 4',
    exp_ex3_reading: '5 घन',
    exp_ex4_reading: '2 की घात 5',
    exp_special_title: 'विशेष नाम',
    exp_special_intro: 'कुछ घातांकों के विशेष नाम हैं जिनका आप अक्सर उपयोग करेंगे:',
    exp_squared: 'वर्ग',
    exp_squared_read: 'वर्ग',
    exp_cubed: 'घन',
    exp_cubed_read: 'घन',
    exp_special_note: 'ये विशेष नाम ज्यामिति से आते हैं - वर्ग वर्ग के क्षेत्रफल से, घन घन के आयतन से!',
    exp_power_of: 'घात',
    exp_fun_fact: 'रोचक तथ्य',
    exp_practice_title: 'इंटरैक्टिव अभ्यास',
    exp_interactive_intro: 'खुद आजमाएं! घातांक कैसे काम करते हैं देखने के लिए आधार और घातांक को बदलें:',
    exp_expanded: 'विस्तारित रूप',
    exp_exponential_form: 'घातांक रूप',
    exp_result: 'परिणाम',
    exp_reading_title: 'पढ़ना',
    exp_raised_to: 'की घात',
    exp_or: 'या',
    of: 'का',
    example: 'उदाहरण',
    formula: 'सूत्र',
    explanation: 'स्पष्टीकरण'
  },
  gu: {
    // Navigation
    home: 'ઘર',
    introduction: 'પરિચય',
    learn: 'શીખો',
    realWorld: 'વાસ્તવિક વિશ્વ',
    simpleEquations: 'સરળ સમીકરણો - ઉમેરણ',
    simpleEquationsTitle: 'સરળ સમીકરણો - ઉમેરણ',
    exponentsTitle: 'ઘાતાંક અને ઘાતનો પરિચય',
    // Exponents hero (for Learn page)
    expHeroTitle: 'ઘાતાંકનો પરિચય',
    expHeroLine1: 'ઘાતાંક વારંવારના ગુણાકાર દર્શાવવાનો શક્તિશાળી રસ્તો છે.',
    expHeroLine2: 'તે મોટી સંખ્યાઓ વાંચવા, સમજવા અને તેમ સાથે કામ કરવું સરળ બનાવે છે!',
    interactivePreview: 'ઇન્ટરેક્ટિવ પૂર્વાવલોકન',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 પરિચય',
    tabExponents: '11.2 ઘાતાંક',
    massOfEarth: 'પૃથ્વીનું દળ',
    massOfUranus: 'યુરેનસનું દળ',
    distancesInSpace: 'અવકાશમાં અંતર',
    hugeNumbersReadable: 'ઘાતાંકો સાથે મોટી સંખ્યાઓ વાંચવા યોગ્ય બને છે',
    powerOf3: '5 ની ઘાત 3',
    powerOf4: '3 ની ઘાત 4',
    powerOf6: '2 ની ઘાત 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 ઘાતાંક — મૂળભૂત ખ્યાલો',
    visualExponentialForm: 'વિઝ્યુઅલ ઘાતાંકીય સ્વરૂપ',
    base: 'આધાર',
    baseDescription: 'જે સંખ્યાનો ગુણાકાર થઈ રહ્યો છે',
    exponent: 'ઘાતાંક',
    exponentDescription: 'કેટલી વાર ગુણાકાર કરવો',
    power: 'ઘાત',
    powerDescription: 'પરિણામ',
    specialName: 'ખાસ નામ',
    squared: 'વર્ગ',
    tenSquared: '"10 નો વર્ગ"',
    cubed: 'ઘન',
    tenCubed: '"10 નો ઘન"',
    primeFactorization: 'અવિભાજ્ય અવયવીકરણ',
    primeFactorizationDesc: 'ઘાતાંકનો ઉપયોગ કરીને અવયવોને સંક્ષિપ્તમાં વ્યક્ત કરો',
    negativeBases: 'નકારાત્મક આધાર',
    generalNotation: 'સામાન્ય સંકેતલિપિ',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'મહત્વપૂર્ણ મુદ્દાઓ',
    pointAnyBase: 'કોઈપણ આધારનો ઉપયોગ કરી શકાય છે — ફક્ત 10 જ નહીં',
    pointExponentialForm: 'ઘાતાંકીય સ્વરૂપ મોટી સંખ્યાઓ સાથે કામ કરવાનું સરળ બનાવે છે',
    pointPrimeFactorization: 'અવિભાજ્ય અવયવીકરણ ઘાતાંક સાથે સંક્ષિપ્ત હોય છે',
    
    // Home Page
    masterSimpleEquations: 'સરળ સમીકરણોમાં નિપુણતા મેળવો',
    masterClass7Mathematics: 'એનસીઇઆરટી અભ્યાસક્રમના આધારે ઇન્ટરેક્ટિવ શીખવા, પ્રેક્ટિસ કસરતો અને આકર્ષક રમતો સાથે ધોરણ 7 ગણિતમાં નિપુણતા મેળવો',
    startLearning: 'શીખવાનું શરૂ કરો',
    whatYoullLearn: 'તમે શું શીખશો',
    comprehensiveTools: 'સરળ સમીકરણોને શીખવાનું આકર્ષક અને અસરકારક બનાવવા માટે ડિઝાઇન કરેલા વ્યાપક સાધનો',
    introductionDesc: 'ઇન્ટરેક્ટિવ ઉદાહરણો સાથે સરળ સમીકરણોની મૂળભૂત વાતો શીખો',
    learnDesc: 'વિઝ્યુઅલ સહાયતા સાથે પગલું-દર-પગલું સ્પષ્ટતા',
    practiceDesc: 'કસરતો હલ કરો અને તમારા ઉકેલો તપાસો',
    realWorldDesc: 'જુઓ કે સમીકરણો રોજિંદા જીવનમાં કેવી રીતે લાગુ પડે છે',
    practiceProblems: 'પ્રેક્ટિસ સમસ્યાઓ',
    interactiveExamples: 'ઇન્ટરેક્ટિવ ઉદાહરણો',
    readyToMaster: 'સરળ સમીકરણોમાં નિપુણતા મેળવવા માટે તૈયાર છો?',
    joinThousands: 'હજારો વિદ્યાર્થીઓ અને શિક્ષકોમાં જોડાઓ જે ગણિતને આકર્ષક અને સુલભ બનાવી રહ્યા છે.',
    startYourJourney: 'તમારી યાત્રા શરૂ કરો',
    
    // Common
    correct: 'સાચું!',
    incorrect: 'ફરી કોશિશ કરો!',
    learning: 'શીખવું',
    practice: 'પ્રેક્ટિસ',
    assessment: 'મૂલ્યાંકન',
    selectEquation: 'સમીકરણ પસંદ કરો:',
    yourAnswer: 'તમારો જવાબ:',
    submit: 'સબમિટ',
    hint: 'સંકેત',
    progress: 'પ્રગતિ:',
    accuracy: 'ચોકસાઈ',
    avgTime: 'સરેરાશ સમય',
    correctAnswers: 'સાચું',
    incorrectAnswers: 'ખોટું',
    totalExercises: 'કુલ',
    excellent: 'ઉત્તમ!',
    goodJob: 'સારું કામ!',
    keepTrying: 'કોશિશ કરતા રહો!',
    showSolution: 'ઉકેલ બતાવો',
    hideSolution: 'ઉકેલ છુપાવો',
    reset: 'રીસેટ',
    stepByStepSolution: 'પગલું-દર-પગલું ઉકેલ:',
    nextStep: 'આગળનું પગલું',
    complete: 'પૂર્ણ',
    
    // Real World
    realWorldApps: 'વાસ્તવિક વિશ્વના ઉપયોગો',
    selectCategory: 'શ્રેણી પસંદ કરો:',
    difficulty: 'મુશ્કેલી:',
    beginner: 'શરૂઆત',
    intermediate: 'મધ્યમ',
    advanced: 'અદ્યતન',
    equation: 'સમીકરણ:',
    solution: 'ઉકેલ:',
    context: 'સંદર્ભ:',
    shopping: 'ખરીદી',
    cooking: 'રસોઈ',
    construction: 'બાંધકામ',
    sports: 'રમત',
    finance: 'વિત્ત',
    science: 'વિજ્ઞાન',
    
    // Learn Section
    linearEquations: 'રેખીય સમીકરણો',
    linearEquationsDesc: 'રેખીય સમીકરણો એવા સમીકરણો છે જ્યાં ચલની સર્વોચ્ચ ઘાત 1 છે. તેમને જોડાણ, બાદબાકી, ગુણાકાર અને ભાગાકાર જેવી મૂળભૂત બીજગણિતીય ક્રિયાઓનો ઉપયોગ કરીને હલ કરી શકાય છે.',
    solvingByAddition: 'જોડાણ દ્વારા હલ કરવું',
    solvingByAdditionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં બાદબાકી હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓમાં સમાન સંખ્યા ઉમેરીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingBySubtraction: 'બાદબાકી દ્વારા હલ કરવું',
    solvingBySubtractionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં જોડાણ હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓમાંથી સમાન સંખ્યા બાદ કરીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingByMultiplication: 'ગુણાકાર દ્વારા હલ કરવું',
    solvingByMultiplicationDesc: 'જ્યારે આપણી પાસે સમીકરણમાં ભાગાકાર હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓને સમાન સંખ્યા વડે ગુણીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingByDivision: 'ભાગાકાર દ્વારા હલ કરવું',
    solvingByDivisionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં ગુણાકાર હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓને સમાન સંખ્યા વડે ભાગીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    originalEquation: 'મૂળ સમીકરણ',
    originalEquationWithSubtraction: 'બાદબાકી સાથે મૂળ સમીકરણ',
    originalEquationWithAddition: 'જોડાણ સાથે મૂળ સમીકરણ',
    originalEquationWithDivision: 'ભાગાકાર સાથે મૂળ સમીકરણ',
    originalEquationWithMultiplication: 'ગુણાકાર સાથે મૂળ સમીકરણ',
    subtractFromBothSides: 'બંને બાજુઓમાંથી 5 બાદ કરો',
    addToBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓમાં 3 ઉમેરો',
    subtractFromBothSidesToIsolate: 'x ને અલગ કરવા માટે બંને બાજુઓમાંથી 4 બાદ કરો',
    multiplyBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓને 3 વડે ગુણો',
    divideBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓને 3 વડે ભાગો',
    simplifyToFindAnswer: 'જવાબ શોધવા માટે સરળ બનાવો',
    simplifyStep: 'સરળ બનાવો: 5 - 5 = 0 અને 12 - 5 = 7',
    verifySolution: 'x = 7 મૂકીને ઉકેલ ચકાસો',
    simplifyAdditionStep: 'સરળ બનાવો: -3 + 3 = 0 અને 8 + 3 = 11',
    verifyAdditionSolution: 'x = 11 મૂકીને ઉકેલ ચકાસો',
    simplifySubtractionStep: 'સરળ બનાવો: 4 - 4 = 0 અને 7 - 4 = 3',
    verifySubtractionSolution: 'x = 3 મૂકીને ઉકેલ ચકાસો',
    simplifyMultiplicationStep: 'સરળ બનાવો: 3/3 = 1 અને 4 × 3 = 12',
    verifyMultiplicationSolution: 'x = 12 મૂકીને ઉકેલ ચકાસો',
    simplifyDivisionStep: 'સરળ બનાવો: 3x ÷ 3 = x અને 15 ÷ 3 = 5',
    verifyDivisionSolution: 'x = 5 મૂકીને ઉકેલ ચકાસો',
    linearEquationExample: 'રેખીય સમીકરણ ઉદાહરણ',
    additionMethodExample: 'જોડાણ પદ્ધતિ ઉદાહરણ',
    subtractionMethodExample: 'બાદબાકી પદ્ધતિ ઉદાહરણ',
    multiplicationMethodExample: 'ગુણાકાર પદ્ધતિ ઉદાહરણ',
    divisionMethodExample: 'ભાગાકાર પદ્ધતિ ઉદાહરણ',
    solving: 'હલ કરવું:',
    play: 'ચલાવો',
    pause: 'રોકો',
    previous: 'પાછલું',
    next: 'આગળનું',
    
    // Practice Mode
    practiceMode: 'પ્રેક્ટિસ મોડ',
    question: 'પ્રશ્ન',
    skippedQuestions: 'છોડેલા પ્રશ્નો',
    notAttempted: 'પ્રયાસ નથી કર્યો',
    totalQuestions: 'કુલ પ્રશ્નો',
    finalGrade: 'અંતિમ ગ્રેડ',
    accuracyRate: 'ચોકસાઈ દર',
    avgTimePerQuestion: 'પ્રતિ પ્રશ્ન સરેરાશ સમય',
    questionByQuestionReview: 'પ્રશ્ન દર પ્રશ્ન સમીક્ષા',
    startNewSession: 'નવો સત્ર શરૂ કરો',
    loadingQuestions: 'પ્રશ્નો લોડ થઈ રહ્યા છે...',
    showAnswer: 'જવાબ બતાવો',
    hideAnswer: 'જવાબ છુપાવો',
    tryAgain: 'ફરી કોશિશ કરો',
    skip: 'છોડો',
    skipped: 'છોડાયેલું',
    sessionComplete: 'સત્ર પૂર્ણ!',
    sessionSummary: 'અહીં તમારો સંપૂર્ણ સત્ર સારાંશ છે',
    correctAnswer: 'સાચો જવાબ',
    check: 'તપાસ',
    notAttempt: 'પ્રયાસ ન કરો',
    
    // Practice Questions - Exponents
    q1_prompt: '10,000 ને ઘાતાંકીય સ્વરૂપમાં રૂપાંતરિત કરો',
    q1_explanation: '10,000 = 10 × 10 × 10 × 10 = 10⁴',
    q2_prompt: '5³ શું છે?',
    q2_explanation: '5³ = 5 × 5 × 5 = 125',
    q3_prompt: '7⁴ માં આધાર શું છે?',
    q3_explanation: '7⁴ માં, 7 એ આધાર છે (જે સંખ્યાને ગુણાકાર કરવામાં આવી રહી છે)',
    q4_prompt: '2⁵ માં ઘાતાંક શું છે?',
    q4_explanation: '2⁵ માં, 5 એ ઘાતાંક છે (દર્શાવે છે કે 2 કેટલી વાર ગુણાકાર થાય છે)',
    q5_prompt: '3⁴ ની ગણતરી કરો',
    q5_explanation: '3⁴ = 3 × 3 × 3 × 3 = 81',
    q6_prompt: '100 ઘાતાંકીય સ્વરૂપમાં શું છે?',
    q6_explanation: '100 = 10 × 10 = 10²',
    
    // Practice Questions
    practice_q1: 'હલ કરો: x + 7 = 15',
    practice_q2: 'હલ કરો: x + 4 = 12',
    practice_q3: 'હલ કરો: x + 3 = 21',
    practice_q4: 'હલ કરો: x + 2 = 8',
    practice_q5: 'હલ કરો: x + 3 = 11',
    practice_q6: 'હલ કરો: x + 5 = 9',
    practice_q7: 'હલ કરો: x + 6 = 18',
    practice_q8: 'હલ કરો: x + 2 = 7',
    practice_q9: 'હલ કરો: x + 8 = 33',
    practice_q10: 'હલ કરો: x + 7 = 13',
    practice_q11: 'હલ કરો: x + 3 = 8',
    practice_q12: 'હલ કરો: x + 12 = 30',
    
    // Exponents
    exp_intro_title: 'ઘાતાંકની જરૂર કેમ છે?',
    exp_intro_text: 'ખૂબ મોટી સંખ્યાઓ સાથે કામ કરવું મુશ્કેલ છે:',
    exp_problem_1: 'વાંચવું મુશ્કેલ: 5,970,000,000,000,000,000,000,000 કિલો',
    exp_problem_2: 'સમજવું મુશ્કેલ: આ સંખ્યા કેટલી મોટી છે?',
    exp_problem_3: 'સરખામણી કરવી મુશ્કેલ: કયું મોટું છે - પૃથ્વી કે યુરેનસ?',
    exp_intro_solution: 'ઉકેલ: સંખ્યાઓને ટૂંકા, સરળ સ્વરૂપમાં લખવા માટે ઘાતાંકનો ઉપયોગ કરો!',
    exp_example_title: 'વાસ્તવિક વિશ્વનું ઉદાહરણ',
    exp_example_before: 'પૃથ્વીનું વજન = 5,970,000,000,000,000,000,000,000 કિલો',
    exp_example_after: 'પૃથ્વીનું વજન = 5.97 × 10²⁴ કિલો',
    exp_example_benefit: 'વાંચવા અને સરખામણી કરવામાં ખૂબ સરળ!',
    exp_before: 'પહેલાં',
    exp_after: 'પછી',
    exp_what_are_title: 'ઘાતાંક શું છે?',
    exp_what_are_text: 'ઘાતાંક આપણને પુનરાવર્તિત ગુણાકારને સંક્ષિપ્ત રીતે લખવા દે છે.',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'પુનરાવર્તિત ગુણાકાર',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'ઘાતાંક સ્વરૂપ',
    exp_main_example: 'મુખ્ય ઉદાહરણ',
    exp_term_base: 'આધાર',
    exp_term_base_def: 'ગુણાકારમાં લેવાતી સંખ્યા',
    exp_term_base_ex: '10⁴ માં, આધાર = 10',
    exp_term_exp: 'ઘાતાંક',
    exp_term_exp_def: 'આધારને કેટલી વાર ગુણાકાર કરવો છે',
    exp_term_exp_ex: '10⁴ માં, ઘાતાંક = 4',
    exp_term_power: 'ઘાત',
    exp_term_power_def: 'સંપૂર્ણ અભિવ્યક્તિ',
    exp_term_power_ex: '10⁴ ને "10 ની ઘાત 4" તરીકે વાંચવામાં આવે છે',
    exp_key_terms: 'યાદ રાખવા યોગ્ય મુખ્ય શબ્દો:',
    exp_examples_title: 'ઉદાહરણો સાથે કામ',
    exp_conversion_text: 'જુઓ કે સંખ્યાઓને ઘાતાંક સ્વરૂપમાં કેવી રીતે બદલવામાં આવે છે:',
    exp_example: 'ઉદાહરણ',
    exp_step1: 'પગલું 1: ગુણાકાર તરીકે લખો',
    exp_step2: 'પગલું 2: ઘાતાંક સ્વરૂપમાં લખો',
    exp_base: 'આધાર',
    exp_exponent: 'ઘાતાંક',
    exp_read_as: 'વાંચો',
    exp_ex1_reading: '10 ની ઘાત 3',
    exp_ex2_reading: '3 ની ઘાત 4',
    exp_ex3_reading: '5 ઘન',
    exp_ex4_reading: '2 ની ઘાત 5',
    exp_special_title: 'વિશેષ નામો',
    exp_special_intro: 'કેટલાક ઘાતાંકોનાં વિશેષ નામો છે જેનો તમે ઘણી વાર ઉપયોગ કરશો:',
    exp_squared: 'વર્ગ',
    exp_squared_read: 'વર્ગ',
    exp_cubed: 'ઘન',
    exp_cubed_read: 'ઘન',
    exp_special_note: 'આ વિશેષ નામો ભૂમિતિમાંથી આવે છે - વર્ગ ચોરસના ક્ષેત્રફળમાંથી, ઘન ઘનના ઘનફળમાંથી!',
    exp_power_of: 'ઘાત',
    exp_fun_fact: 'રસપ્રદ તથ્ય',
    exp_practice_title: 'ઇન્ટરેક્ટિવ પ્રેક્ટિસ',
    exp_interactive_intro: 'જાતે અજમાવો! ઘાતાંક કેવી રીતે કામ કરે છે તે જોવા માટે આધાર અને ઘાતાંક બદલો:',
    exp_expanded: 'વિસ્તૃત સ્વરૂપ',
    exp_exponential_form: 'ઘાતાંક સ્વરૂપ',
    exp_result: 'પરિણામ',
    exp_reading_title: 'વાંચન',
    exp_raised_to: 'ની ઘાત',
    exp_or: 'અથવા',
    of: 'નું',
    example: 'ઉદાહરણ',
    formula: 'સૂત્ર',
    explanation: 'સ્પષ્ટતા'
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'hi' | 'gu'>(() => {
    // Load language from localStorage on initialization
    const savedLanguage = localStorage.getItem('selectedLanguage') as 'en' | 'hi' | 'gu' | null;
    return savedLanguage || 'en';
  });
  const [isTransitioning, setIsTransitioning] = useState(false);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const localizeDigitsInText = (text: string): string => {
    // For now, just return the text as-is
    // In a real implementation, this would convert digits to the appropriate script
    return text;
  };

  const formatNumber = (num: number): string => {
    return num.toString();
  };

  const handleSetLanguage = (lang: 'en' | 'hi' | 'gu') => {
    setIsTransitioning(true);
    // Save language to localStorage
    localStorage.setItem('selectedLanguage', lang);
    setTimeout(() => {
      setLanguage(lang);
      setIsTransitioning(false);
    }, 100); // Further reduced for smoother switching
  };

  const value: LanguageContextType = {
    language,
    setLanguage: handleSetLanguage,
    t,
    isTransitioning,
    localizeDigitsInText,
    formatNumber
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
