import { createContext, useContext, useState, ReactNode, useMemo } from 'react';

type SupportedLanguage = 'en' | 'hi' | 'gu';

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    whyMedianMatters: 'Why Median Matters?',
    medianMattersPoint1: 'Median provides a better measure of central tendency when dealing with outliers.',
    medianMattersPoint2: "It's less affected by extreme values compared to the mean.",
    medianMattersPoint3: 'Perfect for understanding typical values in real-world scenarios.',
    medianMattersPoint4: 'Used in economics, statistics, and data analysis worldwide.',
    proTip: 'Pro Tip!',
    proTipText: 'When analyzing data with outliers, always consider using median instead of mean for a more accurate representation of the typical value! 📏✨',
    realWorldDescription: 'See how median is used in everyday life',
    clickToExpand: 'Click to expand',
    clickToCollapse: 'Click to collapse',
    headerTitle: 'Median Tool',
    learn: 'Learn',
    practice: 'Practice',
    practiceSubtitle: 'Test your understanding of median calculations',
    realWorld: 'Real World',
    data: 'Data',
    sortedData: 'Sorted Data',
    medianLabel: 'Median',
    visual: 'Visual',
    correct: 'Correct!',
    incorrect: 'Incorrect. Try again!',
    tryAgain: 'Try Again',
    of: 'of',
    step1Title: 'Understanding Median 📊',
    step1Desc: 'Median is the middle value when data is arranged in order.',
    step1Context: 'Small dataset',
    step2Title: 'Finding median (odd count) 🔢',
    step2Desc: 'When n is odd, median is the middle value.',
    step3Title: 'Finding median (even count) ⚖️',
    step3Desc: 'When n is even, median is average of two middle values.',
    step3Context: 'Even count dataset',
    step4Title: 'Real data example 📋',
    step4Desc: 'Find median of student test scores.',
    step4Context: 'Test scores',
    definitionLabel: 'Definition',
    bulletMiddleValue: 'Median is the middle value in sorted data',
    bulletOddEven: 'For odd n: middle value, For even n: average of two middles',
    medianDefText: 'Median is the central value that divides data into two equal halves.',
    formulaLabel: 'Formula',
    formulaOdd: 'For odd n',
    formulaEven: 'For even n',
    whereN: 'where n is the number of observations',
    exampleUsingFormula: 'Example using the formula',
    givenData: 'Given data',
    sortFirst: 'First, sort the data',
    nEquals: 'n =',
    isOdd: 'n is odd',
    isEven: 'n is even',
    middlePosition: 'Middle position',
    medianIs: 'Median =',
    avgOfTwo: 'Average of two middle values',
    thereforeMedian: 'Therefore, Median =',
    tryThisQuestion: 'Try this question',
    findMedianOfData: 'Find the median of the data',
    position: 'Position',
    value: 'Value',
    ex1Title: 'Simple median',
    ex1Desc: 'Find the median of a small dataset',
    ex1Question: 'Median = ?',
    ex2Title: 'Even count median',
    ex2Desc: 'Find median when there are even number of values',
    ex2Question: 'What is the median?',
    ex3Title: 'Test scores',
    ex3Desc: 'Find median of student test scores',
    ex3Question: 'Median score = ?',
    ex4Title: 'Heights data',
    ex4Desc: 'Find the median height in cm',
    ex4Question: 'What is the median height?',
    ex5Title: 'Temperature readings',
    ex5Desc: 'Find median temperature value',
    ex5Question: 'Median temperature = ?',
    ex6Title: 'Daily sales',
    ex6Desc: 'Find median of daily sales figures',
    ex6Question: 'What is the median sales?',
    rw1Title: 'Income analysis',
    rw1Desc: 'Median income gives better picture than mean when there are outliers.',
    rw1Context: 'Monthly income in thousands',
    rw2Title: 'House prices',
    rw2Desc: 'Median price shows typical house cost, not affected by luxury homes.',
    rw2Context: 'House prices in lakhs',
    rw3Title: 'Exam performance',
    rw3Desc: 'Median score shows middle performer, useful for grading.',
    rw3Context: 'Student marks',
    rw4Title: 'Commute time',
    rw4Desc: 'Median commute time represents typical journey duration.',
    rw4Context: 'Daily commute in minutes',
    rw5Title: 'Product ratings',
    rw5Desc: 'Median rating shows central customer satisfaction level.',
    rw5Context: 'Ratings out of 5',
    rw6Title: 'Age distribution',
    rw6Desc: 'Median age divides population into two equal groups.',
    rw6Context: 'Age in years',
    question: 'Question',
    previous: 'Previous',
    next: 'Next',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset',
    submitAnswers: 'Submit answers',
    score: 'Score',
    attempts: 'Attempts',
    showSolution: 'Show solution',
    hideSolution: 'Hide solution',
    solutionSteps: 'Solution steps:',
    showHint: 'Show hint',
    hint: 'Hint',
    enterYourAnswer: 'Enter your answer',
    stepSortData: 'Step 1: Sort the data in ascending order',
    stepFindN: 'Step 2: Count the number of values (n)',
    stepCheckOddEven: 'Step 3: Check if n is odd or even',
    stepFindMiddle: 'Step 4: Find the middle value(s)',
    stepCalculateMedian: 'Step 5: Calculate median',
    hintSortFirst: 'First, arrange all values in ascending order',
    hintCountValues: 'Count total number of values',
    hintCheckOddEven: 'If count is odd, pick middle value. If even, average the two middle values',
  },
  hi: {
    whyMedianMatters: 'माध्यिका क्यों महत्वपूर्ण है?',
    medianMattersPoint1: 'आउटलायर होने पर माध्यिका केंद्रीय प्रवृत्ति का बेहतर माप देती है।',
    medianMattersPoint2: 'माध्य की तुलना में चरम मानों से कम प्रभावित होती है।',
    medianMattersPoint3: 'वास्तविक जीवन की स्थितियों में विशिष्ट मान समझने के लिए उपयुक्त।',
    medianMattersPoint4: 'अर्थशास्त्र, सांख्यिकी और डेटा विश्लेषण में उपयोग।',
    proTip: 'प्रो टिप!',
    proTipText: 'आउटलायर वाले डेटा का विश्लेषण करते समय, अधिक सटीक विशिष्ट मान हेतु माध्य के बजाय माध्यिका का प्रयोग करें! 📏✨',
    realWorldDescription: 'देखें कि दैनिक जीवन में माध्यिका कैसे उपयोग होती है',
    clickToExpand: 'विस्तार हेतु क्लिक करें',
    clickToCollapse: 'संकुचित करने हेतु क्लिक करें',
    headerTitle: 'माध्यिका उपकरण',
    learn: 'सीखें',
    practice: 'अभ्यास',
    practiceSubtitle: 'माध्यिका गणनाओं की समझ परखें',
    realWorld: 'वास्तविक दुनिया',
    data: 'डेटा',
    sortedData: 'क्रमबद्ध डेटा',
    medianLabel: 'माध्यिका',
    visual: 'दृश्य',
    correct: 'सही!',
    incorrect: 'गलत। पुनः प्रयास करें!',
    tryAgain: 'फिर प्रयास करें',
    of: 'का',
    step1Title: 'माध्यिका को समझना 📊',
    step1Desc: 'माध्यिका क्रमबद्ध डेटा का मध्य मान है।',
    step1Context: 'छोटा डेटासेट',
    step2Title: 'माध्यिका खोजना (विषम संख्या) 🔢',
    step2Desc: 'जब n विषम हो, माध्यिका मध्य मान होता है।',
    step3Title: 'माध्यिका खोजना (सम संख्या) ⚖️',
    step3Desc: 'जब n सम हो, माध्यिका दो मध्य मानों का औसत होता है।',
    step3Context: 'सम संख्या डेटासेट',
    step4Title: 'वास्तविक डेटा उदाहरण 📋',
    step4Desc: 'छात्र परीक्षा अंकों की माध्यिका खोजें।',
    step4Context: 'परीक्षा अंक',
    definitionLabel: 'परिभाषा',
    bulletMiddleValue: 'माध्यिका क्रमबद्ध डेटा का मध्य मान है',
    bulletOddEven: 'विषम n के लिए: मध्य मान, सम n के लिए: दो मध्य का औसत',
    medianDefText: 'माध्यिका वह केंद्रीय मान है जो डेटा को दो बराबर भागों में बांटता है।',
    formulaLabel: 'सूत्र',
    formulaOdd: 'विषम n के लिए',
    formulaEven: 'सम n के लिए',
    whereN: 'जहाँ n प्रेक्षणों की संख्या है',
    exampleUsingFormula: 'सूत्र का उपयोग करके उदाहरण',
    givenData: 'दिया गया डेटा',
    sortFirst: 'पहले, डेटा को क्रमबद्ध करें',
    nEquals: 'n =',
    isOdd: 'n विषम है',
    isEven: 'n सम है',
    middlePosition: 'मध्य स्थिति',
    medianIs: 'माध्यिका =',
    avgOfTwo: 'दो मध्य मानों का औसत',
    thereforeMedian: 'इसलिए, माध्यिका =',
    tryThisQuestion: 'यह प्रश्न हल करें',
    findMedianOfData: 'डेटा की माध्यिका खोजें',
    position: 'स्थिति',
    value: 'मान',
    ex1Title: 'सरल माध्यिका',
    ex1Desc: 'छोटे डेटासेट की माध्यिका खोजें',
    ex1Question: 'माध्यिका = ?',
    ex2Title: 'सम संख्या माध्यिका',
    ex2Desc: 'सम संख्या मानों की माध्यिका खोजें',
    ex2Question: 'माध्यिका क्या है?',
    ex3Title: 'परीक्षा अंक',
    ex3Desc: 'छात्र परीक्षा अंकों की माध्यिका खोजें',
    ex3Question: 'माध्यिका अंक = ?',
    ex4Title: 'ऊंचाई डेटा',
    ex4Desc: 'सेमी में माध्यिका ऊंचाई खोजें',
    ex4Question: 'माध्यिका ऊंचाई क्या है?',
    ex5Title: 'तापमान रीडिंग',
    ex5Desc: 'माध्यिका तापमान मान खोजें',
    ex5Question: 'माध्यिका तापमान = ?',
    ex6Title: 'दैनिक बिक्री',
    ex6Desc: 'दैनिक बिक्री के आंकड़ों की माध्यिका खोजें',
    ex6Question: 'माध्यिका बिक्री क्या है?',
    rw1Title: 'आय विश्लेषण',
    rw1Desc: 'माध्यिका आय आउटलायर होने पर औसत से बेहतर तस्वीर देती है।',
    rw1Context: 'हजारों में मासिक आय',
    rw2Title: 'घर की कीमतें',
    rw2Desc: 'माध्यिका कीमत विशिष्ट घर की लागत दिखाती है।',
    rw2Context: 'लाखों में घर की कीमतें',
    rw3Title: 'परीक्षा प्रदर्शन',
    rw3Desc: 'माध्यिका अंक मध्य प्रदर्शनकर्ता दिखाता है।',
    rw3Context: 'छात्र अंक',
    rw4Title: 'यात्रा समय',
    rw4Desc: 'माध्यिका यात्रा समय विशिष्ट यात्रा अवधि दर्शाता है।',
    rw4Context: 'मिनटों में दैनिक यात्रा',
    rw5Title: 'उत्पाद रेटिंग',
    rw5Desc: 'माध्यिका रेटिंग केंद्रीय ग्राहक संतुष्टि स्तर दिखाती है।',
    rw5Context: '5 में से रेटिंग',
    rw6Title: 'आयु वितरण',
    rw6Desc: 'माध्यिका आयु जनसंख्या को दो बराबर समूहों में विभाजित करती है।',
    rw6Context: 'वर्षों में आयु',
    question: 'प्रश्न',
    previous: 'पिछला',
    next: 'अगला',
    play: 'चलाएँ',
    pause: 'रोकें',
    reset: 'रीसेट',
    submitAnswers: 'उत्तर जमा करें',
    score: 'स्कोर',
    attempts: 'प्रयास',
    showSolution: 'समाधान दिखाएं',
    hideSolution: 'समाधान छुपाएं',
    solutionSteps: 'समाधान चरण:',
    showHint: 'संकेत दिखाएं',
    hint: 'संकेत',
    enterYourAnswer: 'अपना उत्तर दर्ज करें',
    stepSortData: 'चरण 1: डेटा को आरोही क्रम में क्रमबद्ध करें',
    stepFindN: 'चरण 2: मानों की संख्या (n) गिनें',
    stepCheckOddEven: 'चरण 3: जांचें कि n विषम है या सम',
    stepFindMiddle: 'चरण 4: मध्य मान खोजें',
    stepCalculateMedian: 'चरण 5: माध्यिका की गणना करें',
    hintSortFirst: 'पहले, सभी मानों को आरोही क्रम में व्यवस्थित करें',
    hintCountValues: 'कुल मानों की संख्या गिनें',
    hintCheckOddEven: 'यदि गिनती विषम है, मध्य मान चुनें। यदि सम है, दो मध्य मानों का औसत लें',
  },
  gu: {
    whyMedianMatters: 'મધ્યક કેમ મહત્વપૂર્ણ છે?',
    medianMattersPoint1: 'આઉટલાયર હોય ત્યારે મધ્યક કેન્દ્રિય પ્રવન્તીનું ઉત્તમ માપ આપે છે.',
    medianMattersPoint2: 'મધ્ય કરતાં અતિશય મૂલ્યોનો ઓછો પ્રભાવ પડે છે.',
    medianMattersPoint3: 'વાસ્તવિક પરિસ્થિતિઓમાં લક્ષણાત્મક મૂલ્યો સમજવા માટે ઉત્તમ.',
    medianMattersPoint4: 'અર્થશાસ્ત્ર, આંકડાશાસ્ત્ર અને ડેટા વિશ્લેષણમાં ઉપયોગી.',
    proTip: 'પ્રો ટીપ!',
    proTipText: 'આઉટલાયર્સ સાથેના ડેટાનું વિશ્લેષણ કરતી વખતે, સામાન્ય મૂલ્યના સચોટ પ્રતિનિધિત્વ માટે મધ્યના બદલે મધ્યકનો વિચાર કરો! 📏✨',
    realWorldDescription: 'દૈનિક જીવનમાં મધ્યક કેવી રીતે વપરાય છે તે જુઓ',
    clickToExpand: 'વિસ્તાર માટે ક્લિક કરો',
    clickToCollapse: 'સંકુચિત કરવા ક્લિક કરો',
    headerTitle: 'મધ્યક સાધન',
    learn: 'શીખો',
    practice: 'પ્રેક્ટિસ',
    practiceSubtitle: 'મધ્યક ગણતરીની સમજ પરખો',
    realWorld: 'વાસ્તવિક દુનિયા',
    data: 'ડેટા',
    sortedData: 'ક્રમબદ્ધ ડેટા',
    medianLabel: 'મધ્યક',
    visual: 'દૃશ્ય',
    correct: 'સાચું!',
    incorrect: 'ખોટું. ફરી પ્રયાસ કરો!',
    tryAgain: 'ફરીથી પ્રયાસ કરો',
    of: 'માંથી',
    step1Title: 'મધ્યક સમજવું 📊',
    step1Desc: 'મધ્યક એ ક્રમબદ્ધ ડેટામાં મધ્ય મૂલ્ય છે।',
    step1Context: 'નાનો ડેટાસેટ',
    step2Title: 'મધ્યક શોધવું (વિષમ ગણતરી) 🔢',
    step2Desc: 'જ્યારે n વિષમ હોય, મધ્યક મધ્ય મૂલ્ય છે।',
    step3Title: 'મધ્યક શોધવું (સમ ગણતરી) ⚖️',
    step3Desc: 'જ્યારે n સમ હોય, મધ્યક બે મધ્ય મૂલ્યોની સરેરાશ છે।',
    step3Context: 'સમ ગણતરી ડેટાસેટ',
    step4Title: 'વાસ્તવિક ડેટા ઉદાહરણ 📋',
    step4Desc: 'વિદ્યાર્થી પરીક્ષા ગુણનો મધ્યક શોધો।',
    step4Context: 'પરીક્ષા ગુણ',
    definitionLabel: 'વ્યાખ્યા',
    bulletMiddleValue: 'મધ્યક ક્રમબદ્ધ ડેટામાં મધ્ય મૂલ્ય છે',
    bulletOddEven: 'વિષમ n માટે: મધ્ય મૂલ્ય, સમ n માટે: બે મધ્યની સરેરાશ',
    medianDefText: 'મધ્યક એ કેન્દ્રીય મૂલ્ય છે જે ડેટાને બે સમાન ભાગોમાં વહેંચે છે।',
    formulaLabel: 'સૂત્ર',
    formulaOdd: 'વિષમ n માટે',
    formulaEven: 'સમ n માટે',
    whereN: 'જ્યાં n અવલોકનોની સંખ્યા છે',
    exampleUsingFormula: 'સૂત્રનો ઉપયોગ કરીને ઉદાહરણ',
    givenData: 'આપેલ ડેટા',
    sortFirst: 'પ્રથમ, ડેટાને ક્રમબદ્ધ કરો',
    nEquals: 'n =',
    isOdd: 'n વિષમ છે',
    isEven: 'n સમ છે',
    middlePosition: 'મધ્ય સ્થિતિ',
    medianIs: 'મધ્યક =',
    avgOfTwo: 'બે મધ્ય મૂલ્યોની સરેરાશ',
    thereforeMedian: 'તેથી, મધ્યક =',
    tryThisQuestion: 'આ પ્રશ્ન પ્રયાસ કરો',
    findMedianOfData: 'ડેટાનો મધ્યક શોધો',
    position: 'સ્થિતિ',
    value: 'મૂલ્ય',
    ex1Title: 'સરળ મધ્યક',
    ex1Desc: 'નાના ડેટાસેટનો મધ્યક શોધો',
    ex1Question: 'મધ્યક = ?',
    ex2Title: 'સમ સંખ્યા મધ્યક',
    ex2Desc: 'સમ સંખ્યા મૂલ્યોનો મધ્યક શોધો',
    ex2Question: 'મધ્યક શું છે?',
    ex3Title: 'પરીક્ષા ગુણ',
    ex3Desc: 'વિદ્યાર્થી પરીક્ષા ગુણનો મધ્યક શોધો',
    ex3Question: 'મધ્યક ગુણ = ?',
    ex4Title: 'ઊંચાઈ ડેટા',
    ex4Desc: 'સેમીમાં મધ્યક ઊંચાઈ શોધો',
    ex4Question: 'મધ્યક ઊંચાઈ શું છે?',
    ex5Title: 'તાપમાન રીડિંગ્સ',
    ex5Desc: 'મધ્યક તાપમાન મૂલ્ય શોધો',
    ex5Question: 'મધ્યક તાપમાન = ?',
    ex6Title: 'દૈનિક વેચાણ',
    ex6Desc: 'દૈનિક વેચાણ આંકડાનો મધ્યક શોધો',
    ex6Question: 'મધ્યક વેચાણ શું છે?',
    rw1Title: 'આવક વિશ્લેષણ',
    rw1Desc: 'મધ્યક આવક આઉટલાયર હોય ત્યારે સરેરાશ કરતાં સારું ચિત્ર આપે છે।',
    rw1Context: 'હજારોમાં માસિક આવક',
    rw2Title: 'ઘરની કિંમતો',
    rw2Desc: 'મધ્યક કિંમત લક્ઝરી ઘરોથી પ્રભાવિત નથી.',
    rw2Context: 'લાખોમાં ઘરની કિંમતો',
    rw3Title: 'પરીક્ષા પ્રદર્શન',
    rw3Desc: 'મધ્યક સ્કોર મધ્ય પ્રદર્શનકર્તા બતાવે છે।',
    rw3Context: 'વિદ્યાર્થી ગુણ',
    rw4Title: 'મુસાફરી સમય',
    rw4Desc: 'મધ્યક મુસાફરી સમય લાક્ષણિક પ્રવાસ સમયગાળો દર્શાવે છે।',
    rw4Context: 'મિનિટમાં દૈનિક મુસાફરી',
    rw5Title: 'ઉત્પાદન રેટિંગ્સ',
    rw5Desc: 'મધ્યક રેટિંગ કેન્દ્રીય ગ્રાહક સંતોષ સ્તર બતાવે છે।',
    rw5Context: '5 માંથી રેટિંગ્સ',
    rw6Title: 'વય વિતરણ',
    rw6Desc: 'મધ્યક વય વસ્તીને બે સમાન જૂથોમાં વિભાજિત કરે છે।',
    rw6Context: 'વર્ષોમાં વય',
    question: 'પ્રશ્ન',
    previous: 'પાછળ',
    next: 'આગળ',
    play: 'ચાલુ',
    pause: 'વિરામ',
    reset: 'રીસેટ',
    submitAnswers: 'જવાબો સબમિટ કરો',
    score: 'સ્કોર',
    attempts: 'પ્રયાસો',
    showSolution: 'ઉકેલ બતાવો',
    hideSolution: 'ઉકેલ છુપાવો',
    solutionSteps: 'ઉકેલ પગલાં:',
    showHint: 'સંકેત બતાવો',
    hint: 'સંકેત',
    enterYourAnswer: 'તમારો જવાબ દાખલ કરો',
    stepSortData: 'પગલું 1: ડેટાને ચડતા ક્રમમાં ગોઠવો',
    stepFindN: 'પગલું 2: મૂલ્યોની સંખ્યા (n) ગણો',
    stepCheckOddEven: 'પગલું 3: તપાસો કે n વિષમ છે કે સમ',
    stepFindMiddle: 'પગલું 4: મધ્ય મૂલ્ય શોધો',
    stepCalculateMedian: 'પગલું 5: મધ્યક ની ગણતરી કરો',
    hintSortFirst: 'પ્રથમ, બધા મૂલ્યોને ચડતા ક્રમમાં ગોઠવો',
    hintCountValues: 'કુલ મૂલ્યોની સંખ્યા ગણો',
    hintCheckOddEven: 'જો ગણતરી વિષમ છે, મધ્ય મૂલ્ય પસંદ કરો। જો સમ છે, બે મધ્ય મૂલ્યોની સરેરાશ લો',
  }
};

const LanguageContext = createContext<{
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  isTransitioning: boolean;
} | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('medianSelectedLanguage');
    if (saved === 'en' || saved === 'hi' || saved === 'gu') return saved;
    return 'en';
  });
  const [isTransitioning, setIsTransitioning] = useState(false);
  
  const t = useMemo(() => (key: string) => translations[language][key] ?? key, [language]);

  const setLanguagePersist = (lang: SupportedLanguage) => {
    if (lang === language) return;
    localStorage.setItem('medianSelectedLanguage', lang);
    setIsTransitioning(true);
    setTimeout(() => {
      setLanguage(lang);
      setTimeout(() => setIsTransitioning(false), 250);
    }, 120);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguagePersist, t, isTransitioning }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}






