import { createContext, useContext, useMemo, useState, ReactNode } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'gu';

type LanguageContextValue = {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  formatNumber: (n: number) => string;
  localizeDigitsInText: (text: string) => string;
  isTransitioning: boolean;
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    demo: 'Demonstration',
    practice: 'Practice',
    assessment: 'Assessment',
    header: 'Multiplication: Understanding Arrays & Repeated Addition',
    topicSubtitle: 'Learn multiplication through visual arrays, repeated addition, and mathematical properties',
    visualGridArrays: 'Visual Grid Arrays',
    repeatedAdditionTag: 'Repeated Addition',
    mathematicalPropertiesTag: 'Mathematical Properties',
    realWorld: 'Real World',
    realWorldSubtitle: 'Discover how multiplication works in everyday situations',
    prev: 'Prev',
    next: 'Next',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset',
    check: 'Check',
    submit: 'Submit',
    correct: 'Correct!',
    incorrect: 'Incorrect',
    question: 'Question',
    problem: 'Problem',
    step: 'Step',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit',
    arrays: 'Arrays',
    groups: 'Groups',
    total: 'Total',
    learn: 'Learn',
    replay: 'Replay',
    timesLabel: 'times',
    equalsLabel: 'equals',
    groupsOf: 'groups of',
    replayTip: 'Click any card to replay animations!',
    // Demonstration step titles and descriptions
    arrayTitle: 'Arrays and Groups',
    arrayDesc: 'See how multiplication creates equal groups.',
    arrayExample: '3 × 4 = 12 (3 groups of 4)',
    repeatedAddTitle: 'Repeated Addition',
    repeatedAddDesc: 'Multiplication is adding the same number multiple times.',
    repeatedAddExample: '4 + 4 + 4 = 3 × 4 = 12',
    commutativeTitle: 'Commutative Property',
    commutativeDesc: 'Order doesn\'t matter: 3 × 4 = 4 × 3.',
    commutativeExample: '3 × 4 = 4 × 3 = 12',
    zerosOnesTitle: 'Special Numbers',
    zerosOnesDesc: 'Multiplying by 0 gives 0, by 1 gives the same number.',
    zerosOnesExample: '5 × 0 = 0, 5 × 1 = 5',
    // Property badges
    commutative: 'Commutative (×)',
    associative: 'Associative (×)',
    identity: 'Identity 1',
    zero: 'Zero Property',
    distributive: 'Distributive',
    // Property tags for demonstration
    repeatedAdditionProperty: 'Repeated Addition',
    groupingProperty: 'Grouping',
    basicOperationProperty: 'Basic Operation',
    signRulesProperty: 'Sign Rules',
    integerMultiplicationProperty: 'Integer Multiplication',
    positiveNegativeRuleProperty: 'Positive × Negative = Negative',
    negativeNegativeRuleProperty: 'Negative × Negative = Positive',
    integerPropertiesProperty: 'Integer Properties',
    commutativePropertyProperty: 'Commutative Property',
    orderIndependenceProperty: 'Order Independence',
    commutativeFormulaProperty: 'a × b = b × a',
    associativePropertyProperty: 'Associative Property',
    associativeFormulaProperty: '(a × b) × c = a × (b × c)',
    footerText: 'Interactive Multiplication Learning · Visual Arrays & Mathematical Properties · Progress Tracked',
    // Integer multiplication content
    positiveNegative: 'Positive × Negative',
    positiveNegativeDesc: 'When multiplying a positive and negative integer, the result is negative.',
    positiveNegativeExample: '3 × (-4) = -12 or (-3) × 4 = -12',
    negativeNegative: 'Negative × Negative', 
    negativeNegativeDesc: 'When multiplying two negative integers, the result is positive.',
    negativeNegativeExample: '(-3) × (-4) = 12',
    associativeProperty: 'Associative Property',
    associativePropertyDesc: 'Grouping doesn\'t change the result: (a × b) × c = a × (b × c)',
    associativePropertyExample: '(2 × 3) × 4 = 2 × (3 × 4) = 24',
    distributiveProperty: 'Distributive Property',
    distributivePropertyDesc: 'a × (b + c) = (a × b) + (a × c)',
    distributivePropertyExample: '3 × (4 + 2) = (3 × 4) + (3 × 2) = 18',
    identityProperty: 'Identity Property',
    identityPropertyDesc: 'Any number multiplied by 1 equals itself.',
    identityPropertyExample: '5 × 1 = 5',
    zeroProperty: 'Zero Property',
    zeroPropertyDesc: 'Any number multiplied by 0 equals 0.',
    zeroPropertyExample: '5 × 0 = 0',
    multiplicationRules: 'Multiplication Rules',
    multiplicationRulesDesc: 'Learn the fundamental rules for multiplying integers.',
    
    // Additional UI translations
    enterAnswer: 'Enter your answer...',
    showGridHelper: 'Show Grid Helper',
    hideGridHelper: 'Hide Grid Helper',
    practicePhase: 'Practice Phase',
    assessmentPhase: 'Assessment Phase',
    visualGridHelper: 'Visual Grid Helper',
    guidedPractice: 'Guided Practice Phase',
    loading: 'Loading...',
    loadingExercise: 'Preparing your next multiplication exercise',
    errorLoading: 'Error Loading Exercises',
    reloadPage: 'Reload Page',
    tryAgain: 'Try Again',
    continue: 'Continue',
    practiceAgain: 'Practice Again',
    backToLearning: 'Back to Learning',
    overallPerformance: 'Overall Performance',
    overallAccuracy: 'Overall Accuracy',
    averageTime: 'Average Time',
    totalQuestions: 'Total Questions',
    multiplicationMastery: 'Multiplication Mastery Complete!',
    completedBothPhases: 'You\'ve completed both practice and assessment phases',
    
    // Real world applications
    gardening: 'Gardening',
    gardeningDesc: 'Planting flowers in rows and columns',
    gardeningScenario: 'You plant flowers in 3 rows with 4 flowers each. How many flowers total?',
    shopping: 'Shopping',
    shoppingDesc: 'Calculating total cost of multiple items',
    shoppingScenario: 'You buy 5 packets of cookies, each containing 8 cookies. How many cookies total?',
    cooking: 'Cooking',
    cookingDesc: 'Scaling recipes for more people',
    cookingScenario: 'A recipe serves 2 people. You need to cook for 6 people. How many times bigger?',
    sports: 'Sports',
    sportsDesc: 'Calculating team scores and statistics',
    sportsScenario: 'Each team scores 4 goals in 3 matches. How many goals total?',
    whyMultiplicationMatters: 'Why Multiplication Matters',
    fasterCalculations: 'Faster Calculations',
    fasterCalculationsDesc: 'Quick way to add the same number multiple times',
    patternRecognition: 'Pattern Recognition',
    patternRecognitionDesc: 'See patterns and relationships in numbers',
    problemSolving: 'Problem Solving',
    problemSolvingDesc: 'Essential skill for advanced math and daily life',
    
    // Demonstration step content
    step1Title: 'Understanding Multiplication Basics',
    step1Desc: 'Multiplication is repeated addition. When we multiply 3 × 4, we are adding 3 four times: 3 + 3 + 3 + 3 = 12. This can be visualized as rectangular arrays or grids.',
    step2Title: 'Multiplication as Repeated Addition',
    step2Desc: 'Every multiplication can be understood as repeated addition. 4 × 3 means "add 4 three times" or 4 + 4 + 4 = 12. This helps us understand the fundamental concept.',
    step3Title: 'Multiplication of Positive and Negative Integers',
    step3Desc: 'When multiplying integers: Positive × Positive = Positive (3 × 4 = 12), Positive × Negative = Negative (3 × -4 = -12), Negative × Positive = Negative (-3 × 4 = -12).',
    step4Title: 'Multiplication of Two Negative Integers',
    step4Desc: 'When both numbers are negative, the result is positive: (-3) × (-4) = +12. This follows the rule that "negative times negative equals positive".',
    step5Title: 'Commutative Property',
    step5Desc: 'The order of multiplication doesn\'t matter: 3 × 4 = 4 × 3 = 12. This is called the commutative property of multiplication.',
    step6Title: 'Identity and Zero Properties',
    step6Desc: 'Special multiplication rules: Any number × 1 = that number (Identity Property). Any number × 0 = 0 (Zero Property).',
    step7Title: 'Associative Property',
    step7Desc: 'When multiplying three numbers, grouping doesn\'t matter: (2 × 3) × 4 = 2 × (3 × 4) = 24. This helps in mental math calculations.',
    step8Title: 'Distributive Property',
    step8Desc: 'Multiplication distributes over addition: 3 × (4 + 2) = (3 × 4) + (3 × 2) = 12 + 6 = 18. This property is very useful in algebra.',
    keyConceptLabel: 'Key Concept:',
    visualRepresentation: 'Visual Representation',
    rowsColumns: 'rows × columns = total',
  },
  hi: {
    demo: 'प्रदर्शन',
    practice: 'अभ्यास',
    assessment: 'मूल्यांकन',
    header: 'गुणा: सरणियों और बार-बार जोड़ को समझना',
    topicSubtitle: 'दृश्य सरणियों, बार-बार जोड़ने और गणितीय गुणों के माध्यम से गुणा सीखें',
    visualGridArrays: 'दृश्य ग्रिड सरणियाँ',
    repeatedAdditionTag: 'बार-बार जमा',
    mathematicalPropertiesTag: 'गणितीय गुण',
    realWorld: 'वास्तविक जीवन',
    realWorldSubtitle: 'जानें कि गुणा रोजमर्रा की स्थितियों में कैसे काम करता है',
    prev: 'पिछला',
    next: 'अगला',
    play: 'चलाएँ',
    pause: 'रोकें',
    reset: 'रीसेट',
    check: 'जाँचें',
    submit: 'जमा करें',
    correct: 'सही!',
    question: 'प्रश्न',
    problem: 'समस्या',
    step: 'चरण',
    fullscreen: 'पूर्ण स्क्रीन',
    exitFullscreen: 'बाहर निकलें',
    arrays: 'सरणियाँ',
    groups: 'समूह',
    total: 'कुल',
    learn: 'सीखें',
    replay: 'दोबारा चलाएँ',
    timesLabel: 'गुना',
    equalsLabel: 'बराबर',
    groupsOf: 'के समूह',
    replayTip: 'एनीमेशन दोबारा देखने के लिए किसी भी कार्ड पर क्लिक करें!',
    // Demonstration step titles and descriptions
    arrayTitle: 'सरणियाँ और समूह',
    arrayDesc: 'देखें कि गुणा कैसे समान समूह बनाता है।',
    arrayExample: '३ × ४ = १२ (४ के ३ समूह)',
    repeatedAddTitle: 'बार-बार जोड़',
    repeatedAddDesc: 'गुणा एक ही संख्या को कई बार जोड़ना है।',
    repeatedAddExample: '४ + ४ + ४ = ३ × ४ = १२',
    commutativeTitle: 'क्रमविनिमेय गुणधर्म',
    commutativeDesc: 'क्रम मायने नहीं रखता: ३ × ४ = ४ × ३।',
    commutativeExample: '३ × ४ = ४ × ३ = १२',
    zerosOnesTitle: 'विशेष संख्याएँ',
    zerosOnesDesc: '० से गुणा करने पर ० मिलता है, १ से गुणा करने पर वही संख्या मिलती है।',
    zerosOnesExample: '५ × ० = ०, ५ × १ = ५',
    // Property badges
    commutative: 'क्रमविनिमेय (×)',
    associative: 'साहचर्य (×)',
    identity: 'तत्समक १',
    zero: 'शून्य गुणधर्म',
    distributive: 'वितरण',
    // Property tags for demonstration
    repeatedAdditionProperty: 'बार-बार जोड़',
    groupingProperty: 'समूहीकरण',
    basicOperationProperty: 'मूल संक्रिया',
    signRulesProperty: 'चिह्न नियम',
    integerMultiplicationProperty: 'पूर्णांक गुणा',
    positiveNegativeRuleProperty: 'धनात्मक × ऋणात्मक = ऋणात्मक',
    negativeNegativeRuleProperty: 'ऋणात्मक × ऋणात्मक = धनात्मक',
    integerPropertiesProperty: 'पूर्णांक गुणधर्म',
    commutativePropertyProperty: 'क्रमविनिमेय गुणधर्म',
    orderIndependenceProperty: 'क्रम स्वतंत्रता',
    commutativeFormulaProperty: 'a × b = b × a',
    associativePropertyProperty: 'साहचर्य गुणधर्म',
    associativeFormulaProperty: '(a × b) × c = a × (b × c)',
    footerText: 'इंटरैक्टिव गुणा सीखना · दृश्य सरणियाँ और गणितीय गुण · प्रगति ट्रैक्ड',
    // Integer multiplication content
    positiveNegative: 'धनात्मक × ऋणात्मक',
    positiveNegativeDesc: 'धनात्मक और ऋणात्मक पूर्णांक का गुणा करने पर परिणाम ऋणात्मक होता है।',
    positiveNegativeExample: '३ × (-४) = -१२ या (-३) × ४ = -१२',
    negativeNegative: 'ऋणात्मक × ऋणात्मक',
    negativeNegativeDesc: 'दो ऋणात्मक पूर्णांकों का गुणा करने पर परिणाम धनात्मक होता है।',
    negativeNegativeExample: '(-३) × (-४) = १२',
    associativeProperty: 'साहचर्य गुणधर्म',
    associativePropertyDesc: 'समूहीकरण परिणाम नहीं बदलता: (a × b) × c = a × (b × c)',
    associativePropertyExample: '(२ × ३) × ४ = २ × (३ × ४) = २४',
    distributiveProperty: 'वितरण गुणधर्म',
    distributivePropertyDesc: 'a × (b + c) = (a × b) + (a × c)',
    distributivePropertyExample: '३ × (४ + २) = (३ × ४) + (३ × २) = १८',
    identityProperty: 'तत्समक गुणधर्म',
    identityPropertyDesc: 'किसी भी संख्या का १ से गुणा करने पर वही संख्या मिलती है।',
    identityPropertyExample: '५ × १ = ५',
    zeroProperty: 'शून्य गुणधर्म',
    zeroPropertyDesc: 'किसी भी संख्या का ० से गुणा करने पर ० मिलता है।',
    zeroPropertyExample: '५ × ० = ०',
    multiplicationRules: 'गुणा के नियम',
    multiplicationRulesDesc: 'पूर्णांकों के गुणा के मूलभूत नियम सीखें।',
    
    // Additional UI translations
    enterAnswer: 'अपना उत्तर दर्ज करें...',
    showGridHelper: 'ग्रिड सहायक दिखाएं',
    hideGridHelper: 'ग्रिड सहायक छुपाएं',
    practicePhase: 'अभ्यास चरण',
    assessmentPhase: 'मूल्यांकन चरण',
    visualGridHelper: 'दृश्य ग्रिड सहायक',
    guidedPractice: 'निर्देशित अभ्यास चरण',
    loading: 'लोड हो रहा है...',
    loadingExercise: 'आपका अगला गुणा अभ्यास तैयार कर रहे हैं',
    errorLoading: 'अभ्यास लोड करने में त्रुटि',
    reloadPage: 'पृष्ठ पुनः लोड करें',
    tryAgain: 'फिर प्रयास करें',
    continue: 'जारी रखें',
    practiceAgain: 'फिर अभ्यास करें',
    backToLearning: 'सीखने पर वापस जाएं',
    overallPerformance: 'समग्र प्रदर्शन',
    overallAccuracy: 'समग्र सटीकता',
    averageTime: 'औसत समय',
    totalQuestions: 'कुल प्रश्न',
    multiplicationMastery: 'गुणा में दक्षता पूर्ण!',
    completedBothPhases: 'आपने अभ्यास और मूल्यांकन दोनों चरण पूरे कर लिए हैं',
    incorrect: 'गलत',
    
    // Real world applications
    gardening: 'बागवानी',
    gardeningDesc: 'पंक्तियों और स्तंभों में फूल लगाना',
    gardeningScenario: 'आप ३ पंक्तियों में ४-४ फूल लगाते हैं। कुल कितने फूल हैं?',
    shopping: 'खरीदारी',
    shoppingDesc: 'कई वस्तुओं की कुल लागत की गणना',
    shoppingScenario: 'आप ५ पैकेट कुकीज खरीदते हैं, हर पैकेट में ८ कुकीज हैं। कुल कितनी कुकीज?',
    cooking: 'खाना बनाना',
    cookingDesc: 'अधिक लोगों के लिए व्यंजनों का विस्तार',
    cookingScenario: 'एक रेसिपी २ लोगों के लिए है। आपको ६ लोगों के लिए बनाना है। कितनी बार बढ़ाना होगा?',
    sports: 'खेल',
    sportsDesc: 'टीम स्कोर और आंकड़ों की गणना',
    sportsScenario: 'हर टीम ३ मैचों में ४-४ गोल करती है। कुल कितने गोल?',
    whyMultiplicationMatters: 'गुणा क्यों महत्वपूर्ण है',
    fasterCalculations: 'तेज़ गणना',
    fasterCalculationsDesc: 'एक ही संख्या को कई बार जोड़ने का तेज़ तरीका',
    patternRecognition: 'पैटर्न पहचान',
    patternRecognitionDesc: 'संख्याओं में पैटर्न और संबंध देखना',
    problemSolving: 'समस्या समाधान',
    problemSolvingDesc: 'उन्नत गणित और दैनिक जीवन के लिए आवश्यक कौशल',
    
    // Demonstration step content
    step1Title: 'गुणा की मूल बातें समझना',
    step1Desc: 'गुणा बार-बार जोड़ना है। जब हम ३ × ४ करते हैं, तो हम ३ को चार बार जोड़ते हैं: ३ + ३ + ३ + ३ = १२। इसे आयताकार सरणियों या ग्रिड के रूप में देखा जा सकता है।',
    step2Title: 'बार-बार जोड़ के रूप में गुणा',
    step2Desc: 'हर गुणा को बार-बार जोड़ के रूप में समझा जा सकता है। ४ × ३ का मतलब है "४ को तीन बार जोड़ें" या ४ + ४ + ४ = १२। यह हमें मूलभूत अवधारणा समझने में मदद करता है।',
    step3Title: 'धनात्मक और ऋणात्मक पूर्णांकों का गुणा',
    step3Desc: 'पूर्णांकों का गुणा करते समय: धनात्मक × धनात्मक = धनात्मक (३ × ४ = १२), धनात्मक × ऋणात्मक = ऋणात्मक (३ × -४ = -१२), ऋणात्मक × धनात्मक = ऋणात्मक (-३ × ४ = -१२)।',
    step4Title: 'दो ऋणात्मक पूर्णांकों का गुणा',
    step4Desc: 'जब दोनों संख्याएं ऋणात्मक हों, तो परिणाम धनात्मक होता है: (-३) × (-४) = +१२। यह नियम है कि "ऋणात्मक गुना ऋणात्मक बराबर धनात्मक"।',
    step5Title: 'क्रमविनिमेय गुणधर्म',
    step5Desc: 'गुणा का क्रम मायने नहीं रखता: ३ × ४ = ४ × ३ = १२। इसे गुणा का क्रमविनिमेय गुणधर्म कहते हैं।',
    step6Title: 'तत्समक और शून्य गुणधर्म',
    step6Desc: 'विशेष गुणा नियम: कोई भी संख्या × १ = वही संख्या (तत्समक गुणधर्म)। कोई भी संख्या × ० = ० (शून्य गुणधर्म)।',
    step7Title: 'साहचर्य गुणधर्म',
    step7Desc: 'तीन संख्याओं का गुणा करते समय, समूहीकरण मायने नहीं रखता: (२ × ३) × ४ = २ × (३ × ४) = २४। यह मानसिक गणित में सहायक है।',
    step8Title: 'वितरण गुणधर्म',
    step8Desc: 'गुणा जोड़ पर वितरित होता है: ३ × (४ + २) = (३ × ४) + (३ × २) = १२ + ६ = १८। यह गुणधर्म बीजगणित में बहुत उपयोगी है।',
    keyConceptLabel: 'मुख्य अवधारणा:',
    visualRepresentation: 'दृश्य प्रतिनिधित्व',
    rowsColumns: 'पंक्तियाँ × स्तंभ = कुल',
  },
  gu: {
    demo: 'પ્રદર્શન',
    practice: 'અભ્યાસ',
    assessment: 'મૂલ્યાંકન',
    header: 'ગુણાકાર: એરે અને પુનરાવર્તિત ઉમેરાને સમજવું',
    topicSubtitle: 'દ્રશ્ય એરે, પુનરાવર્તિત ઉમેરા અને ગાણિતિક ગુણધર્મો દ્વારા ગુણાકાર શીખો',
    visualGridArrays: 'દ્રશ્ય ગ્રિડ એરે',
    repeatedAdditionTag: 'પુનરાવર્તિત ઉમેરો',
    mathematicalPropertiesTag: 'ગાણિતિક ગુણધર્મો',
    realWorld: 'વાસ્તવિક દુનિયા',
    realWorldSubtitle: 'જાણો કે ગુણાકાર રોજિંદા પરિસ્થિતિઓમાં કેવી રીતે કામ કરે છે',
    prev: 'પાછળ',
    next: 'આગળ',
    play: 'ચાલુ',
    pause: 'વિરામ',
    reset: 'રીસેટ',
    check: 'ચેક',
    submit: 'સબમિટ',
    correct: 'સારું!',
    question: 'પ્રશ્ન',
    problem: 'સમસ્યા',
    step: 'પગલું',
    fullscreen: 'ફુલસ્ક્રીન',
    exitFullscreen: 'બહાર',
    arrays: 'એરે',
    groups: 'જૂથો',
    total: 'કુલ',
    learn: 'શીખો',
    replay: 'પુનઃ ચલાવો',
    timesLabel: 'વખત',
    equalsLabel: 'બરાબર',
    groupsOf: 'ના જૂથો',
    replayTip: 'એનિમેશન ફરીથી જોવા માટે કોઈપણ કાર્ડ પર ક્લિક કરો!',
    // Demonstration step titles and descriptions
    arrayTitle: 'એરે અને જૂથો',
    arrayDesc: 'જુઓ કે ગુણાકાર કેવી રીતે સમાન જૂથો બનાવે છે।',
    arrayExample: '૩ × ૪ = ૧૨ (૪ ના ૩ જૂથો)',
    repeatedAddTitle: 'પુનરાવર્તિત ઉમેરો',
    repeatedAddDesc: 'ગુણાકાર એ જ નંબરને ઘણી વખત ઉમેરવાનું છે।',
    repeatedAddExample: '૪ + ૪ + ૪ = ૩ × ૪ = ૧૨',
    commutativeTitle: 'ક્રમવિનિમય ગુણધર્મ',
    commutativeDesc: 'ક્રમ મહત્વનો નથી: ૩ × ૪ = ૪ × ૩।',
    commutativeExample: '૩ × ૪ = ૪ × ૩ = ૧૨',
    zerosOnesTitle: 'વિશેષ નંબરો',
    zerosOnesDesc: '૦ સાથે ગુણાકાર ૦ આપે છે, ૧ સાથે ગુણાકાર તે જ નંબર આપે છે।',
    zerosOnesExample: '૫ × ૦ = ૦, ૫ × ૧ = ૫',
    // Property badges
    commutative: 'ક્રમવિનિમય (×)',
    associative: 'સહયોગી (×)',
    identity: 'ઓળખ ૧',
    zero: 'શૂન્ય ગુણધર્મ',
    distributive: 'વિતરણ',
    // Property tags for demonstration
    repeatedAdditionProperty: 'પુનરાવર્તિત ઉમેરો',
    groupingProperty: 'જૂથીકરણ',
    basicOperationProperty: 'મૂળભૂત ક્રિયા',
    signRulesProperty: 'ચિહ્ન નિયમો',
    integerMultiplicationProperty: 'પૂર્ણાંક ગુણાકાર',
    positiveNegativeRuleProperty: 'હકારાત્મક × નકારાત્મક = નકારાત્મક',
    negativeNegativeRuleProperty: 'નકારાત્મક × નકારાત્મક = હકારાત્મક',
    integerPropertiesProperty: 'પૂર્ણાંક ગુણધર્મો',
    commutativePropertyProperty: 'ક્રમવિનિમય ગુણધર્મ',
    orderIndependenceProperty: 'ક્રમ સ્વતંત્રતા',
    commutativeFormulaProperty: 'a × b = b × a',
    associativePropertyProperty: 'સહયોગી ગુણધર્મ',
    associativeFormulaProperty: '(a × b) × c = a × (b × c)',
    footerText: 'ઇન્ટરેક્ટિવ ગુણાકાર શિક્ષણ · દૃશ્ય એરે અને ગાણિતિક ગુણધર્મો · પ્રગતિ ટ્રેક કરવામાં આવે છે',
    // Integer multiplication content
    positiveNegative: 'હકારાત્મક × નકારાત્મક',
    positiveNegativeDesc: 'હકારાત્મક અને નકારાત્મક પૂર્ણાંકનો ગુણાકાર કરતાં પરિણામ નકારાત્મક હોય છે.',
    positiveNegativeExample: '૩ × (-૪) = -૧૨ અથવા (-૩) × ૪ = -૧૨',
    negativeNegative: 'નકારાત્મક × નકારાત્મક',
    negativeNegativeDesc: 'બે નકારાત્મક પૂર્ણાંકનો ગુણાકાર કરતાં પરિણામ હકારાત્મક હોય છે.',
    negativeNegativeExample: '(-૩) × (-૪) = ૧૨',
    associativeProperty: 'સહયોગી ગુણધર્મ',
    associativePropertyDesc: 'જૂથીકરણ પરિણામ બદલતું નથી: (a × b) × c = a × (b × c)',
    associativePropertyExample: '(૨ × ૩) × ૪ = ૨ × (૩ × ૪) = ૨૪',
    distributiveProperty: 'વિતરણ ગુણધર્મ',
    distributivePropertyDesc: 'a × (b + c) = (a × b) + (a × c)',
    distributivePropertyExample: '૩ × (૪ + ૨) = (૩ × ૪) + (૩ × ૨) = ૧૮',
    identityProperty: 'ઓળખ ગુણધર્મ',
    identityPropertyDesc: 'કોઈપણ નંબરનો ૧ સાથે ગુણાકાર તે જ નંબર આપે છે.',
    identityPropertyExample: '૫ × ૧ = ૫',
    zeroProperty: 'શૂન્ય ગુણધર્મ',
    zeroPropertyDesc: 'કોઈપણ નંબરનો ૦ સાથે ગુણાકાર ૦ આપે છે.',
    zeroPropertyExample: '૫ × ૦ = ૦',
    multiplicationRules: 'ગુણાકારના નિયમો',
    multiplicationRulesDesc: 'પૂર્ણાંકોના ગુણાકારના મૂળभૂત નિયમો શીખો.',
    
    // Additional UI translations
    enterAnswer: 'તમારો જવાબ દાખલ કરો...',
    showGridHelper: 'ગ્રિડ સહાયક બતાવો',
    hideGridHelper: 'ગ્રિડ સહાયક છુપાવો',
    practicePhase: 'અભ્યાસ તબક્કો',
    assessmentPhase: 'મૂલ્યાંકન તબક્કો',
    visualGridHelper: 'દ્રશ્ય ગ્રિડ સહાયક',
    guidedPractice: 'માર્ગદર્શિત અભ્યાસ તબક્કો',
    loading: 'લોડ થઈ રહ્યું છે...',
    loadingExercise: 'તમારો આગલો ગુણાકાર અભ્યાસ તૈયાર કરી રહ્યા છીએ',
    errorLoading: 'અભ્યાસ લોડ કરવામાં ભૂલ',
    reloadPage: 'પેજ ફરીથી લોડ કરો',
    tryAgain: 'ફરી પ્રયત્ન કરો',
    continue: 'ચાલુ રાખો',
    practiceAgain: 'ફરી અભ્યાસ કરો',
    backToLearning: 'શીખવા પર પાછા જાઓ',
    overallPerformance: 'એકંદર પ્રદર્શન',
    overallAccuracy: 'એકંદર ચોકસાઈ',
    averageTime: 'સરેરાશ સમય',
    totalQuestions: 'કુલ પ્રશ્નો',
    multiplicationMastery: 'ગુણાકારમાં નિપુણતા પૂર્ણ!',
    completedBothPhases: 'તમે અભ્યાસ અને મૂલ્યાંકન બંને તબક્કા પૂર્ણ કર્યા છે',
    incorrect: 'ખોટું',
    
    // Real world applications
    gardening: 'બાગકામ',
    gardeningDesc: 'પંક્તિઓ અને કૉલમમાં ફૂલો વાવવા',
    gardeningScenario: 'તમે ૩ પંક્તિઓમાં ૪-૪ ફૂલો વાવો છો. કુલ કેટલા ફૂલો છે?',
    shopping: 'ખરીદારી',
    shoppingDesc: 'અનેક વસ્તુઓની કુલ કિંમતની ગણતરી',
    shoppingScenario: 'તમે ૫ પેકેટ કૂકીઝ ખરીદો છો, દરેક પેકેટમાં ૮ કૂકીઝ છે. કુલ કેટલી કૂકીઝ?',
    cooking: 'રસોઈ',
    cookingDesc: 'વધુ લોકો માટે રેસિપીનું માપ વધારવું',
    cookingScenario: 'એક રેસિપી ૨ લોકો માટે છે. તમારે ૬ લોકો માટે બનાવવું છે. કેટલા વખત વધારવું પડશે?',
    sports: 'રમતગમત',
    sportsDesc: 'ટીમ સ્કોર અને આંકડાઓની ગણતરી',
    sportsScenario: 'દરેક ટીમ ૩ મેચમાં ૪-૪ ગોલ કરે છે. કુલ કેટલા ગોલ?',
    whyMultiplicationMatters: 'ગુણાકાર કેમ મહત્વનું છે',
    fasterCalculations: 'ઝડપી ગણતરી',
    fasterCalculationsDesc: 'એક જ નંબરને ઘણી વાર ઉમેરવાની ઝડપી રીત',
    patternRecognition: 'પેટર્ન ઓળખ',
    patternRecognitionDesc: 'નંબરોમાં પેટર્ન અને સંબંધો જોવા',
    problemSolving: 'સમસ્યા ઉકેલ',
    problemSolvingDesc: 'અદ્યતન ગણિત અને દૈનિક જીવન માટે જરૂરી કૌશલ્ય',
    
    // Demonstration step content
    step1Title: 'ગુણાકારની મૂળભૂત બાબતો સમજવી',
    step1Desc: 'ગુણાકાર એ પુનરાવર્તિત ઉમેરો છે. જ્યારે આપણે ૩ × ૪ કરીએ છીએ, તો આપણે ૩ ને ચાર વખત ઉમેરીએ છીએ: ૩ + ૩ + ૩ + ૩ = ૧૨. આને લંબચોરસ એરે અથવા ગ્રિડ તરીકે જોઈ શકાય છે.',
    step2Title: 'પુનરાવર્તિત ઉમેરા તરીકે ગુણાકાર',
    step2Desc: 'દરેક ગુણાકારને પુનરાવર્તિત ઉમેરા તરીકે સમજી શકાય છે. ૪ × ૩ નો અર્થ છે "૪ ને ત્રણ વખત ઉમેરો" અથવા ૪ + ૪ + ૪ = ૧૨. આ આપણને મૂળભૂત ખ્યાલ સમજવામાં મદદ કરે છે.',
    step3Title: 'હકારાત્મક અને નકારાત્મક પૂર્ણાંકોનો ગુણાકાર',
    step3Desc: 'પૂર્ણાંકોનો ગુણાકાર કરતી વખતે: હકારાત્મક × હકારાત્મક = હકારાત્મક (૩ × ૪ = ૧૨), હકારાત્મક × નકારાત્મક = નકારાત્મક (૩ × -૪ = -૧૨), નકારાત્મક × હકારાત્મક = નકારાત્મક (-૩ × ૪ = -૧૨).',
    step4Title: 'બે નકારાત્મક પૂર્ણાંકોનો ગુણાકાર',
    step4Desc: 'જ્યારે બંને નંબરો નકારાત્મક હોય, તો પરિણામ હકારાત્મક હોય છે: (-૩) × (-૪) = +૧૨. આ નિયમ છે કે "નકારાત્મક ગુણાકાર નકારાત્મક બરાબર હકારાત્મક".',
    step5Title: 'ક્રમવિનિમય ગુણધર્મ',
    step5Desc: 'ગુણાકારનો ક્રમ મહત્વનો નથી: ૩ × ૪ = ૪ × ૩ = ૧૨. આને ગુણાકારનો ક્રમવિનિમય ગુણધર્મ કહે છે.',
    step6Title: 'ઓળખ અને શૂન્ય ગુણધર્મ',
    step6Desc: 'વિશેષ ગુણાકાર નિયમો: કોઈપણ નંબર × ૧ = તે જ નંબર (ઓળખ ગુણધર્મ). કોઈપણ નંબર × ૦ = ૦ (શૂન્ય ગુણધર્મ).',
    step7Title: 'સહયોગી ગુણધર્મ',
    step7Desc: 'ત્રણ નંબરોનો ગુણાકાર કરતી વખતે, જૂથીકરણ મહત્વનું નથી: (૨ × ૩) × ૪ = ૨ × (૩ × ૪) = ૨૪. આ માનસિક ગણિતમાં મદદગાર છે.',
    step8Title: 'વિતરણ ગુણધર્મ',
    step8Desc: 'ગુણાકાર ઉમેરા પર વિતરિત થાય છે: ૩ × (૪ + ૨) = (૩ × ૪) + (૩ × ૨) = ૧૨ + ૬ = ૧૮. આ ગુણધર્મ બીજગણિતમાં ખૂબ ઉપયોગી છે.',
    keyConceptLabel: 'મુખ્ય ખ્યાલ:',
    visualRepresentation: 'દ્રશ્ય પ્રતિનિધિત્વ',
    rowsColumns: 'પંક્તિઓ × સ્તંભો = કુલ',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<SupportedLanguage>('en');
  const [isTransitioning, setIsTransitioning] = useState(false);
  const t = useMemo(() => (key: string) => translations[language][key] ?? key, [language]);

  const digitMaps: Record<SupportedLanguage, Record<string, string>> = {
    en: { '0': '0', '1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9' },
    hi: { '0': '०', '1': '१', '2': '२', '3': '३', '4': '४', '5': '५', '6': '६', '7': '७', '8': '८', '9': '९' },
    gu: { '0': '૦', '1': '૧', '2': '૨', '3': '૩', '4': '૪', '5': '૫', '6': '૬', '7': '૭', '8': '૮', '9': '૯' },
  };

  const formatNumber = (n: number) => String(n).replace(/[0-9]/g, (d) => digitMaps[language][d]);
  const localizeDigitsInText = (text: string) => text.replace(/[0-9]/g, (d) => digitMaps[language][d]);

  // Enhanced setLanguage with transition animation
  const setLanguageWithAnimation = (lang: SupportedLanguage) => {
    if (lang === language) return;
    
    setIsTransitioning(true);
    
    // Add a slight delay to show the transition effect
    setTimeout(() => {
      setLanguage(lang);
      setTimeout(() => {
        setIsTransitioning(false);
      }, 300); // Animation duration
    }, 150);
  };

  const value = useMemo(() => ({ 
    language, 
    setLanguage: setLanguageWithAnimation, 
    t, 
    formatNumber, 
    localizeDigitsInText, 
    isTransitioning 
  }), [language, t, formatNumber, localizeDigitsInText, isTransitioning]);
  
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}