import { createContext, useContext, useMemo, useState, ReactNode, useEffect } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'gu';

type LanguageContextValue = {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  formatNumber: (n: number) => string;
  localizeDigitsInText: (text: string) => string;
  isTransitioning: boolean;
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    learn: 'Learn',
    demo: 'Demonstration',
    practice: 'Practice',
    assessment: 'Assessment',
    header: 'Division of Integers: Properties & Operations',
    topicSubtitle: '1.4 Division of Integers & 1.5 Properties of Division',
    realWorld: 'Real World',
    realWorldSubtitle: 'Discover how integer division works in everyday situations',
    prev: 'Prev',
    next: 'Next',
    startLabel: 'Start',
    changeLabel: 'Change',
    finalLabel: 'Final',
    upLabel: 'Up',
    downLabel: 'Down',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset',
    check: 'Check',
    submit: 'Submit',
    correct: 'Correct!',
    tryAgain: 'Try again',
    question: 'Question',
    problem: 'Problem',
    step: 'Step',
    mode: 'Mode',
    attempted: 'Attempted',
    skipped: 'Skipped',
    accuracy: 'Accuracy',
    questionsOverview: 'Questions Overview',
    incorrect: 'Incorrect',
    current: 'Current',
    skip: 'Skip',
    emptyAnswer: 'Please enter an answer',
    whitespaceAnswer: 'Answer cannot be just spaces',
    invalidNumber: 'Please enter a valid number',
    enterInteger: 'Enter integer',
    checking: 'Checking...',
    completed: 'Completed',
    attempts: 'Attempts',
    hint: 'Hint',
    divisionTip: 'Remember: Division is the inverse of multiplication',
    firstTry: 'First try!',
    wellDone: 'Well done!',
    practice_q1: 'Evaluate: 12 ÷ 3',
    practice_q2: 'Evaluate: (-15) ÷ 5',
    practice_q3: 'Evaluate: 18 ÷ (-6)',
    practice_q4: 'Evaluate: (-24) ÷ (-4)',
    practice_q5: 'Evaluate: 0 ÷ 7',
    practice_q6: 'Evaluate: 35 ÷ (-7)',
    assess_q1: 'Compute: (-21) ÷ 3',
    assess_q2: 'Compute: 28 ÷ (-4)',
    assess_q3: 'Compute: (-36) ÷ (-9)',
    assess_q4: 'Compute: 0 ÷ (-8)',
    assess_q5: 'Compute: 45 ÷ 5',
    assess_q6: 'Compute: (-56) ÷ 7',
    assessmentComplete: 'Assessment Complete!',
    detailedResults: 'Detailed Results',
    totalQuestions: 'Total Questions',
    points: 'Points',
    reviewAnswers: 'Review Answers',
    backToResults: 'Back to Results',
    correctAnswer: 'Correct Answer',
    yourAnswer: 'Your Answer',
    retakeAssessment: 'Retake Assessment',
    avgTime: 'Avg Time',
    suggestions: 'Suggestions',
    suggestMorePractice: 'Practice more division operations',
    suggestSpeedUp: 'Work on improving calculation speed',
    suggestCompleteAll: 'Try to attempt all questions',
    // Division-specific terms
    dividend: 'Dividend',
    divisor: 'Divisor', 
    quotient: 'Quotient',
    remainder: 'Remainder',
    division: 'Division',
    // Division demonstration steps
    basicDivisionTitle: 'Basic Division',
    basicDivisionDesc: 'Learn fundamental division concepts with positive integers. Understanding how division splits numbers into equal groups.',
    basicDivisionExample: '12 ÷ 3 = 4',
    negativeDivisionTitle: 'Division with Negative Numbers',
    negativeDivisionDesc: 'Master division rules with negative integers. Learn when results are positive or negative.',
    negativeDivisionExample: '(-15) ÷ 5 = -3, (-12) ÷ (-4) = 3',
    zeroDivisionTitle: 'Division by Zero & Special Cases',
    zeroDivisionDesc: 'Understand why division by zero is undefined and how zero behaves in division operations.',
    zeroDivisionExample: '0 ÷ 7 = 0, 7 ÷ 0 = undefined',
    divisionPropertiesTitle: 'Properties of Division',
    divisionPropertiesDesc: 'Explore mathematical properties of division: commutative, associative, and identity properties.',
    divisionPropertiesExample: '12 ÷ 3 ≠ 3 ÷ 12',
    distributiveTitle: 'Distributive Property',
    distributiveDesc: 'Learn how division distributes over addition and subtraction operations.',
    
    // Division demonstration steps for step-by-step learning
    sharingSweetsTitle: 'Sharing Sweets Equally',
    sharingSweetsDesc: 'You have 12 sweets to share equally among 3 friends. How many sweets does each friend get?',
    sharingSweetsExample: '12 ÷ 3 = 4 sweets per friend',
    
    temperatureDivisionTitle: 'Temperature Division',
    temperatureDivisionDesc: 'Temperature dropped 20°C over 4 days. What was the average daily drop?',
    temperatureDivisionExample: '(-20) ÷ 4 = -5°C per day',
    
    businessProfitTitle: 'Business Profit Division',
    businessProfitDesc: 'A business lost ₹800 over 4 months. What was the average monthly loss?',
    businessProfitExample: '(-800) ÷ 4 = -₹200 per month',
    
    groupingObjectsTitle: 'Grouping Objects',
    groupingObjectsDesc: 'Division shows us how to group items equally or find how many groups we can make.',
    groupingObjectsExample: '15 ÷ 5 = 3 groups of 5 items each',
    
    divisionPropertiesStepTitle: 'Division Properties Summary',
    divisionPropertiesStepDesc: 'Understanding key properties: Division is not commutative, not associative, but follows distributive property over addition.',
    divisionPropertiesStepExample: '12 ÷ 3 ≠ 3 ÷ 12 (4 ≠ 0.25)',
    distributiveExample: '(15 + 9) ÷ 3 = (15 ÷ 3) + (9 ÷ 3) = 5 + 3 = 8',
    // Property badges for division
    identity: 'Identity (÷1)',
    zero_property: 'Zero Property',
    sign_rule: 'Sign Rules',
    not_commutative: 'Not Commutative',
    not_associative: 'Not Associative',
    distributive_over_addition: 'Distributive',
    session_complete: 'Session Complete!',
    session_summary: 'Here\'s your complete session summary',
    total_questions: 'Total Questions',
    correct_answers: 'Correct Answers',
    incorrect_answers: 'Incorrect Answers',
    skipped_questions: 'Skipped Questions',
    final_grade: 'Final Grade',
    accuracy_rate: 'Accuracy Rate',
    avg_time_per_question: 'Avg Time/Question',
    question_review: 'Question by Question Review',
    start_new_session: 'Start New Session',
    not_attempted: 'Not Attempted',
    previous: 'Previous',
    hideAnswer: 'Hide Answer',
    showAnswer: 'Show Answer',
    notAttempt: 'Not Attempt',
    guidedPractice: 'Guided Practice',
    knowledgeAssessment: 'Knowledge Assessment',
    interactiveLearning: 'Interactive learning with immediate feedback and comprehensive assessment',
  },
  hi: {
    learn: 'सीखें',
    demo: 'प्रदर्शन',
    practice: 'अभ्यास',
    assessment: 'मूल्यांकन',
    header: 'पूर्णांकों का भाग: गुण और संक्रियाएं',
    topicSubtitle: '१.४ पूर्णांकों का भाग और १.५ भाग के गुण',
    realWorld: 'वास्तविक जीवन',
    realWorldSubtitle: 'जानें कि पूर्णांकों का भाग रोजमर्रा की स्थितियों में कैसे काम करता है',
    prev: 'पिछला',
    next: 'अगला',
    play: 'चलाएँ',
    pause: 'रोकें',
    reset: 'रीसेट',
    check: 'जाँचें',
    submit: 'जमा करें',
    correct: 'सही!',
    tryAgain: 'फिर प्रयास करें',
    question: 'प्रश्न',
    problem: 'समस्या',
    step: 'चरण',
    mode: 'मोड',
    attempted: 'प्रयास किया',
    skipped: 'छोड़ा गया',
    accuracy: 'सटीकता',
    questionsOverview: 'प्रश्न अवलोकन',
    incorrect: 'गलत',
    current: 'वर्तमान',
    skip: 'छोड़ें',
    emptyAnswer: 'कृपया एक उत्तर दर्ज करें',
    whitespaceAnswer: 'उत्तर केवल खाली स्थान नहीं हो सकता',
    invalidNumber: 'कृपया एक वैध संख्या दर्ज करें',
    enterInteger: 'पूर्णांक दर्ज करें',
    checking: 'जाँच रहे हैं...',
    completed: 'पूर्ण',
    attempts: 'प्रयास',
    hint: 'संकेत',
    divisionTip: 'याद रखें: भाग गुणा का व्युत्क्रम है',
    firstTry: 'पहली कोशिश!',
    wellDone: 'बहुत बढ़िया!',
    practice_q1: 'मूल्यांकन करें: १२ ÷ ३',
    practice_q2: 'मूल्यांकन करें: (-१५) ÷ ५',
    practice_q3: 'मूल्यांकन करें: १८ ÷ (-६)',
    practice_q4: 'मूल्यांकन करें: (-२४) ÷ (-४)',
    practice_q5: 'मूल्यांकन करें: ० ÷ ७',
    practice_q6: 'मूल्यांकन करें: ३५ ÷ (-७)',
    assess_q1: 'गणना करें: (-२१) ÷ ३',
    assess_q2: 'गणना करें: २८ ÷ (-४)',
    assess_q3: 'गणना करें: (-३६) ÷ (-९)',
    assess_q4: 'गणना करें: ० ÷ (-८)',
    assess_q5: 'गणना करें: ४५ ÷ ५',
    assess_q6: 'गणना करें: (-५६) ÷ ७',
    assessmentComplete: 'मूल्यांकन पूर्ण!',
    detailedResults: 'विस्तृत परिणाम',
    totalQuestions: 'कुल प्रश्न',
    points: 'अंक',
    reviewAnswers: 'उत्तर समीक्षा',
    backToResults: 'परिणाम पर वापस',
    correctAnswer: 'सही उत्तर',
    yourAnswer: 'आपका उत्तर',
    retakeAssessment: 'पुनः मूल्यांकन',
    avgTime: 'औसत समय',
    suggestions: 'सुझाव',
    suggestMorePractice: 'भाग की संक्रियाओं का अधिक अभ्यास करें',
    suggestSpeedUp: 'गणना की गति में सुधार पर काम करें',
    suggestCompleteAll: 'सभी प्रश्नों का प्रयास करने की कोशिश करें',
    // Division-specific terms
    dividend: 'भाज्य',
    divisor: 'भाजक',
    quotient: 'भागफल',
    remainder: 'शेषफल',
    division: 'भाग',
    // Division demonstration steps
    basicDivisionTitle: 'मूलभूत भाग',
    basicDivisionDesc: 'धनात्मक पूर्णांकों के साथ मौलिक भाग अवधारणाएं सीखें। समझें कि भाग संख्याओं को समान समूहों में कैसे बांटता है।',
    basicDivisionExample: '१२ ÷ ३ = ४',
    negativeDivisionTitle: 'ऋणात्मक संख्याओं के साथ भाग',
    negativeDivisionDesc: 'ऋणात्मक पूर्णांकों के साथ भाग नियमों में महारत हासिल करें। सीखें कि परिणाम कब धनात्मक या ऋणात्मक होते हैं।',
    negativeDivisionExample: '(-१५) ÷ ५ = -३, (-१२) ÷ (-४) = ३',
    zeroDivisionTitle: 'शून्य से भाग और विशेष मामले',
    zeroDivisionDesc: 'समझें कि शून्य से भाग क्यों अपरिभाषित है और भाग संक्रियाओं में शून्य कैसे व्यवहार करता है।',
    zeroDivisionExample: '० ÷ ७ = ०, ७ ÷ ० = अपरिभाषित',
    divisionPropertiesTitle: 'भाग के गुण',
    divisionPropertiesDesc: 'भाग के गणितीय गुणों का अन्वेषण करें: क्रमविनिमेय, साहचर्य, और तत्समक गुण।',
    divisionPropertiesExample: '१२ ÷ ३ ≠ ३ ÷ १२',
    distributiveTitle: 'वितरण गुण',
    distributiveDesc: 'सीखें कि भाग योग और व्यवकलन संक्रियाओं पर कैसे वितरित होता है।',
    
    // Division demonstration steps for step-by-step learning
    sharingSweetsTitle: 'मिठाई समान रूप से बांटना',
    sharingSweetsDesc: 'आपके पास 12 मिठाई हैं जो 3 दोस्तों में समान रूप से बांटनी हैं। हर दोस्त को कितनी मिठाई मिलेगी?',
    sharingSweetsExample: '12 ÷ 3 = प्रत्येक मित्र को 4 मिठाई',
    
    temperatureDivisionTitle: 'तापमान विभाजन',
    temperatureDivisionDesc: '4 दिनों में तापमान 20°C गिरा। दैनिक औसत गिरावट कितनी थी?',
    temperatureDivisionExample: '(-20) ÷ 4 = प्रति दिन -5°C',
    
    businessProfitTitle: 'व्यापारिक लाभ विभाजन',
    businessProfitDesc: 'एक व्यापार में 4 महीनों में ₹800 की हानि हुई। औसत मासिक हानि कितनी थी?',
    businessProfitExample: '(-800) ÷ 4 = प्रति महीने -₹200',
    
    groupingObjectsTitle: 'वस्तुओं का समूहीकरण',
    groupingObjectsDesc: 'भाग हमें दिखाता है कि वस्तुओं को समान रूप से कैसे समूहीकृत करें या कितने समूह बना सकते हैं।',
    groupingObjectsExample: '15 ÷ 5 = 5 वस्तुओं के 3 समूह',
    
    divisionPropertiesStepTitle: 'भाग गुण सारांश',
    divisionPropertiesStepDesc: 'मुख्य गुणों को समझना: भाग क्रमविनिमेय नहीं है, साहचर्य नहीं है, लेकिन योग पर वितरण गुण का पालन करता है।',
    divisionPropertiesStepExample: '12 ÷ 3 ≠ 3 ÷ 12 (4 ≠ 0.25)',
    distributiveExample: '(१५ + ९) ÷ ३ = (१५ ÷ ३) + (९ ÷ ३) = ५ + ३ = ८',
    // Property badges for division
    identity: 'तत्समक (÷१)',
    zero_property: 'शून्य गुण',
    sign_rule: 'चिह्न नियम',
    not_commutative: 'क्रमविनिमेय नहीं',
    not_associative: 'साहचर्य नहीं',
    distributive_over_addition: 'वितरण',
    session_complete: 'सत्र पूर्ण हो गया!',
    session_summary: 'यहाँ आपके सत्र का पूरा सारांश है',
    total_questions: 'कुल प्रश्न',
    correct_answers: 'सही उत्तर',
    incorrect_answers: 'गलत उत्तर',
    skipped_questions: 'छोड़े गए प्रश्न',
    final_grade: 'अंतिम ग्रेड',
    accuracy_rate: 'सटीकता दर',
    avg_time_per_question: 'औसत समय/प्रश्न',
    question_review: 'प्रश्न दर प्रश्न समीक्षा',
    start_new_session: 'नया सत्र शुरू करें',
    not_attempted: 'प्रयास नहीं किया',
    previous: 'पिछला',
    hideAnswer: 'उत्तर छुपाएं',
    showAnswer: 'उत्तर दिखाएं',
    notAttempt: 'प्रयास नहीं',
    guidedPractice: 'निर्देशित अभ्यास',
    knowledgeAssessment: 'ज्ञान मूल्यांकन',
    interactiveLearning: 'तत्काल प्रतिक्रिया और व्यापक मूल्यांकन के साथ इंटरैक्टिव शिक्षा',
  },
  gu: {
    learn: 'શીખો',
    demo: 'પ્રદર્શન',
    practice: 'અભ્યાસ',
    assessment: 'મૂલ્યાંકન',
    header: 'પૂર્ણાંકોનું ભાગાકાર: ગુણધર્મો અને ક્રિયાઓ',
    topicSubtitle: '૧.૪ પૂર્ણાંકોનું ભાગાકાર અને ૧.૫ ભાગાકારના ગુણધર્મો',
    realWorld: 'વાસ્તવિક દુનિયા',
    realWorldSubtitle: 'જાણો કે પૂર્ણાંકોનું ભાગાકાર રોજિંદા પરિસ્થિતિઓમાં કેવી રીતે કામ કરે છે',
    prev: 'પાછળ',
    next: 'આગળ',
    play: 'ચાલુ',
    pause: 'વિરામ',
    reset: 'રીસેટ',
    check: 'ચેક',
    submit: 'સબમિટ',
    correct: 'સારું!',
    tryAgain: 'ફરી પ્રયત્ન કરો',
    question: 'પ્રશ્ન',
    problem: 'સમસ્યા',
    step: 'પગલું',
    mode: 'મોડ',
    attempted: 'પ્રયાસ કર્યો',
    skipped: 'છોડ્યું',
    accuracy: 'ચોકસાઈ',
    questionsOverview: 'પ્રશ્નોની ઝાંખી',
    incorrect: 'ખોટું',
    current: 'વર્તમાન',
    skip: 'છોડો',
    emptyAnswer: 'કૃપા કરીને જવાબ દાખલ કરો',
    whitespaceAnswer: 'જવાબ ફક્ત ખાલી જગ્યા હોઈ શકે નહીં',
    invalidNumber: 'કૃપા કરીને માન્ય સંખ્યા દાખલ કરો',
    enterInteger: 'પૂર્ણાંક દાખલ કરો',
    checking: 'તપાસી રહ્યાં છીએ...',
    completed: 'પૂર્ણ',
    attempts: 'પ્રયાસો',
    hint: 'સંકેત',
    divisionTip: 'યાદ રાખો: ભાગાકાર ગુણાકારનું વિપરીત છે',
    firstTry: 'પ્રથમ પ્રયાસ!',
    wellDone: 'સારું કર્યું!',
    practice_q1: 'મૂલ્યાંકન કરો: ૧૨ ÷ ૩',
    practice_q2: 'મૂલ્યાંકન કરો: (-૧૫) ÷ ૫',
    practice_q3: 'મૂલ્યાંકન કરો: ૧૮ ÷ (-૬)',
    practice_q4: 'મૂલ્યાંકન કરો: (-૨૪) ÷ (-૪)',
    practice_q5: 'મૂલ્યાંકન કરો: ૦ ÷ ૭',
    practice_q6: 'મૂલ્યાંકન કરો: ૩૫ ÷ (-૭)',
    assess_q1: 'ગણતરી કરો: (-૨૧) ÷ ૩',
    assess_q2: 'ગણતરી કરો: ૨૮ ÷ (-૪)',
    assess_q3: 'ગણતરી કરો: (-૩૬) ÷ (-૯)',
    assess_q4: 'ગણતરી કરો: ૦ ÷ (-૮)',
    assess_q5: 'ગણતરી કરો: ૪૫ ÷ ૫',
    assess_q6: 'ગણતરી કરો: (-૫૬) ÷ ૭',
    assessmentComplete: 'મૂલ્યાંકન પૂર્ણ!',
    detailedResults: 'વિગતવાર પરિણામો',
    totalQuestions: 'કુલ પ્રશ્નો',
    points: 'પોઈન્ટ્સ',
    reviewAnswers: 'જવાબોની સમીક્ષા',
    backToResults: 'પરિણામો પર પાછા',
    correctAnswer: 'સાચો જવાબ',
    yourAnswer: 'તમારો જવાબ',
    retakeAssessment: 'ફરીથી મૂલ્યાંકન',
    avgTime: 'સરેરાશ સમય',
    suggestions: 'સૂચનો',
    suggestMorePractice: 'ભાગાકારની ક્રિયાઓનો વધુ અભ્યાસ કરો',
    suggestSpeedUp: 'ગણતરીની ગતિ સુધારવા પર કામ કરો',
    suggestCompleteAll: 'બધા પ્રશ્નોનો પ્રયાસ કરવાનો પ્રયત્ન કરો',
    // Division-specific terms
    dividend: 'ભાજ્ય',
    divisor: 'ભાજક',
    quotient: 'ભાગફળ',
    remainder: 'બાકી',
    division: 'ભાગાકાર',
    // Division demonstration steps
    basicDivisionTitle: 'મૂળભૂત ભાગાકાર',
    basicDivisionDesc: 'ધનાત્મક પૂર્ણાંકો સાથે મૂળભૂત ભાગાકાર કન્સેપ્ટ્સ શીખો. સમજો કે ભાગાકાર સંખ્યાઓને સમાન જૂથોમાં કેવી રીતે વહેંચે છે.',
    basicDivisionExample: '૧૨ ÷ ૩ = ૪',
    negativeDivisionTitle: 'નકારાત્મક સંખ્યાઓ સાથે ભાગાકાર',
    negativeDivisionDesc: 'નકારાત્મક પૂર્ણાંકો સાથે ભાગાકાર નિયમોમાં નિપુણતા મેળવો. શીખો કે પરિણામ ક્યારે ધનાત્મક અથવા નકારાત્મક હોય છે.',
    negativeDivisionExample: '(-૧૫) ÷ ૫ = -૩, (-૧૨) ÷ (-૪) = ૩',
    zeroDivisionTitle: 'શૂન્ય દ્વારા ભાગાકાર અને વિશેષ કેસો',
    zeroDivisionDesc: 'સમજો કે શૂન્ય દ્વારા ભાગાકાર શા માટે અવ્યાખ્યાયિત છે અને ભાગાકાર ક્રિયાઓમાં શૂન્ય કેવી રીતે વર્તે છે.',
    zeroDivisionExample: '૦ ÷ ૭ = ૦, ૭ ÷ ૦ = અવ્યાખ્યાયિત',
    divisionPropertiesTitle: 'ભાગાકારના ગુણધર્મો',
    divisionPropertiesDesc: 'ભાગાકારના ગાણિતિક ગુણધર્મોનું અન્વેષણ કરો: ક્રમવિનિમય, સહયોગી, અને ઓળખ ગુણધર્મો.',
    divisionPropertiesExample: '૧૨ ÷ ૩ ≠ ૩ ÷ ૧૨',
    distributiveTitle: 'વિતરણ ગુણધર્મ',
    distributiveDesc: 'શીખો કે ભાગાકાર સરવાળા અને બાદબાકી ક્રિયાઓ પર કેવી રીતે વિતરિત થાય છે.',
    
    // Division demonstration steps for step-by-step learning
    sharingSweetsTitle: 'મીઠાઈ સરખી રીતે વહેંચવી',
    sharingSweetsDesc: 'તમારી પાસે 12 મીઠાઈ છે જે 3 મિત્રોમાં સરખી રીતે વહેંચવી છે. દરેક મિત્રને કેટલી મીઠાઈ મળશે?',
    sharingSweetsExample: '12 ÷ 3 = દરેક મિત્રને 4 મીઠાઈ',
    
    temperatureDivisionTitle: 'તાપમાન ભાગાકાર',
    temperatureDivisionDesc: '4 દિવસમાં તાપમાન 20°C ઘટ્યું. દૈનિક સરેરાશ ઘટાડો કેટલો હતો?',
    temperatureDivisionExample: '(-20) ÷ 4 = દરરોજ -5°C',
    
    businessProfitTitle: 'વ્યાપારિક નફો ભાગાકાર',
    businessProfitDesc: 'એક વ્યાપારમાં 4 મહિનામાં ₹800 નું નુકસાન થયું. સરેરાશ માસિક નુકસાન કેટલું હતું?',
    businessProfitExample: '(-800) ÷ 4 = દર મહિને -₹200',
    
    groupingObjectsTitle: 'વસ્તુઓનું જૂથીકરણ',
    groupingObjectsDesc: 'ભાગાકાર આપણને બતાવે છે કે વસ્તુઓને સરખી રીતે કેવી રીતે જૂથબદ્ધ કરવી અથવા કેટલા જૂથ બનાવી શકીએ.',
    groupingObjectsExample: '15 ÷ 5 = 5 વસ્તુઓના 3 જૂથ',
    
    divisionPropertiesStepTitle: 'ભાગાકાર ગુણધર્મ સારાંશ',
    divisionPropertiesStepDesc: 'મુખ્ય ગુણધર્મોને સમજવા: ભાગાકાર ક્રમવિનિમય નથી, સહયોગી નથી, પરંતુ સરવાળા પર વિતરણ ગુણધર્મ અનુસરે છે.',
    divisionPropertiesStepExample: '12 ÷ 3 ≠ 3 ÷ 12 (4 ≠ 0.25)',
    distributiveExample: '(૧૫ + ૯) ÷ ૩ = (૧૫ ÷ ૩) + (૯ ÷ ૩) = ૫ + ૩ = ૮',
    // Property badges for division
    identity: 'ઓળખ (÷૧)',
    zero_property: 'શૂન્ય ગુણધર્મ',
    sign_rule: 'ચિહ્ન નિયમો',
    not_commutative: 'ક્રમવિનિમય નથી',
    not_associative: 'સહયોગી નથી',
    distributive_over_addition: 'વિતરણ',
    session_complete: 'સત્ર પૂર્ણ!',
    session_summary: 'અહીં તમારા સત્રનો સંપૂર્ણ સારાંશ છે',
    total_questions: 'કુલ પ્રશ્નો',
    correct_answers: 'સાચા જવાબો',
    incorrect_answers: 'ખોટા જવાબો',
    skipped_questions: 'છોડેલા પ્રશ્નો',
    final_grade: 'અંતિમ ગ્રેડ',
    accuracy_rate: 'સચોટતા દર',
    avg_time_per_question: 'સરેરાશ સમય/પ્રશ્ન',
    question_review: 'પ્રશ્ન દર પ્રશ્ન સમીક્ષા',
    start_new_session: 'નવો સત્ર શરૂ કરો',
    not_attempted: 'પ્રયાસ કર્યો નથી',
    previous: 'પાછળ',
    hideAnswer: 'જવાબ છુપાવો',
    showAnswer: 'જવાબ બતાવો',
    notAttempt: 'પ્રયાસ નહીં',
    guidedPractice: 'માર્ગદર્શિત અભ્યાસ',
    knowledgeAssessment: 'જ્ઞાન મૂલ્યાંકન',
    interactiveLearning: 'તાત્કાલિક પ્રતિસાદ અને વ્યાપક મૂલ્યાંકન સાથે ઇન્ટરેક્ટિવ શિક્ષણ',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<SupportedLanguage>('en');
  const [isTransitioning, setIsTransitioning] = useState(false);
  const t = useMemo(() => (key: string) => translations[language][key] ?? key, [language]);

  const digitMaps: Record<SupportedLanguage, Record<string, string>> = {
    en: { '0': '0', '1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9' },
    hi: { '0': '०', '1': '१', '2': '२', '3': '३', '4': '४', '5': '५', '6': '६', '7': '७', '8': '८', '9': '९' },
    gu: { '0': '૦', '1': '૧', '2': '૨', '3': '૩', '4': '૪', '5': '૫', '6': '૬', '7': '૭', '8': '૮', '9': '૯' },
  };

  const formatNumber = (n: number) => String(n).replace(/[0-9]/g, (d) => digitMaps[language][d]);
  const localizeDigitsInText = (text: string) => text.replace(/[0-9]/g, (d) => digitMaps[language][d]);

  // Enhanced setLanguage with transition animation
  const setLanguageWithAnimation = (lang: SupportedLanguage) => {
    if (lang === language) return;
    
    setIsTransitioning(true);
    
    // Add a slight delay to show the transition effect
    setTimeout(() => {
      setLanguage(lang);
      setTimeout(() => {
        setIsTransitioning(false);
      }, 300); // Animation duration
    }, 150);
  };

  const value = useMemo(() => ({ 
    language, 
    setLanguage: setLanguageWithAnimation, 
    t, 
    formatNumber, 
    localizeDigitsInText, 
    isTransitioning 
  }), [language, isTransitioning]);
  
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}