import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'hi' | 'gu';
  setLanguage: (lang: 'en' | 'hi' | 'gu') => void;
  t: (key: string) => string;
  isTransitioning: boolean;
  localizeDigitsInText: (text: string) => string;
  formatNumber: (num: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Comprehensive translations
const translations = {
  en: {
    // Navigation
    home: 'Home',
    introduction: 'Introduction',
    learn: 'Learn',
    realWorld: 'Real World',
    simpleEquations: 'Simple Equations - Addition',
    simpleEquationsTitle: 'Simple Equations - Addition',
    exponentsTitle: 'Introduction to Exponents & Powers',
    rationalNumbersTitle: 'Rational Numbers on Number Line',
    rn_titleShort: 'Rational Number',
    rn_definition: '"Rational = any number p⁄q where q ≠ 0 — watch it form on the number line."',
    // Exponents hero (for Learn page)
    expHeroTitle: 'Introduction to Exponents',
    expHeroLine1: 'Exponents are a powerful way to represent repeated multiplication.',
    expHeroLine2: 'They make large numbers easier to read, understand, and work with!',
    interactivePreview: 'Interactive Preview',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 Introduction',
    tabExponents: '11.2 Exponents',
    massOfEarth: 'Mass of Earth',
    massOfUranus: 'Mass of Uranus',
    distancesInSpace: 'Distances in Space',
    hugeNumbersReadable: 'Huge numbers made readable with exponents',
    powerOf3: '5 to the power of 3',
    powerOf4: '3 to the power of 4',
    powerOf6: '2 to the power of 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 Exponents — Basic Concepts',
    visualExponentialForm: 'Visual Exponential Form',
    base: 'Base',
    baseDescription: 'The number being multiplied',
    exponent: 'Exponent',
    exponentDescription: 'How many times to multiply',
    power: 'Power',
    powerDescription: 'The result',
    specialName: 'Special Name',
    squared: 'Squared',
    tenSquared: '"10 squared"',
    cubed: 'Cubed',
    tenCubed: '"10 cubed"',
    primeFactorization: 'Prime Factorization',
    primeFactorizationDesc: 'Express factors compactly using exponents',
    negativeBases: 'Negative Bases',
    generalNotation: 'General Notation',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'Important Points',
    pointAnyBase: 'Any base can be used — not just 10',
    pointExponentialForm: 'Exponential form makes large numbers easier to work with',
    pointPrimeFactorization: 'Prime factorization is compact with exponents',
    
    // Home Page
    masterSimpleEquations: 'Master Simple Equations',
    masterClass7Mathematics: 'Master Class 7 Mathematics with interactive learning, practice exercises, and engaging games based on NCERT curriculum',
    startLearning: 'Start Learning',
    whatYoullLearn: 'What You\'ll Learn',
    comprehensiveTools: 'Comprehensive tools designed to make learning simple equations engaging and effective',
    introductionDesc: 'Learn the basics of simple equations with interactive examples',
    learnDesc: 'Step-by-step explanations with visual aids',
    practiceDesc: 'Solve exercises and check your solutions',
    realWorldDesc: 'See how equations apply in everyday life',
    practiceProblems: 'Practice Problems',
    interactiveExamples: 'Interactive Examples',
    readyToMaster: 'Ready to Master Simple Equations?',
    joinThousands: 'Join thousands of students and teachers who are making mathematics engaging and accessible.',
    startYourJourney: 'Start Your Journey',
    
    // Common
    correct: 'Correct!',
    incorrect: 'Try again!',
    notQuite: 'Not quite.',
    learning: 'Learning',
    practice: 'Practice',
    assessment: 'Assessment',
    selectEquation: 'Select Equation:',
    yourAnswer: 'Your Answer:',
    submit: 'Submit',
    hint: 'Hint',
    progress: 'Progress:',
    accuracy: 'Accuracy',
    avgTime: 'Avg Time',
    correctAnswers: 'Correct',
    incorrectAnswers: 'Incorrect',
    totalExercises: 'Total',
    excellent: 'Excellent!',
    goodJob: 'Good Job!',
    keepTrying: 'Keep Trying!',
    showSolution: 'Show Solution',
    hideSolution: 'Hide Solution',
    reset: 'Reset',
    stepByStepSolution: 'Step-by-Step Solution:',
    nextStep: 'Next Step',
    complete: 'Complete',
    
    // Real World
    realWorldApps: 'Real World Applications',
    selectCategory: 'Select Category:',
    difficulty: 'Difficulty:',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    equation: 'Equation:',
    solution: 'Solution:',
    context: 'Context:',
    shopping: 'Shopping',
    cooking: 'Cooking',
    construction: 'Construction',
    sports: 'Sports',
    finance: 'Finance',
    science: 'Science',
    
    // Learn Section
    linearEquations: 'Linear Equations',
    linearEquationsDesc: 'Linear equations are equations where the highest power of the variable is 1. They can be solved using basic algebraic operations like addition, subtraction, multiplication, and division.',
    solvingByAddition: 'Solving by Addition',
    solvingByAdditionDesc: 'When we have subtraction in an equation, we add the same number to both sides to isolate the variable. This maintains the balance of the equation.',
    solvingBySubtraction: 'Solving by Subtraction',
    solvingBySubtractionDesc: 'When we have addition in an equation, we subtract the same number from both sides to isolate the variable. This maintains the balance of the equation.',
    solvingByMultiplication: 'Solving by Multiplication',
    solvingByMultiplicationDesc: 'When we have division in an equation, we multiply both sides by the same number to isolate the variable. This maintains the balance of the equation.',
    solvingByDivision: 'Solving by Division',
    solvingByDivisionDesc: 'When we have multiplication in an equation, we divide both sides by the same number to isolate the variable. This maintains the balance of the equation.',
    originalEquation: 'Original equation',
    originalEquationWithSubtraction: 'Original equation with subtraction',
    originalEquationWithAddition: 'Original equation with addition',
    originalEquationWithDivision: 'Original equation with division',
    originalEquationWithMultiplication: 'Original equation with multiplication',
    subtractFromBothSides: 'Subtract 5 from both sides',
    addToBothSides: 'Add 3 to both sides to isolate x',
    subtractFromBothSidesToIsolate: 'Subtract 4 from both sides to isolate x',
    multiplyBothSides: 'Multiply both sides by 3 to isolate x',
    divideBothSides: 'Divide both sides by 3 to isolate x',
    simplifyToFindAnswer: 'Simplify to find the answer',
    simplifyStep: 'Simplify: 5 - 5 = 0 and 12 - 5 = 7',
    verifySolution: 'Verify the solution by substituting x = 7',
    simplifyAdditionStep: 'Simplify: -3 + 3 = 0 and 8 + 3 = 11',
    verifyAdditionSolution: 'Verify the solution by substituting x = 11',
    simplifySubtractionStep: 'Simplify: 4 - 4 = 0 and 7 - 4 = 3',
    verifySubtractionSolution: 'Verify the solution by substituting x = 3',
    simplifyMultiplicationStep: 'Simplify: 3/3 = 1 and 4 × 3 = 12',
    verifyMultiplicationSolution: 'Verify the solution by substituting x = 12',
    simplifyDivisionStep: 'Simplify: 3x ÷ 3 = x and 15 ÷ 3 = 5',
    verifyDivisionSolution: 'Verify the solution by substituting x = 5',
    linearEquationExample: 'Linear Equation Example',
    additionMethodExample: 'Addition Method Example',
    subtractionMethodExample: 'Subtraction Method Example',
    multiplicationMethodExample: 'Multiplication Method Example',
    divisionMethodExample: 'Division Method Example',
    solving: 'Solving:',
    play: 'Play',
    pause: 'Pause',
    previous: 'Previous',
    next: 'Next',
    
    // Practice Mode
    practiceMode: 'Practice Mode',
    question: 'Question',
    skippedQuestions: 'Skipped Questions',
    notAttempted: 'Not Attempted',
    totalQuestions: 'Total Questions',
    finalGrade: 'Final Grade',
    accuracyRate: 'Accuracy Rate',
    avgTimePerQuestion: 'Avg Time/Question',
    questionByQuestionReview: 'Question by Question Review',
    startNewSession: 'Start New Session',
    loadingQuestions: 'Loading questions...',
    showAnswer: 'Show Answer',
    hideAnswer: 'Hide Answer',
    tryAgain: 'Try Again',
    skip: 'Skip',
    skipped: 'Skipped',
    sessionComplete: 'Session Complete!',
    sessionSummary: 'Here\'s your complete session summary',
    correctAnswer: 'Correct Answer',
    check: 'Check',
    notAttempt: 'Not Attempt',
    
    // Practice Questions
    q1_prompt: 'Convert 10,000 to exponential form',
    q1_explanation: '10,000 = 10 × 10 × 10 × 10 = 10⁴',
    q2_prompt: 'What is 5³?',
    q2_explanation: '5³ = 5 × 5 × 5 = 125',
    q3_prompt: 'What is the base in 7⁴?',
    q3_explanation: 'In 7⁴, 7 is the base (the number being multiplied)',
    q4_prompt: 'What is the exponent in 2⁵?',
    q4_explanation: 'In 2⁵, 5 is the exponent (showing how many times 2 is multiplied)',
    q5_prompt: 'Calculate 3⁴',
    q5_explanation: '3⁴ = 3 × 3 × 3 × 3 = 81',
    q6_prompt: 'What is 100 in exponential form?',
    q6_explanation: '100 = 10 × 10 = 10²',
    
    // Practice Questions
    practice_q1: 'Solve: x + 7 = 15',
    practice_q2: 'Solve: x + 4 = 12',
    practice_q3: 'Solve: x + 3 = 21',
    practice_q4: 'Solve: x + 2 = 8',
    practice_q5: 'Solve: x + 3 = 11',
    practice_q6: 'Solve: x + 5 = 9',
    practice_q7: 'Solve: x + 6 = 18',
    practice_q8: 'Solve: x + 2 = 7',
    practice_q9: 'Solve: x + 8 = 33',
    practice_q10: 'Solve: x + 7 = 13',
    practice_q11: 'Solve: x + 3 = 8',
    practice_q12: 'Solve: x + 12 = 30',
    
    // Exponents - Section 1: Introduction
    exp_intro_title: 'Why Do We Need Exponents?',
    exp_intro_text: 'Very large numbers are difficult to work with:',
    exp_problem_1: 'Hard to Read: 5,970,000,000,000,000,000,000,000 kg',
    exp_problem_2: 'Hard to Understand: How big is this number?',
    exp_problem_3: 'Hard to Compare: Which is bigger - Earth or Uranus?',
    exp_intro_solution: 'Solution: Use exponents to write numbers in a shorter, simpler form!',
    exp_example_title: 'Real-World Example',
    exp_example_before: 'Mass of Earth = 5,970,000,000,000,000,000,000,000 kg',
    exp_example_after: 'Mass of Earth = 5.97 × 10²⁴ kg',
    exp_example_benefit: 'Much easier to read and compare!',
    exp_before: 'Before',
    exp_after: 'After',
    
    // Exponents - Section 2: What Are Exponents
    exp_what_are_title: 'What Are Exponents?',
    exp_what_are_text: 'Exponents let us write repeated multiplication in a compact way.',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'Repeated multiplication',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'Exponential form',
    exp_main_example: 'Main Example',
    exp_term_base: 'Base',
    exp_term_base_def: 'The number being multiplied',
    exp_term_base_ex: 'In 10⁴, base = 10',
    exp_term_exp: 'Exponent',
    exp_term_exp_def: 'How many times to multiply the base',
    exp_term_exp_ex: 'In 10⁴, exponent = 4',
    exp_term_power: 'Power',
    exp_term_power_def: 'The whole expression',
    exp_term_power_ex: '10⁴ is read as "10 to the power of 4"',
    exp_key_terms: 'Key Terms to Remember:',
    
    // Exponents - Section 3: Working with Examples
    exp_examples_title: 'Working with Examples',
    exp_conversion_text: 'Let\'s see how numbers are converted to exponential form:',
    exp_example: 'Example',
    exp_step1: 'Step 1: Write as multiplication',
    exp_step2: 'Step 2: Write in exponential form',
    exp_base: 'Base',
    exp_exponent: 'Exponent',
    exp_read_as: 'Read as',
    exp_ex1_reading: '10 raised to the power of 3',
    exp_ex2_reading: '3 raised to the power of 4',
    exp_ex3_reading: '5 cubed',
    exp_ex4_reading: '2 raised to the power of 5',
    
    // Exponents - Section 4: Special Names
    exp_special_title: 'Special Names',
    exp_special_intro: 'Some exponents have special names that you\'ll use often:',
    exp_squared: 'Squared',
    exp_squared_read: 'squared',
    exp_cubed: 'Cubed',
    exp_cubed_read: 'cubed',
    exp_special_note: 'These special names come from geometry - squared from area of a square, cubed from volume of a cube!',
    exp_power_of: 'Power of',
    exp_fun_fact: 'Fun Fact',
    
    // Exponents - Section 5: Interactive Practice
    exp_practice_title: 'Interactive Practice',
    exp_interactive_intro: 'Try it yourself! Change the base and exponent to see how exponents work:',
    exp_expanded: 'Expanded Form',
    exp_exponential_form: 'Exponential Form',
    exp_result: 'Result',
    exp_reading_title: 'Reading',
    exp_raised_to: 'raised to the power of',
    exp_or: 'or',
    
    // Exponents - Common Terms
    of: 'of',
    example: 'Example',
    formula: 'Formula',
    explanation: 'Explanation',
    
    // Rational Numbers - Topic 8.1
    rn_topic81: '8.1 Introduction',
    rn_topic82: '8.2 Need for Rational Numbers',
    rn_progressiveExtension: 'Progressive Extension of the Number System',
    rn_naturalNumbers: 'Natural Numbers (Counting Numbers)',
    rn_naturalNumbersDesc: '1, 2, 3, 4, ...',
    rn_wholeNumbers: 'Whole Numbers',
    rn_wholeNumbersDesc: 'Natural numbers including zero (0, 1, 2, 3, ...)',
    rn_integers: 'Integers',
    rn_integersDesc: 'Whole numbers and the negatives of natural numbers (..., -3, -2, -1, 0, 1, 2, 3, ...)',
    rn_fractions: 'Fractions',
    rn_fractionsDesc: 'Numbers of the form numerator/denominator, where the numerator is a positive integer or zero, and the denominator is a positive integer',
    rn_rationalNumbers: 'Rational Numbers',
    rn_rationalNumbersDesc: 'All numbers that can be written as p/q where p and q are integers and q ≠ 0',
    rn_chapterObjective: 'Chapter Objective',
    rn_objectiveText: 'Further extend the number system to introduce the concept of Rational Numbers and study their fundamental operations (addition, subtraction, multiplication, and division).',
    
    // Rational Numbers - Topic 8.2
    rn_needTitle: 'Need for Rational Numbers',
    rn_insufficient: 'Why existing number systems are insufficient',
    rn_oppositeIntegers: 'Opposite Situations with Integers',
    rn_oppositeIntegersDesc: 'Integers are used to represent opposite quantities, such as distance to the right (positive 3) versus distance to the left (negative 5), or profit (positive ₹150) versus loss (negative ₹100).',
    rn_oppositeFractions: 'Opposite Situations with Fractions',
    rn_oppositeFractionsDesc: 'When these opposite situations involve fractional amounts, a new type of number is required.',
    rn_exampleAbove: '750m above sea level can be written as 3/4 km',
    rn_exampleBelow: '750m below sea level would logically be represented as -3/4 km',
    rn_gapTitle: 'The Gap in the Number System',
    rn_gapDesc: 'The number -3/4 is neither an integer nor a standard fraction (where the numerator is non-negative and the denominator is positive).',
    rn_conclusion: 'Conclusion',
    rn_conclusionText: 'The number system must be extended to include these new numbers, which are called Rational Numbers.',
    
    // Rational Numbers - Visualizations
    rn_numberLine: 'Number Line Representation',
    rn_seeItForm: 'Watch rational numbers form on the number line',
    rn_standardForm: 'Standard Form',
    rn_seeFractionShrink: 'See the fraction shrink to standard form',
    rn_equivalence: 'Equivalence',
    rn_seePiecesMerge: 'Watch the pieces merge to show equality',
    rn_visualGuidePositive: 'This positive rational number ({x}) lies to the right of zero.',
    rn_visualGuideNegative: 'This negative rational number ({x}) lies to the left of zero.',
    
    // Rational Numbers - Practice
    rn_practiceTitle: 'Practice — Try, see, succeed',
    rn_practiceDesc: 'Interactive problems with animated hints and instant visual feedback',
    rn_typeTwoRationals: 'Type two rationals — we\'ll animate the midpoint',
    rn_checkNumbers: 'Tap \'Check\' — numbers light up green for correct',
    rn_showHint: 'Got it wrong? A quick hint animates the step-by-step fix',
    
    // Rational Numbers - Real World
    rn_realWorldTitle: 'Real World — Where math meets life',
    rn_realWorldDesc: 'Short, realistic scenarios with animated diagrams',
    rn_metersKm: 'Meters → kilometres: watch the ruler compress',
    rn_slideControl: 'Slide the control to change a value and watch the world update',
    rn_ratiosAnimate: 'Interest rates, music ratios — see each ratio animate'
    ,
    // Rational Numbers – Practice custom text
    rn_practiceHeader: 'Practice Question',
    rn_practiceSub: 'Practice questions designed to build confidence and accuracy.',
    // Score Card
    sc_sessionComplete: 'Session Complete',
    sc_totalQuestions: 'Total Questions',
    sc_finalGrade: 'Final Grade',
    sc_accuracyRate: 'Accuracy Rate',
    sc_avgTime: 'Avg Time/Question',
    sc_startNew: 'Start New Session',
    sc_clickToSeeAnswer: 'Click to see answer',
    sc_answer: 'Answer:',
    // Real World custom
    rw_title: 'Real World Application',
    rw_desc: 'Explore how rational numbers appear in the world around you.',
    rw_overview: 'Overview',
    rw_calc: 'Calculation',
    rw_tapToExpand: 'Tap to expand',
    rw_app_temperature_title: 'Temperature Below Zero',
    rw_app_temperature_desc: 'Leh: −5°C, Delhi: +10°C. Temperatures below zero are negative; above zero are positive.',
    rw_app_banking_title: 'Banking — Profit and Loss',
    rw_app_banking_desc: 'Week 1: +₹2000 gain; Week 2: −₹1500 loss. Gains are positive, losses negative.',
    rw_app_sea_title: 'Elevation — Above and Below Sea Level',
    rw_app_sea_desc: 'Submarine at −300 m, Ship at +100 m. Both directions from sea level.',
    rw_app_debt_title: 'Finance — Debt and Credit',
    rw_app_debt_desc: 'Debt ₹500 (negative) and Credit ₹1000 (positive) as rational numbers.',
    rw_app_weather_title: 'Weather — Rise and Fall',
    rw_app_weather_desc: 'Morning 8°C and drop by 4°C → 4°C. Decrease is leftward on the line.',
    rw_app_airplane_title: 'Altitude — Airplane Descent',
    rw_app_airplane_desc: 'Descends from 3000 m to 1500 m → change −1500 m (leftward movement).'
    ,
    // Learn tools (Between Finder & Standard Form) — labels and messages
    bf_title: 'Find Rational Between Two Numbers',
    bf_placeholder1: 'First rational (e.g., -3/5)',
    bf_placeholder2: 'Second rational (e.g., -1/2)',
    bf_tryIt: 'Try it',
    bf_retry: 'Retry',
    bf_betweenLabel: 'A rational number between them:',
    bf_invalidInput: 'Invalid input — use forms like -3/5 or 0.4',
    bf_equalNumbers: 'Numbers are equal — infinitely many rationals exist between them.',
    sf_title: 'Convert to Standard Form',
    sf_placeholder: '36/24 or -15/20',
    sf_convert: 'Convert',
    sf_retry: 'Retry',
    sf_error_enter: 'Please enter a fraction (e.g., 36/24 or -15/20)',
    sf_error_invalid: 'Invalid format. Please use format: numerator/denominator',
    sf_error_den: 'Invalid numbers. Denominator cannot be zero.',
    sf_resultLabel: 'Standard Form:',
    
    // Rational Numbers - Topic 8.5
    rn85_main_title: 'Rational Numbers on Number Line',
    rn85_main_subtitle: 'Topic 8.5',
    
    // Topic 8.5: Rational Numbers on a Number Line
    rn85_title: 'Rational Numbers on a Number Line',
    rn85_intro_title: 'Basic Concept',
    rn85_intro_text: 'Rational numbers can be represented on a number line, just like integers and fractions.',
    rn85_placement_title: 'Key Rules for Placement',
    rn85_placement_subtitle: 'Position relative to zero:',
    rn85_positive_right: 'Positive rational numbers → marked to the right of 0',
    rn85_negative_left: 'Negative rational numbers → marked to the left of 0',
    rn85_zero_center: '0 → at the center',
    rn85_properties_title: 'Important Properties',
    rn85_equal_distance_title: 'Equal Distance from Zero:',
    rn85_equal_distance_text: 'Rational numbers like 1/2 and -1/2 are at equal distances from 0',
    rn85_equal_distance_ex: 'Examples: 3/2 and -3/2 are equidistant from 0',
    rn85_marking_title: 'Marking Examples:',
    rn85_marking_ex1: '-1/2: lies halfway between 0 and -1',
    rn85_marking_ex2: '-3/2: lies halfway between -1 and -2',
    rn85_marking_ex3: '-1/3: same distance from 0 as 1/3, but on the left side',
    rn85_interactive_title: 'Interactive Number Line',
    rn85_interactive_subtitle: 'Explore rational numbers on the number line',
    
    // Topic 8.6: Rational Numbers in Standard Form
    rn86_title: 'Topic 8.6: Rational Numbers in Standard Form',
    rn86_definition_title: 'Definition',
    rn86_definition_text: 'A rational number is in standard form when:',
    rn86_rule1: 'The denominator is a positive integer',
    rn86_rule2: 'The numerator and denominator have no common factor other than 1',
    rn86_rule3: 'The negative sign (if any) is in the numerator only',
    rn86_examples_title: 'Examples',
    rn86_standard_form: 'Standard form:',
    rn86_standard_ex: '-3/5, 5/8, -2/7, 7/11',
    rn86_not_standard: 'Not in standard form:',
    rn86_not_standard_ex: '3/-5, 45/-30, -12/24',
    rn86_convert_title: 'How to Convert to Standard Form',
    rn86_step1: 'Step 1: Find the HCF (Highest Common Factor) of numerator and denominator (ignore negative signs)',
    rn86_step2: 'Step 2: Divide both numerator and denominator by their HCF',
    rn86_step2_note: 'If denominator is negative, divide by -HCF',
    rn86_examples_convert_title: 'Conversion Examples:',
    rn86_ex1: '-45/30 → HCF = 15 → (-45÷15)/(30÷15) = -3/2 ✓',
    rn86_ex2: '36/-24 → Divide by -12 → (36÷-12)/(-24÷-12) = -3/2 ✓',
    rn86_ex3: '-3/-15 → Divide by -3 → (-3÷-3)/(-15÷-3) = 1/5 ✓',
    rn86_interactive_title: 'Convert to Standard Form',
    rn86_interactive_subtitle: 'Practice converting rational numbers',
    rn86_numerator_label: 'Numerator',
    rn86_denominator_label: 'Denominator',
    rn86_convert_button: 'Convert to Standard Form',
    rn86_hcf_label: 'HCF:',
    rn86_result_label: 'Standard Form:',
    
    // Real World Applications (Topic 8.5)
    rw_app_temperature_title: 'Temperature Scale',
    rw_app_temperature_desc: 'Temperature can be shown on a number line with 0°C as center, positive temperatures to the right (hot), and negative temperatures to the left (cold).',
    rw_app_recipe_title: 'Water Level',
    rw_app_recipe_desc: 'Water level in a tank: +3/4 meter above normal (right of 0) or -3/4 meter below normal (left of 0) on number line.',
    rw_app_distance_title: 'Distance Markers',
    rw_app_distance_desc: 'Road markers showing positions: negative for west (-3/2 km) and positive for east (+3/2 km) from reference point on number line.',
    rw_app_altitude_title: 'Sea Level Altitude',
    rw_app_altitude_desc: 'Altitude measurements on number line: -1/2 km below sea level (left of 0) and +1/2 km above sea level (right of 0).',
    rw_app_money_title: 'Bank Balance',
    rw_app_money_desc: 'Bank account on number line: +5/2 thousand rupees (credit, right of 0) or -5/2 thousand rupees (debt, left of 0).',
    rw_app_time_title: 'Time Difference',
    rw_app_time_desc: 'Time differences on number line: +5/2 hours ahead of GMT (right of 0) and -5/2 hours behind GMT (left of 0).',
    
    // Practice page questions (Rational Numbers Topic 8.5)
    pq1_prompt: 'Where is the rational number -1/2 located on the number line?',
    pq1_explain: '-1/2 lies halfway between 0 and -1 on the left side of 0.',
    pq2_prompt: 'Which rational numbers are at equal distances from 0?',
    pq2_explain: 'Rational numbers like 3/4 and -3/4 are at equal distances from 0, one on the right and one on the left.',
    pq3_prompt: 'Where do we mark positive rational numbers on the number line?',
    pq3_explain: 'Positive rational numbers are always marked to the right of 0 on the number line.',
    pq4_prompt: 'Where is -3/2 located on the number line?',
    pq4_explain: '-3/2 = -1.5, which lies halfway between -1 and -2 on the left side of 0.',
    pq5_prompt: 'If 2/5 is marked on the right side of 0, where will -2/5 be located?',
    pq5_explain: '-2/5 will be at the same distance from 0 as 2/5, but on the left side of 0.',
    pq6_prompt: 'Which is farther from 0 on the number line?',
    pq6_explain: '3/2 is farther from 0 than 1/2, because 3/2 = 1.5 which is greater than 1/2 = 0.5.',
    // Question options
    pq1_opt1: 'Between -1 and -2',
    pq1_opt2: 'Between 0 and 1',
    pq1_opt3: 'Halfway between 0 and -1',
    pq1_opt4: 'Between 1 and 2',
    pq2_opt1: '1/2 and 1/3',
    pq2_opt2: '3/4 and -3/4',
    pq2_opt3: '1/2 and 2/3',
    pq2_opt4: '5/6 and 1/6',
    pq3_opt1: 'To the left of 0',
    pq3_opt2: 'At 0',
    pq3_opt3: 'To the right of 0',
    pq3_opt4: 'Anywhere on the line',
    pq4_opt1: 'Between 0 and -1',
    pq4_opt2: 'Between -1 and -2',
    pq4_opt3: 'Between -2 and -3',
    pq4_opt4: 'Between 1 and 2',
    pq5_opt1: 'On the right side of 0',
    pq5_opt2: 'On the left side of 0',
    pq5_opt3: 'At the same place as 2/5',
    pq5_opt4: 'At 0',
    pq6_opt1: '1/2',
    pq6_opt2: '3/2',
    pq6_opt3: 'Both are equal',
    pq6_opt4: 'Cannot determine'
  },
  hi: {
    // Navigation
    home: 'होम',
    introduction: 'परिचय',
    learn: 'सीखें',
    realWorld: 'वास्तविक दुनिया',
    simpleEquations: 'सरल समीकरण - जोड़',
    simpleEquationsTitle: 'सरल समीकरण - जोड़',
    exponentsTitle: 'घातांक और घात का परिचय',
    rationalNumbersTitle: 'संख्या रेखा पर परिमेय संख्याएं और मानक रूप',
    rn_titleShort: 'परिमेय संख्या',
    rn_definition: '"परिमेय = कोई भी संख्या p⁄q जहाँ q ≠ 0 — इसे संख्या रेखा पर देखें।"',
    // Exponents hero (for Learn page)
    expHeroTitle: 'घातांकों का परिचय',
    expHeroLine1: 'घातांक बार‑बार गुणा को दर्शाने का एक शक्तिशाली तरीका है।',
    expHeroLine2: 'ये बड़ी संख्याओं को पढ़ना, समझना और उनके साथ काम करना आसान बनाते हैं!',
    interactivePreview: 'इंटरैक्टिव पूर्वावलोकन',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 परिचय',
    tabExponents: '11.2 घातांक',
    massOfEarth: 'पृथ्वी का द्रव्यमान',
    massOfUranus: 'यूरेनस का द्रव्यमान',
    distancesInSpace: 'अंतरिक्ष में दूरियाँ',
    hugeNumbersReadable: 'घातांकों से बड़ी संख्याएँ पढ़ने योग्य बनती हैं',
    powerOf3: '5 की घात 3',
    powerOf4: '3 की घात 4',
    powerOf6: '2 की घात 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 घातांक — मूल अवधारणाएँ',
    visualExponentialForm: 'दृश्य घातांकीय रूप',
    base: 'आधार',
    baseDescription: 'वह संख्या जिसे गुणा किया जा रहा है',
    exponent: 'घातांक',
    exponentDescription: 'कितनी बार गुणा करना है',
    power: 'घात',
    powerDescription: 'परिणाम',
    specialName: 'विशेष नाम',
    squared: 'वर्ग',
    tenSquared: '"10 का वर्ग"',
    cubed: 'घन',
    tenCubed: '"10 का घन"',
    primeFactorization: 'अभाज्य गुणनखंडन',
    primeFactorizationDesc: 'घातांकों का उपयोग करके गुणनखंडों को संक्षिप्त रूप से व्यक्त करें',
    negativeBases: 'ऋणात्मक आधार',
    generalNotation: 'सामान्य संकेतन',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'महत्वपूर्ण बिंदु',
    pointAnyBase: 'कोई भी आधार उपयोग किया जा सकता है — केवल 10 ही नहीं',
    pointExponentialForm: 'घातांकीय रूप बड़ी संख्याओं के साथ काम करना आसान बनाता है',
    pointPrimeFactorization: 'अभाज्य गुणनखंडन घातांकों के साथ संक्षिप्त होता है',
    
    // Home Page
    masterSimpleEquations: 'सरल समीकरणों में महारत हासिल करें',
    masterClass7Mathematics: 'एनसीईआरटी पाठ्यक्रम के आधार पर इंटरैक्टिव सीखने, अभ्यास अभ्यास और आकर्षक गेम के साथ कक्षा 7 गणित में महारत हासिल करें',
    startLearning: 'सीखना शुरू करें',
    whatYoullLearn: 'आप क्या सीखेंगे',
    comprehensiveTools: 'सरल समीकरणों को सीखने को आकर्षक और प्रभावी बनाने के लिए डिज़ाइन किए गए व्यापक उपकरण',
    introductionDesc: 'इंटरैक्टिव उदाहरणों के साथ सरल समीकरणों की मूल बातें सीखें',
    learnDesc: 'दृश्य सहायता के साथ चरण-दर-चरण स्पष्टीकरण',
    practiceDesc: 'अभ्यास हल करें और अपने समाधान जांचें',
    realWorldDesc: 'देखें कि समीकरण रोजमर्रा की जिंदगी में कैसे लागू होते हैं',
    practiceProblems: 'अभ्यास समस्याएं',
    interactiveExamples: 'इंटरैक्टिव उदाहरण',
    readyToMaster: 'सरल समीकरणों में महारत हासिल करने के लिए तैयार हैं?',
    joinThousands: 'हजारों छात्रों और शिक्षकों में शामिल हों जो गणित को आकर्षक और सुलभ बना रहे हैं।',
    startYourJourney: 'अपनी यात्रा शुरू करें',
    
    // Common
    correct: 'सही!',
    incorrect: 'फिर कोशिश करें!',
    notQuite: 'ठीक नहीं।',
    learning: 'सीखना',
    practice: 'अभ्यास',
    assessment: 'मूल्यांकन',
    selectEquation: 'समीकरण चुनें:',
    yourAnswer: 'आपका उत्तर:',
    submit: 'जमा करें',
    hint: 'संकेत',
    progress: 'प्रगति:',
    accuracy: 'सटीकता',
    avgTime: 'औसत समय',
    correctAnswers: 'सही',
    incorrectAnswers: 'गलत',
    totalExercises: 'कुल',
    excellent: 'उत्कृष्ट!',
    goodJob: 'अच्छा काम!',
    keepTrying: 'कोशिश करते रहें!',
    showSolution: 'समाधान दिखाएं',
    hideSolution: 'समाधान छुपाएं',
    reset: 'रीसेट',
    stepByStepSolution: 'चरण-दर-चरण समाधान:',
    nextStep: 'अगला चरण',
    complete: 'पूर्ण',
    
    // Real World
    realWorldApps: 'वास्तविक दुनिया के अनुप्रयोग',
    selectCategory: 'श्रेणी चुनें:',
    difficulty: 'कठिनाई:',
    beginner: 'शुरुआती',
    intermediate: 'मध्यम',
    advanced: 'उन्नत',
    equation: 'समीकरण:',
    solution: 'समाधान:',
    context: 'संदर्भ:',
    shopping: 'खरीदारी',
    cooking: 'खाना पकाना',
    construction: 'निर्माण',
    sports: 'खेल',
    finance: 'वित्त',
    science: 'विज्ञान',
    
    // Learn Section
    linearEquations: 'रैखिक समीकरण',
    linearEquationsDesc: 'रैखिक समीकरण वे समीकरण हैं जहाँ चर की सबसे बड़ी घात 1 है।',
    solvingByAddition: 'जोड़ द्वारा हल करना',
    solvingByAdditionDesc: 'जब हमारे पास समीकरण में घटाव होता है, तो हम चर को अलग करने के लिए दोनों पक्षों में समान संख्या जोड़ते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingBySubtraction: 'घटाव द्वारा हल करना',
    solvingBySubtractionDesc: 'जब हमारे पास समीकरण में जोड़ होता है, तो हम चर को अलग करने के लिए दोनों पक्षों से समान संख्या घटाते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingByMultiplication: 'गुणा द्वारा हल करना',
    solvingByMultiplicationDesc: 'जब हमारे पास समीकरण में भाग होता है, तो हम चर को अलग करने के लिए दोनों पक्षों को समान संख्या से गुणा करते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    solvingByDivision: 'भाग द्वारा हल करना',
    solvingByDivisionDesc: 'जब हमारे पास समीकरण में गुणा होता है, तो हम चर को अलग करने के लिए दोनों पक्षों को समान संख्या से भाग देते हैं। यह समीकरण के संतुलन को बनाए रखता है।',
    originalEquation: 'मूल समीकरण',
    originalEquationWithSubtraction: 'घटाव के साथ मूल समीकरण',
    originalEquationWithAddition: 'जोड़ के साथ मूल समीकरण',
    originalEquationWithDivision: 'भाग के साथ मूल समीकरण',
    originalEquationWithMultiplication: 'गुणा के साथ मूल समीकरण',
    subtractFromBothSides: 'दोनों पक्षों से 5 घटाएं',
    addToBothSides: 'x को अलग करने के लिए दोनों पक्षों में 3 जोड़ें',
    subtractFromBothSidesToIsolate: 'x को अलग करने के लिए दोनों पक्षों से 4 घटाएं',
    multiplyBothSides: 'x को अलग करने के लिए दोनों पक्षों को 3 से गुणा करें',
    divideBothSides: 'x को अलग करने के लिए दोनों पक्षों को 3 से भाग दें',
    simplifyToFindAnswer: 'उत्तर ज्ञात करने के लिए सरल करें',
    simplifyStep: 'सरल करें: 5 - 5 = 0 और 12 - 5 = 7',
    verifySolution: 'x = 7 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyAdditionStep: 'सरल करें: -3 + 3 = 0 और 8 + 3 = 11',
    verifyAdditionSolution: 'x = 11 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifySubtractionStep: 'सरल करें: 4 - 4 = 0 और 7 - 4 = 3',
    verifySubtractionSolution: 'x = 3 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyMultiplicationStep: 'सरल करें: 3/3 = 1 और 4 × 3 = 12',
    verifyMultiplicationSolution: 'x = 12 प्रतिस्थापित करके समाधान सत्यापित करें',
    simplifyDivisionStep: 'सरल करें: 3x ÷ 3 = x और 15 ÷ 3 = 5',
    verifyDivisionSolution: 'x = 5 प्रतिस्थापित करके समाधान सत्यापित करें',
    linearEquationExample: 'रैखिक समीकरण उदाहरण',
    additionMethodExample: 'जोड़ विधि उदाहरण',
    subtractionMethodExample: 'घटाव विधि उदाहरण',
    multiplicationMethodExample: 'गुणा विधि उदाहरण',
    divisionMethodExample: 'भाग विधि उदाहरण',
    solving: 'हल करना:',
    play: 'चलाएं',
    pause: 'रोकें',
    previous: 'पिछला',
    next: 'अगला',
    
    // Practice Mode
    practiceMode: 'अभ्यास मोड',
    question: 'प्रश्न',
    skippedQuestions: 'छोड़े गए प्रश्न',
    notAttempted: 'प्रयास नहीं किया',
    totalQuestions: 'कुल प्रश्न',
    finalGrade: 'अंतिम ग्रेड',
    accuracyRate: 'सटीकता दर',
    avgTimePerQuestion: 'प्रति प्रश्न औसत समय',
    questionByQuestionReview: 'प्रश्न दर प्रश्न समीक्षा',
    startNewSession: 'नया सत्र शुरू करें',
    loadingQuestions: 'प्रश्न लोड हो रहे हैं...',
    showAnswer: 'उत्तर दिखाएं',
    hideAnswer: 'उत्तर छुपाएं',
    tryAgain: 'फिर कोशिश करें',
    skip: 'छोड़ें',
    skipped: 'छोड़ा गया',
    sessionComplete: 'सत्र पूरा!',
    sessionSummary: 'यहाँ आपका पूरा सत्र सारांश है',
    correctAnswer: 'सही उत्तर',
    check: 'जांच',
    notAttempt: 'प्रयास नहीं करें',
    
    // Practice Questions - Exponents
    q1_prompt: '10,000 को घातांकीय रूप में बदलें',
    q1_explanation: '10,000 = 10 × 10 × 10 × 10 = 10⁴',
    q2_prompt: '5³ क्या है?',
    q2_explanation: '5³ = 5 × 5 × 5 = 125',
    q3_prompt: '7⁴ में आधार क्या है?',
    q3_explanation: '7⁴ में, 7 आधार है (जिस संख्या को गुणा किया जा रहा है)',
    q4_prompt: '2⁵ में घातांक क्या है?',
    q4_explanation: '2⁵ में, 5 घातांक है (दिखाता है कि 2 कितनी बार गुणा होता है)',
    q5_prompt: '3⁴ की गणना करें',
    q5_explanation: '3⁴ = 3 × 3 × 3 × 3 = 81',
    q6_prompt: '100 घातांकीय रूप में क्या है?',
    q6_explanation: '100 = 10 × 10 = 10²',
    
    // Practice Questions
    practice_q1: 'हल करें: x + 7 = 15',
    practice_q2: 'हल करें: x + 4 = 12',
    practice_q3: 'हल करें: x + 3 = 21',
    practice_q4: 'हल करें: x + 2 = 8',
    practice_q5: 'हल करें: x + 3 = 11',
    practice_q6: 'हल करें: x + 5 = 9',
    practice_q7: 'हल करें: x + 6 = 18',
    practice_q8: 'हल करें: x + 2 = 7',
    practice_q9: 'हल करें: x + 8 = 33',
    practice_q10: 'हल करें: x + 7 = 13',
    practice_q11: 'हल करें: x + 3 = 8',
    practice_q12: 'हल करें: x + 12 = 30',
    
    // Exponents
    exp_intro_title: 'घातांक क्यों चाहिए?',
    exp_intro_text: 'बहुत बड़ी संख्याओं के साथ काम करना मुश्किल है:',
    exp_problem_1: 'पढ़ना मुश्किल: 5,970,000,000,000,000,000,000,000 किलो',
    exp_problem_2: 'समझना मुश्किल: यह संख्या कितनी बड़ी है?',
    exp_problem_3: 'तुलना करना मुश्किल: कौन बड़ा है - पृथ्वी या यूरेनस?',
    exp_intro_solution: 'समाधान: संख्याओं को छोटे, सरल रूप में लिखने के लिए घातांक का उपयोग करें!',
    exp_example_title: 'वास्तविक दुनिया का उदाहरण',
    exp_example_before: 'पृथ्वी का द्रव्यमान = 5,970,000,000,000,000,000,000,000 किलो',
    exp_example_after: 'पृथ्वी का द्रव्यमान = 5.97 × 10²⁴ किलो',
    exp_example_benefit: 'पढ़ने और तुलना करने में बहुत आसान!',
    exp_before: 'पहले',
    exp_after: 'बाद में',
    exp_what_are_title: 'घातांक क्या हैं?',
    exp_what_are_text: 'घातांक हमें दोहरा गुणन को संक्षिप्त तरीके से लिखने देते हैं।',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'दोहरा गुणन',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'घातांक रूप',
    exp_main_example: 'मुख्य उदाहरण',
    exp_term_base: 'आधार',
    exp_term_base_def: 'गुणा होने वाली संख्या',
    exp_term_base_ex: '10⁴ में, आधार = 10',
    exp_term_exp: 'घातांक',
    exp_term_exp_def: 'आधार को कितनी बार गुणा करना है',
    exp_term_exp_ex: '10⁴ में, घातांक = 4',
    exp_term_power: 'घात',
    exp_term_power_def: 'पूरी अभिव्यक्ति',
    exp_term_power_ex: '10⁴ को "10 की घात 4" पढ़ा जाता है',
    exp_key_terms: 'याद रखने योग्य मुख्य शब्द:',
    exp_examples_title: 'उदाहरणों के साथ कार्य',
    exp_conversion_text: 'देखते हैं कि संख्याओं को घातांक रूप में कैसे परिवर्तित किया जाता है:',
    exp_example: 'उदाहरण',
    exp_step1: 'चरण 1: गुणन के रूप में लिखें',
    exp_step2: 'चरण 2: घातांक रूप में लिखें',
    exp_base: 'आधार',
    exp_exponent: 'घातांक',
    exp_read_as: 'पढ़ें',
    exp_ex1_reading: '10 की घात 3',
    exp_ex2_reading: '3 की घात 4',
    exp_ex3_reading: '5 घन',
    exp_ex4_reading: '2 की घात 5',
    exp_special_title: 'विशेष नाम',
    exp_special_intro: 'कुछ घातांकों के विशेष नाम हैं जिनका आप अक्सर उपयोग करेंगे:',
    exp_squared: 'वर्ग',
    exp_squared_read: 'वर्ग',
    exp_cubed: 'घन',
    exp_cubed_read: 'घन',
    exp_special_note: 'ये विशेष नाम ज्यामिति से आते हैं - वर्ग वर्ग के क्षेत्रफल से, घन घन के आयतन से!',
    exp_power_of: 'घात',
    exp_fun_fact: 'रोचक तथ्य',
    exp_practice_title: 'इंटरैक्टिव अभ्यास',
    exp_interactive_intro: 'खुद आजमाएं! घातांक कैसे काम करते हैं देखने के लिए आधार और घातांक को बदलें:',
    exp_expanded: 'विस्तारित रूप',
    exp_exponential_form: 'घातांक रूप',
    exp_result: 'परिणाम',
    exp_reading_title: 'पढ़ना',
    exp_raised_to: 'की घात',
    exp_or: 'या',
    of: 'का',
    example: 'उदाहरण',
    formula: 'सूत्र',
    explanation: 'स्पष्टीकरण',
    
    // Rational Numbers - Topic 8.1 (Hindi)
    rn_topic81: '8.1 परिचय',
    rn_topic82: '8.2 परिमेय संख्याओं की आवश्यकता',
    rn_progressiveExtension: 'संख्या प्रणाली का क्रमिक विस्तार',
    rn_naturalNumbers: 'प्राकृतिक संख्याएं (गिनती संख्याएं)',
    rn_naturalNumbersDesc: '1, 2, 3, 4, ...',
    rn_wholeNumbers: 'पूर्ण संख्याएं',
    rn_wholeNumbersDesc: 'शून्य सहित प्राकृतिक संख्याएं (0, 1, 2, 3, ...)',
    rn_integers: 'पूर्णांक',
    rn_integersDesc: 'पूर्ण संख्याएं और प्राकृतिक संख्याओं के ऋणात्मक (..., -3, -2, -1, 0, 1, 2, 3, ...)',
    rn_fractions: 'भिन्न',
    rn_fractionsDesc: 'अंश/हर के रूप की संख्याएं, जहाँ अंश धनात्मक पूर्णांक या शून्य है, और हर धनात्मक पूर्णांक है',
    rn_rationalNumbers: 'परिमेय संख्याएं',
    rn_rationalNumbersDesc: 'सभी संख्याएं जिन्हें p/q के रूप में लिखा जा सकता है जहाँ p और q पूर्णांक हैं और q ≠ 0',
    rn_chapterObjective: 'अध्याय का उद्देश्य',
    rn_objectiveText: 'संख्या प्रणाली को आगे बढ़ाकर परिमेय संख्याओं की अवधारणा को पेश करना और उनकी मूलभूत क्रियाओं (जोड़, घटाव, गुणा और भाग) का अध्ययन करना।',
    rn_needTitle: 'परिमेय संख्याओं की आवश्यकता',
    rn_insufficient: 'मौजूदा संख्या प्रणालियाँ अपर्याप्त क्यों हैं',
    rn_oppositeIntegers: 'पूर्णांकों के साथ विपरीत स्थितियां',
    rn_oppositeIntegersDesc: 'पूर्णांक विपरीत मात्राओं को दर्शाने के लिए उपयोग किए जाते हैं, जैसे दाईं ओर दूरी (धनात्मक 3) बनाम बाईं ओर दूरी (ऋणात्मक 5), या लाभ (धनात्मक ₹150) बनाम हानि (ऋणात्मक ₹100)।',
    rn_oppositeFractions: 'भिन्नों के साथ विपरीत स्थितियां',
    rn_oppositeFractionsDesc: 'जब इन विपरीत स्थितियों में भिन्नात्मक मात्राएं शामिल होती हैं, तो एक नए प्रकार की संख्या की आवश्यकता होती है।',
    rn_exampleAbove: 'समुद्र तल से 750m ऊपर को 3/4 किमी के रूप में लिखा जा सकता है',
    rn_exampleBelow: 'समुद्र तल से 750m नीचे को तार्किक रूप से -3/4 किमी के रूप में दर्शाया जाएगा',
    rn_gapTitle: 'संख्या प्रणाली में अंतर',
    rn_gapDesc: 'संख्या -3/4 न तो एक पूर्णांक है और न ही एक मानक भिन्न (जहाँ अंश गैर-ऋणात्मक है और हर धनात्मक है)।',
    rn_conclusion: 'निष्कर्ष',
    rn_conclusionText: 'संख्या प्रणाली को इन नई संख्याओं को शामिल करने के लिए विस्तारित किया जाना चाहिए, जिन्हें परिमेय संख्याएं कहा जाता है।',
    rn_numberLine: 'संख्या रेखा निरूपण',
    rn_seeItForm: 'संख्या रेखा पर परिमेय संख्याओं को बनते हुए देखें',
    rn_standardForm: 'मानक रूप',
    rn_seeFractionShrink: 'भिन्न को मानक रूप में सिकुड़ते हुए देखें',
    rn_equivalence: 'समतुल्यता',
    rn_seePiecesMerge: 'समानता दिखाने के लिए टुकड़ों के विलय होते हुए देखें',
    rn_visualGuidePositive: 'यह धनात्मक परिमेय संख्या ({x}) शून्य के दाएं ओर स्थित है।',
    rn_visualGuideNegative: 'यह ऋणात्मक परिमेय संख्या ({x}) शून्य के बाएं ओर स्थित है।',
    rn_practiceTitle: 'अभ्यास — कोशिश करें, देखें, सफल हों',
    rn_practiceDesc: 'एनिमेटेड संकेतों और तत्काल दृश्य प्रतिक्रिया के साथ इंटरैक्टिव समस्याएं',
    rn_typeTwoRationals: 'दो परिमेय संख्याएं टाइप करें — हम मध्यबिंदु को एनिमेट करेंगे',
    rn_checkNumbers: '\'जांच\' पर टैप करें — सही होने पर संख्याएं हरे रंग में चमकेंगी',
    rn_showHint: 'गलत हो गया? एक त्वरित संकेत चरण-दर-चरण सुधार को एनिमेट करता है',
    rn_realWorldTitle: 'वास्तविक दुनिया — जहां गणित जीवन से मिलता है',
    rn_realWorldDesc: 'एनिमेटेड आरेखों के साथ छोटे, यथार्थवादी परिदृश्य',
    rn_metersKm: 'मीटर → किलोमीटर: रूलर को सिकुड़ते हुए देखें',
    rn_slideControl: 'मान बदलने के लिए नियंत्रण स्लाइड करें और दुनिया को अपडेट होते हुए देखें',
    rn_ratiosAnimate: 'ब्याज दरें, संगीत अनुपात — प्रत्येक अनुपात को एनिमेट होते हुए देखें'
    ,
    rn_practiceHeader: 'अभ्यास प्रश्न',
    rn_practiceSub: 'आत्मविश्वास और सटीकता बढ़ाने के लिए बनाए गए अभ्यास प्रश्न।',
    sc_sessionComplete: 'सत्र पूरा',
    sc_totalQuestions: 'कुल प्रश्न',
    sc_finalGrade: 'अंतिम ग्रेड',
    sc_accuracyRate: 'सटीकता दर',
    sc_avgTime: 'प्रति प्रश्न औसत समय',
    sc_startNew: 'नया सत्र शुरू करें',
    sc_clickToSeeAnswer: 'उत्तर देखने के लिए क्लिक करें',
    sc_answer: 'उत्तर:',
    rw_title: 'वास्तविक दुनिया का उपयोग',
    rw_desc: 'देखें कि आपके आसपास की दुनिया में परिमेय संख्याएँ कैसे दिखती हैं।',
    rw_overview: 'सारांश',
    rw_calc: 'गणना',
    rw_tapToExpand: 'विस्तार के लिए टैप करें',
    rw_app_temperature_title: 'शून्य से नीचे तापमान',
    rw_app_temperature_desc: 'लेह: −5°C, दिल्ली: +10°C। शून्य के नीचे ऋणात्मक, ऊपर धनात्मक।',
    rw_app_banking_title: 'बैंकिंग — लाभ और हानि',
    rw_app_banking_desc: 'सप्ताह 1: +₹2000 लाभ; सप्ताह 2: −₹1500 हानि।',
    rw_app_sea_title: 'समुद्र तल — ऊपर और नीचे',
    rw_app_sea_desc: 'पनडुब्बी −300 m, जहाज +100 m।',
    rw_app_debt_title: 'वित्त — देनदारी और जमा',
    rw_app_debt_desc: '₹500 देनदारी (ऋणात्मक) और ₹1000 जमा (धनात्मक)।',
    rw_app_weather_title: 'मौसम — बढ़ना और घटना',
    rw_app_weather_desc: 'सुबह 8°C और 4°C की कमी → 4°C।',
    rw_app_airplane_title: 'ऊँचाई — हवाई जहाज़ का अवतरण',
    rw_app_airplane_desc: '3000 m से 1500 m तक अवतरण → −1500 m परिवर्तन।'
    ,
    bf_title: 'दो संख्याओं के बीच परिमेय संख्या खोजें',
    bf_placeholder1: 'पहली परिमेय संख्या (उदा., -3/5)',
    bf_placeholder2: 'दूसरी परिमेय संख्या (उदा., -1/2)',
    bf_tryIt: 'आजमाएँ',
    bf_retry: 'फिर से',
    bf_betweenLabel: 'इनके बीच एक परिमेय संख्या:',
    bf_invalidInput: 'अमान्य इनपुट — -3/5 या 0.4 जैसे रूप का उपयोग करें',
    bf_equalNumbers: 'संख्याएँ समान हैं — उनके बीच अनंत परिमेय संख्याएँ हैं।',
    sf_title: 'मानक रूप में बदलें',
    sf_placeholder: '36/24 या -15/20',
    sf_convert: 'बदलें',
    sf_retry: 'फिर से',
    sf_error_enter: 'कृपया एक भिन्न दर्ज करें (उदा., 36/24 या -15/20)',
    sf_error_invalid: 'अमान्य प्रारूप। कृपया रूप उपयोग करें: अंश/हर',
    sf_error_den: 'अमान्य संख्याएँ। हर शून्य नहीं हो सकता।',
    sf_resultLabel: 'मानक रूप:',
    
    // Rational Numbers - Topic 8.5
    rn85_main_title: 'संख्या रेखा पर परिमेय संख्याएं',
    rn85_main_subtitle: 'विषय 8.5',
    
    // Topic 8.5: Rational Numbers on a Number Line
    rn85_title: 'संख्या रेखा पर परिमेय संख्याएं',
    rn85_intro_title: 'मूल अवधारणा',
    rn85_intro_text: 'परिमेय संख्याओं को संख्या रेखा पर दर्शाया जा सकता है, बिल्कुल पूर्णांकों और भिन्नों की तरह।',
    rn85_placement_title: 'स्थान निर्धारण के मुख्य नियम',
    rn85_placement_subtitle: 'शून्य के सापेक्ष स्थिति:',
    rn85_positive_right: 'धनात्मक परिमेय संख्याएं → 0 के दाईं ओर अंकित',
    rn85_negative_left: 'ऋणात्मक परिमेय संख्याएं → 0 के बाईं ओर अंकित',
    rn85_zero_center: '0 → केंद्र में',
    rn85_properties_title: 'महत्वपूर्ण गुण',
    rn85_equal_distance_title: 'शून्य से समान दूरी:',
    rn85_equal_distance_text: '1/2 और -1/2 जैसी परिमेय संख्याएं 0 से समान दूरी पर हैं',
    rn85_equal_distance_ex: 'उदाहरण: 3/2 और -3/2, 0 से समान दूरी पर हैं',
    rn85_marking_title: 'अंकन के उदाहरण:',
    rn85_marking_ex1: '-1/2: 0 और -1 के बीच में स्थित',
    rn85_marking_ex2: '-3/2: -1 और -2 के बीच में स्थित',
    rn85_marking_ex3: '-1/3: 0 से 1/3 के समान दूरी पर, लेकिन बाईं ओर',
    rn85_interactive_title: 'इंटरैक्टिव संख्या रेखा',
    rn85_interactive_subtitle: 'संख्या रेखा पर परिमेय संख्याओं का अन्वेषण करें',
    
    // Topic 8.6: Rational Numbers in Standard Form
    rn86_title: 'विषय 8.6: मानक रूप में परिमेय संख्याएं',
    rn86_definition_title: 'परिभाषा',
    rn86_definition_text: 'एक परिमेय संख्या मानक रूप में होती है जब:',
    rn86_rule1: 'हर एक धनात्मक पूर्णांक हो',
    rn86_rule2: 'अंश और हर में 1 के अलावा कोई उभयनिष्ठ गुणनखंड न हो',
    rn86_rule3: 'ऋणात्मक चिह्न (यदि कोई हो) केवल अंश में हो',
    rn86_examples_title: 'उदाहरण',
    rn86_standard_form: 'मानक रूप:',
    rn86_standard_ex: '-3/5, 5/8, -2/7, 7/11',
    rn86_not_standard: 'मानक रूप में नहीं:',
    rn86_not_standard_ex: '3/-5, 45/-30, -12/24',
    rn86_convert_title: 'मानक रूप में कैसे बदलें',
    rn86_step1: 'चरण 1: अंश और हर का म.स. (महत्तम समापवर्तक) ज्ञात करें (ऋणात्मक चिह्न को अनदेखा करें)',
    rn86_step2: 'चरण 2: अंश और हर दोनों को उनके म.स. से भाग दें',
    rn86_step2_note: 'यदि हर ऋणात्मक है, तो -म.स. से भाग दें',
    rn86_examples_convert_title: 'रूपांतरण के उदाहरण:',
    rn86_ex1: '-45/30 → म.स. = 15 → (-45÷15)/(30÷15) = -3/2 ✓',
    rn86_ex2: '36/-24 → -12 से भाग दें → (36÷-12)/(-24÷-12) = -3/2 ✓',
    rn86_ex3: '-3/-15 → -3 से भाग दें → (-3÷-3)/(-15÷-3) = 1/5 ✓',
    rn86_interactive_title: 'मानक रूप में बदलें',
    rn86_interactive_subtitle: 'परिमेय संख्याओं को बदलने का अभ्यास करें',
    rn86_numerator_label: 'अंश',
    rn86_denominator_label: 'हर',
    rn86_convert_button: 'मानक रूप में बदलें',
    rn86_hcf_label: 'म.स.:',
    rn86_result_label: 'मानक रूप:',
    
    // Real World Applications (Topic 8.5)
    rw_app_temperature_title: 'तापमान पैमाना',
    rw_app_temperature_desc: 'तापमान को संख्या रेखा पर दिखाया जा सकता है, 0°C केंद्र में, धनात्मक तापमान दाईं ओर (गर्म), और ऋणात्मक तापमान बाईं ओर (ठंडा)।',
    rw_app_recipe_title: 'जल स्तर',
    rw_app_recipe_desc: 'टैंक में पानी का स्तर: सामान्य से +3/4 मीटर ऊपर (0 के दाईं ओर) या सामान्य से -3/4 मीटर नीचे (0 के बाईं ओर) संख्या रेखा पर।',
    rw_app_distance_title: 'दूरी चिह्नक',
    rw_app_distance_desc: 'सड़क चिह्नक स्थितियां दिखाते हैं: संदर्भ बिंदु से पश्चिम के लिए ऋणात्मक (-3/2 km) और पूर्व के लिए धनात्मक (+3/2 km) संख्या रेखा पर।',
    rw_app_altitude_title: 'समुद्र तल की ऊंचाई',
    rw_app_altitude_desc: 'संख्या रेखा पर ऊंचाई माप: समुद्र तल से -1/2 km नीचे (0 के बाईं ओर) और समुद्र तल से +1/2 km ऊपर (0 के दाईं ओर)।',
    rw_app_money_title: 'बैंक बैलेंस',
    rw_app_money_desc: 'संख्या रेखा पर बैंक खाता: +5/2 हजार रुपये (क्रेडिट, 0 के दाईं ओर) या -5/2 हजार रुपये (ऋण, 0 के बाईं ओर)।',
    rw_app_time_title: 'समय अंतर',
    rw_app_time_desc: 'संख्या रेखा पर समय अंतर: GMT से +5/2 घंटे आगे (0 के दाईं ओर) और GMT से -5/2 घंटे पीछे (0 के बाईं ओर)।',
    
    // Practice page questions (Rational Numbers Topic 8.5)
    pq1_prompt: 'संख्या रेखा पर परिमेय संख्या -1/2 कहाँ स्थित है?',
    pq1_explain: '-1/2, 0 के बाईं ओर 0 और -1 के बीच में स्थित है।',
    pq2_prompt: 'कौन सी परिमेय संख्याएं 0 से समान दूरी पर हैं?',
    pq2_explain: '3/4 और -3/4 जैसी परिमेय संख्याएं 0 से समान दूरी पर हैं, एक दाईं ओर और एक बाईं ओर।',
    pq3_prompt: 'संख्या रेखा पर हम धनात्मक परिमेय संख्याओं को कहाँ अंकित करते हैं?',
    pq3_explain: 'धनात्मक परिमेय संख्याओं को हमेशा संख्या रेखा पर 0 के दाईं ओर अंकित किया जाता है।',
    pq4_prompt: 'संख्या रेखा पर -3/2 कहाँ स्थित है?',
    pq4_explain: '-3/2 = -1.5, जो 0 के बाईं ओर -1 और -2 के बीच में स्थित है।',
    pq5_prompt: 'यदि 2/5 को 0 के दाईं ओर अंकित किया गया है, तो -2/5 कहाँ स्थित होगा?',
    pq5_explain: '-2/5, 0 से 2/5 के समान दूरी पर होगा, लेकिन 0 के बाईं ओर।',
    pq6_prompt: 'संख्या रेखा पर 0 से कौन अधिक दूर है?',
    pq6_explain: '3/2, 0 से 1/2 की तुलना में अधिक दूर है, क्योंकि 3/2 = 1.5 जो 1/2 = 0.5 से अधिक है।',
    // Question options
    pq1_opt1: '-1 और -2 के बीच',
    pq1_opt2: '0 और 1 के बीच',
    pq1_opt3: '0 और -1 के बीच में',
    pq1_opt4: '1 और 2 के बीच',
    pq2_opt1: '1/2 और 1/3',
    pq2_opt2: '3/4 और -3/4',
    pq2_opt3: '1/2 और 2/3',
    pq2_opt4: '5/6 और 1/6',
    pq3_opt1: '0 के बाईं ओर',
    pq3_opt2: '0 पर',
    pq3_opt3: '0 के दाईं ओर',
    pq3_opt4: 'रेखा पर कहीं भी',
    pq4_opt1: '0 और -1 के बीच',
    pq4_opt2: '-1 और -2 के बीच',
    pq4_opt3: '-2 और -3 के बीच',
    pq4_opt4: '1 और 2 के बीच',
    pq5_opt1: '0 के दाईं ओर',
    pq5_opt2: '0 के बाईं ओर',
    pq5_opt3: '2/5 के समान स्थान पर',
    pq5_opt4: '0 पर',
    pq6_opt1: '1/2',
    pq6_opt2: '3/2',
    pq6_opt3: 'दोनों समान हैं',
    pq6_opt4: 'निर्धारित नहीं कर सकते'
  },
  gu: {
    // Navigation
    home: 'ઘર',
    introduction: 'પરિચય',
    learn: 'શીખો',
    realWorld: 'વાસ્તવિક વિશ્વ',
    simpleEquations: 'સરળ સમીકરણો - ઉમેરણ',
    simpleEquationsTitle: 'સરળ સમીકરણો - ઉમેરણ',
    exponentsTitle: 'ઘાતાંક અને ઘાતનો પરિચય',
    rationalNumbersTitle: 'સંખ્યા રેખા પર પરિમેય સંખ્યાઓ અને પ્રમાણભૂત સ્વરૂપ',
    rn_titleShort: 'પરિમેય સંખ્યા',
    rn_definition: '"પરિમેય = કોઈપણ સંખ્યા p⁄q જ્યાં q ≠ 0 — તેને સંખ્યા રેખા પર જુઓ।"',
    // Exponents hero (for Learn page)
    expHeroTitle: 'ઘાતાંકનો પરિચય',
    expHeroLine1: 'ઘાતાંક વારંવારના ગુણાકાર દર્શાવવાનો શક્તિશાળી રસ્તો છે.',
    expHeroLine2: 'તે મોટી સંખ્યાઓ વાંચવા, સમજવા અને તેમ સાથે કામ કરવું સરળ બનાવે છે!',
    interactivePreview: 'ઇન્ટરેક્ટિવ પૂર્વાવલોકન',
    // 11.1 Introduction tab
    tabIntroduction: '11.1 પરિચય',
    tabExponents: '11.2 ઘાતાંક',
    massOfEarth: 'પૃથ્વીનું દળ',
    massOfUranus: 'યુરેનસનું દળ',
    distancesInSpace: 'અવકાશમાં અંતર',
    hugeNumbersReadable: 'ઘાતાંકો સાથે મોટી સંખ્યાઓ વાંચવા યોગ્ય બને છે',
    powerOf3: '5 ની ઘાત 3',
    powerOf4: '3 ની ઘાત 4',
    powerOf6: '2 ની ઘાત 6',
    // 11.2 Exponents tab
    exponentsBasicConcepts: '11.2 ઘાતાંક — મૂળભૂત ખ્યાલો',
    visualExponentialForm: 'વિઝ્યુઅલ ઘાતાંકીય સ્વરૂપ',
    base: 'આધાર',
    baseDescription: 'જે સંખ્યાનો ગુણાકાર થઈ રહ્યો છે',
    exponent: 'ઘાતાંક',
    exponentDescription: 'કેટલી વાર ગુણાકાર કરવો',
    power: 'ઘાત',
    powerDescription: 'પરિણામ',
    specialName: 'ખાસ નામ',
    squared: 'વર્ગ',
    tenSquared: '"10 નો વર્ગ"',
    cubed: 'ઘન',
    tenCubed: '"10 નો ઘન"',
    primeFactorization: 'અવિભાજ્ય અવયવીકરણ',
    primeFactorizationDesc: 'ઘાતાંકનો ઉપયોગ કરીને અવયવોને સંક્ષિપ્તમાં વ્યક્ત કરો',
    negativeBases: 'નકારાત્મક આધાર',
    generalNotation: 'સામાન્ય સંકેતલિપિ',
    generalNotationA2: 'a² = a × a',
    generalNotationA3: 'a³ = a × a × a',
    generalNotationA7: 'a⁷ = a × a × a × a × a × a × a',
    generalNotationA3B2: 'a³b² = a × a × a × b × b',
    importantPoints: 'મહત્વપૂર્ણ મુદ્દાઓ',
    pointAnyBase: 'કોઈપણ આધારનો ઉપયોગ કરી શકાય છે — ફક્ત 10 જ નહીં',
    pointExponentialForm: 'ઘાતાંકીય સ્વરૂપ મોટી સંખ્યાઓ સાથે કામ કરવાનું સરળ બનાવે છે',
    pointPrimeFactorization: 'અવિભાજ્ય અવયવીકરણ ઘાતાંક સાથે સંક્ષિપ્ત હોય છે',
    
    // Home Page
    masterSimpleEquations: 'સરળ સમીકરણોમાં નિપુણતા મેળવો',
    masterClass7Mathematics: 'એનસીઇઆરટી અભ્યાસક્રમના આધારે ઇન્ટરેક્ટિવ શીખવા, પ્રેક્ટિસ કસરતો અને આકર્ષક રમતો સાથે ધોરણ 7 ગણિતમાં નિપુણતા મેળવો',
    startLearning: 'શીખવાનું શરૂ કરો',
    whatYoullLearn: 'તમે શું શીખશો',
    comprehensiveTools: 'સરળ સમીકરણોને શીખવાનું આકર્ષક અને અસરકારક બનાવવા માટે ડિઝાઇન કરેલા વ્યાપક સાધનો',
    introductionDesc: 'ઇન્ટરેક્ટિવ ઉદાહરણો સાથે સરળ સમીકરણોની મૂળભૂત વાતો શીખો',
    learnDesc: 'વિઝ્યુઅલ સહાયતા સાથે પગલું-દર-પગલું સ્પષ્ટતા',
    practiceDesc: 'કસરતો હલ કરો અને તમારા ઉકેલો તપાસો',
    realWorldDesc: 'જુઓ કે સમીકરણો રોજિંદા જીવનમાં કેવી રીતે લાગુ પડે છે',
    practiceProblems: 'પ્રેક્ટિસ સમસ્યાઓ',
    interactiveExamples: 'ઇન્ટરેક્ટિવ ઉદાહરણો',
    readyToMaster: 'સરળ સમીકરણોમાં નિપુણતા મેળવવા માટે તૈયાર છો?',
    joinThousands: 'હજારો વિદ્યાર્થીઓ અને શિક્ષકોમાં જોડાઓ જે ગણિતને આકર્ષક અને સુલભ બનાવી રહ્યા છે.',
    startYourJourney: 'તમારી યાત્રા શરૂ કરો',
    
    // Common
    correct: 'સાચું!',
    incorrect: 'ફરી કોશિશ કરો!',
    notQuite: 'બિલકુલ બરાબર નહીં.',
    learning: 'શીખવું',
    practice: 'પ્રેક્ટિસ',
    assessment: 'મૂલ્યાંકન',
    selectEquation: 'સમીકરણ પસંદ કરો:',
    yourAnswer: 'તમારો જવાબ:',
    submit: 'સબમિટ',
    hint: 'સંકેત',
    progress: 'પ્રગતિ:',
    accuracy: 'ચોકસાઈ',
    avgTime: 'સરેરાશ સમય',
    correctAnswers: 'સાચું',
    incorrectAnswers: 'ખોટું',
    totalExercises: 'કુલ',
    excellent: 'ઉત્તમ!',
    goodJob: 'સારું કામ!',
    keepTrying: 'કોશિશ કરતા રહો!',
    showSolution: 'ઉકેલ બતાવો',
    hideSolution: 'ઉકેલ છુપાવો',
    reset: 'રીસેટ',
    stepByStepSolution: 'પગલું-દર-પગલું ઉકેલ:',
    nextStep: 'આગળનું પગલું',
    complete: 'પૂર્ણ',
    
    // Real World
    realWorldApps: 'વાસ્તવિક વિશ્વના ઉપયોગો',
    selectCategory: 'શ્રેણી પસંદ કરો:',
    difficulty: 'મુશ્કેલી:',
    beginner: 'શરૂઆત',
    intermediate: 'મધ્યમ',
    advanced: 'અદ્યતન',
    equation: 'સમીકરણ:',
    solution: 'ઉકેલ:',
    context: 'સંદર્ભ:',
    shopping: 'ખરીદી',
    cooking: 'રસોઈ',
    construction: 'બાંધકામ',
    sports: 'રમત',
    finance: 'વિત્ત',
    science: 'વિજ્ઞાન',
    
    // Learn Section
    linearEquations: 'રેખીય સમીકરણો',
    linearEquationsDesc: 'રેખીય સમીકરણો એવા સમીકરણો છે જ્યાં ચલની સર્વોચ્ચ ઘાત 1 છે. તેમને જોડાણ, બાદબાકી, ગુણાકાર અને ભાગાકાર જેવી મૂળભૂત બીજગણિતીય ક્રિયાઓનો ઉપયોગ કરીને હલ કરી શકાય છે.',
    solvingByAddition: 'જોડાણ દ્વારા હલ કરવું',
    solvingByAdditionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં બાદબાકી હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓમાં સમાન સંખ્યા ઉમેરીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingBySubtraction: 'બાદબાકી દ્વારા હલ કરવું',
    solvingBySubtractionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં જોડાણ હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓમાંથી સમાન સંખ્યા બાદ કરીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingByMultiplication: 'ગુણાકાર દ્વારા હલ કરવું',
    solvingByMultiplicationDesc: 'જ્યારે આપણી પાસે સમીકરણમાં ભાગાકાર હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓને સમાન સંખ્યા વડે ગુણીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    solvingByDivision: 'ભાગાકાર દ્વારા હલ કરવું',
    solvingByDivisionDesc: 'જ્યારે આપણી પાસે સમીકરણમાં ગુણાકાર હોય છે, ત્યારે આપણે ચલને અલગ કરવા માટે બંને બાજુઓને સમાન સંખ્યા વડે ભાગીએ છીએ. આ સમીકરણનું સંતુલન જાળવે છે.',
    originalEquation: 'મૂળ સમીકરણ',
    originalEquationWithSubtraction: 'બાદબાકી સાથે મૂળ સમીકરણ',
    originalEquationWithAddition: 'જોડાણ સાથે મૂળ સમીકરણ',
    originalEquationWithDivision: 'ભાગાકાર સાથે મૂળ સમીકરણ',
    originalEquationWithMultiplication: 'ગુણાકાર સાથે મૂળ સમીકરણ',
    subtractFromBothSides: 'બંને બાજુઓમાંથી 5 બાદ કરો',
    addToBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓમાં 3 ઉમેરો',
    subtractFromBothSidesToIsolate: 'x ને અલગ કરવા માટે બંને બાજુઓમાંથી 4 બાદ કરો',
    multiplyBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓને 3 વડે ગુણો',
    divideBothSides: 'x ને અલગ કરવા માટે બંને બાજુઓને 3 વડે ભાગો',
    simplifyToFindAnswer: 'જવાબ શોધવા માટે સરળ બનાવો',
    simplifyStep: 'સરળ બનાવો: 5 - 5 = 0 અને 12 - 5 = 7',
    verifySolution: 'x = 7 મૂકીને ઉકેલ ચકાસો',
    simplifyAdditionStep: 'સરળ બનાવો: -3 + 3 = 0 અને 8 + 3 = 11',
    verifyAdditionSolution: 'x = 11 મૂકીને ઉકેલ ચકાસો',
    simplifySubtractionStep: 'સરળ બનાવો: 4 - 4 = 0 અને 7 - 4 = 3',
    verifySubtractionSolution: 'x = 3 મૂકીને ઉકેલ ચકાસો',
    simplifyMultiplicationStep: 'સરળ બનાવો: 3/3 = 1 અને 4 × 3 = 12',
    verifyMultiplicationSolution: 'x = 12 મૂકીને ઉકેલ ચકાસો',
    simplifyDivisionStep: 'સરળ બનાવો: 3x ÷ 3 = x અને 15 ÷ 3 = 5',
    verifyDivisionSolution: 'x = 5 મૂકીને ઉકેલ ચકાસો',
    linearEquationExample: 'રેખીય સમીકરણ ઉદાહરણ',
    additionMethodExample: 'જોડાણ પદ્ધતિ ઉદાહરણ',
    subtractionMethodExample: 'બાદબાકી પદ્ધતિ ઉદાહરણ',
    multiplicationMethodExample: 'ગુણાકાર પદ્ધતિ ઉદાહરણ',
    divisionMethodExample: 'ભાગાકાર પદ્ધતિ ઉદાહરણ',
    solving: 'હલ કરવું:',
    play: 'ચલાવો',
    pause: 'રોકો',
    previous: 'પાછલું',
    next: 'આગળનું',
    
    // Practice Mode
    practiceMode: 'પ્રેક્ટિસ મોડ',
    question: 'પ્રશ્ન',
    skippedQuestions: 'છોડેલા પ્રશ્નો',
    notAttempted: 'પ્રયાસ નથી કર્યો',
    totalQuestions: 'કુલ પ્રશ્નો',
    finalGrade: 'અંતિમ ગ્રેડ',
    accuracyRate: 'ચોકસાઈ દર',
    avgTimePerQuestion: 'પ્રતિ પ્રશ્ન સરેરાશ સમય',
    questionByQuestionReview: 'પ્રશ્ન દર પ્રશ્ન સમીક્ષા',
    startNewSession: 'નવો સત્ર શરૂ કરો',
    loadingQuestions: 'પ્રશ્નો લોડ થઈ રહ્યા છે...',
    showAnswer: 'જવાબ બતાવો',
    hideAnswer: 'જવાબ છુપાવો',
    tryAgain: 'ફરી કોશિશ કરો',
    skip: 'છોડો',
    skipped: 'છોડાયેલું',
    sessionComplete: 'સત્ર પૂર્ણ!',
    sessionSummary: 'અહીં તમારો સંપૂર્ણ સત્ર સારાંશ છે',
    correctAnswer: 'સાચો જવાબ',
    check: 'તપાસ',
    notAttempt: 'પ્રયાસ ન કરો',
    
    // Practice Questions - Exponents
    q1_prompt: '10,000 ને ઘાતાંકીય સ્વરૂપમાં રૂપાંતરિત કરો',
    q1_explanation: '10,000 = 10 × 10 × 10 × 10 = 10⁴',
    q2_prompt: '5³ શું છે?',
    q2_explanation: '5³ = 5 × 5 × 5 = 125',
    q3_prompt: '7⁴ માં આધાર શું છે?',
    q3_explanation: '7⁴ માં, 7 એ આધાર છે (જે સંખ્યાને ગુણાકાર કરવામાં આવી રહી છે)',
    q4_prompt: '2⁵ માં ઘાતાંક શું છે?',
    q4_explanation: '2⁵ માં, 5 એ ઘાતાંક છે (દર્શાવે છે કે 2 કેટલી વાર ગુણાકાર થાય છે)',
    q5_prompt: '3⁴ ની ગણતરી કરો',
    q5_explanation: '3⁴ = 3 × 3 × 3 × 3 = 81',
    q6_prompt: '100 ઘાતાંકીય સ્વરૂપમાં શું છે?',
    q6_explanation: '100 = 10 × 10 = 10²',
    
    // Practice Questions
    practice_q1: 'હલ કરો: x + 7 = 15',
    practice_q2: 'હલ કરો: x + 4 = 12',
    practice_q3: 'હલ કરો: x + 3 = 21',
    practice_q4: 'હલ કરો: x + 2 = 8',
    practice_q5: 'હલ કરો: x + 3 = 11',
    practice_q6: 'હલ કરો: x + 5 = 9',
    practice_q7: 'હલ કરો: x + 6 = 18',
    practice_q8: 'હલ કરો: x + 2 = 7',
    practice_q9: 'હલ કરો: x + 8 = 33',
    practice_q10: 'હલ કરો: x + 7 = 13',
    practice_q11: 'હલ કરો: x + 3 = 8',
    practice_q12: 'હલ કરો: x + 12 = 30',
    
    // Exponents
    exp_intro_title: 'ઘાતાંકની જરૂર કેમ છે?',
    exp_intro_text: 'ખૂબ મોટી સંખ્યાઓ સાથે કામ કરવું મુશ્કેલ છે:',
    exp_problem_1: 'વાંચવું મુશ્કેલ: 5,970,000,000,000,000,000,000,000 કિલો',
    exp_problem_2: 'સમજવું મુશ્કેલ: આ સંખ્યા કેટલી મોટી છે?',
    exp_problem_3: 'સરખામણી કરવી મુશ્કેલ: કયું મોટું છે - પૃથ્વી કે યુરેનસ?',
    exp_intro_solution: 'ઉકેલ: સંખ્યાઓને ટૂંકા, સરળ સ્વરૂપમાં લખવા માટે ઘાતાંકનો ઉપયોગ કરો!',
    exp_example_title: 'વાસ્તવિક વિશ્વનું ઉદાહરણ',
    exp_example_before: 'પૃથ્વીનું વજન = 5,970,000,000,000,000,000,000,000 કિલો',
    exp_example_after: 'પૃથ્વીનું વજન = 5.97 × 10²⁴ કિલો',
    exp_example_benefit: 'વાંચવા અને સરખામણી કરવામાં ખૂબ સરળ!',
    exp_before: 'પહેલાં',
    exp_after: 'પછી',
    exp_what_are_title: 'ઘાતાંક શું છે?',
    exp_what_are_text: 'ઘાતાંક આપણને પુનરાવર્તિત ગુણાકારને સંક્ષિપ્ત રીતે લખવા દે છે.',
    exp_main_problem: '10,000 = ?',
    exp_main_step1: '10,000 = 10 × 10 × 10 × 10',
    exp_main_step1_label: 'પુનરાવર્તિત ગુણાકાર',
    exp_main_step2: '10,000 = 10⁴',
    exp_main_step2_label: 'ઘાતાંક સ્વરૂપ',
    exp_main_example: 'મુખ્ય ઉદાહરણ',
    exp_term_base: 'આધાર',
    exp_term_base_def: 'ગુણાકારમાં લેવાતી સંખ્યા',
    exp_term_base_ex: '10⁴ માં, આધાર = 10',
    exp_term_exp: 'ઘાતાંક',
    exp_term_exp_def: 'આધારને કેટલી વાર ગુણાકાર કરવો છે',
    exp_term_exp_ex: '10⁴ માં, ઘાતાંક = 4',
    exp_term_power: 'ઘાત',
    exp_term_power_def: 'સંપૂર્ણ અભિવ્યક્તિ',
    exp_term_power_ex: '10⁴ ને "10 ની ઘાત 4" તરીકે વાંચવામાં આવે છે',
    exp_key_terms: 'યાદ રાખવા યોગ્ય મુખ્ય શબ્દો:',
    exp_examples_title: 'ઉદાહરણો સાથે કામ',
    exp_conversion_text: 'જુઓ કે સંખ્યાઓને ઘાતાંક સ્વરૂપમાં કેવી રીતે બદલવામાં આવે છે:',
    exp_example: 'ઉદાહરણ',
    exp_step1: 'પગલું 1: ગુણાકાર તરીકે લખો',
    exp_step2: 'પગલું 2: ઘાતાંક સ્વરૂપમાં લખો',
    exp_base: 'આધાર',
    exp_exponent: 'ઘાતાંક',
    exp_read_as: 'વાંચો',
    exp_ex1_reading: '10 ની ઘાત 3',
    exp_ex2_reading: '3 ની ઘાત 4',
    exp_ex3_reading: '5 ઘન',
    exp_ex4_reading: '2 ની ઘાત 5',
    exp_special_title: 'વિશેષ નામો',
    exp_special_intro: 'કેટલાક ઘાતાંકોનાં વિશેષ નામો છે જેનો તમે ઘણી વાર ઉપયોગ કરશો:',
    exp_squared: 'વર્ગ',
    exp_squared_read: 'વર્ગ',
    exp_cubed: 'ઘન',
    exp_cubed_read: 'ઘન',
    exp_special_note: 'આ વિશેષ નામો ભૂમિતિમાંથી આવે છે - વર્ગ ચોરસના ક્ષેત્રફળમાંથી, ઘન ઘનના ઘનફળમાંથી!',
    exp_power_of: 'ઘાત',
    exp_fun_fact: 'રસપ્રદ તથ્ય',
    exp_practice_title: 'ઇન્ટરેક્ટિવ પ્રેક્ટિસ',
    exp_interactive_intro: 'જાતે અજમાવો! ઘાતાંક કેવી રીતે કામ કરે છે તે જોવા માટે આધાર અને ઘાતાંક બદલો:',
    exp_expanded: 'વિસ્તૃત સ્વરૂપ',
    exp_exponential_form: 'ઘાતાંક સ્વરૂપ',
    exp_result: 'પરિણામ',
    exp_reading_title: 'વાંચન',
    exp_raised_to: 'ની ઘાત',
    exp_or: 'અથવા',
    of: 'નું',
    example: 'ઉદાહરણ',
    formula: 'સૂત્ર',
    explanation: 'સ્પષ્ટતા',
    
    // Rational Numbers - Topic 8.1 (Gujarati)
    rn_topic81: '8.1 પરિચય',
    rn_topic82: '8.2 પરિમેય સંખ્યાઓની જરૂરિયાત',
    rn_progressiveExtension: 'સંખ્યા પ્રણાલીનું પ્રગતિશીલ વિસ્તરણ',
    rn_naturalNumbers: 'કુદરતી સંખ્યાઓ (ગણતરીની સંખ્યાઓ)',
    rn_naturalNumbersDesc: '1, 2, 3, 4, ...',
    rn_wholeNumbers: 'પૂર્ણાંક સંખ્યાઓ',
    rn_wholeNumbersDesc: 'શૂન્ય સહિત કુદરતી સંખ્યાઓ (0, 1, 2, 3, ...)',
    rn_integers: 'પૂર્ણાંકો',
    rn_integersDesc: 'પૂર્ણાંક સંખ્યાઓ અને કુદરતી સંખ્યાઓના નકારાત્મક (..., -3, -2, -1, 0, 1, 2, 3, ...)',
    rn_fractions: 'અપૂર્ણાંકો',
    rn_fractionsDesc: 'અંશ/છેદના સ્વરૂપની સંખ્યાઓ, જ્યાં અંશ ધનાત્મક પૂર્ણાંક અથવા શૂન્ય છે, અને છેદ ધનાત્મક પૂર્ણાંક છે',
    rn_rationalNumbers: 'પરિમેય સંખ્યાઓ',
    rn_rationalNumbersDesc: 'બધી સંખ્યાઓ જેને p/q તરીકે લખી શકાય છે જ્યાં p અને q પૂર્ણાંકો છે અને q ≠ 0',
    rn_chapterObjective: 'અધ્યાયનો ઉદ્દેશ્ય',
    rn_objectiveText: 'સંખ્યા પ્રણાલીને આગળ વધારીને પરિમેય સંખ્યાઓની સંકલ્પના દાખલ કરવી અને તેમની મૂળભૂત ક્રિયાઓ (ઉમેરણ, બાદબાકી, ગુણાકાર અને ભાગાકાર)નો અભ્યાસ કરવો।',
    rn_needTitle: 'પરિમેય સંખ્યાઓની જરૂરિયાત',
    rn_insufficient: 'હાલની સંખ્યા પ્રણાલીઓ શા માટે અપૂર્ણ છે',
    rn_oppositeIntegers: 'પૂર્ણાંકો સાથે વિપરીત પરિસ્થિતિઓ',
    rn_oppositeIntegersDesc: 'પૂર્ણાંકો વિપરીત માત્રાઓ દર્શાવવા માટે ઉપયોગમાં લેવાય છે, જેમ કે જમણી તરફ અંતર (ધનાત્મક 3) વિરુદ્ધ ડાબી તરફ અંતર (નકારાત્મક 5), અથવા નફો (ધનાત્મક ₹150) વિરુદ્ધ ખોટ (નકારાત્મક ₹100)।',
    rn_oppositeFractions: 'અપૂર્ણાંકો સાથે વિપરીત પરિસ્થિતિઓ',
    rn_oppositeFractionsDesc: 'જ્યારે આ વિપરીત પરિસ્થિતિઓમાં અપૂર્ણાંક માત્રાઓ સામેલ હોય છે, ત્યારે નવા પ્રકારની સંખ્યાની જરૂર પડે છે।',
    rn_exampleAbove: 'સમુદ્ર સપાટીથી 750m ઉપર 3/4 કિમી તરીકે લખી શકાય છે',
    rn_exampleBelow: 'સમુદ્ર સપાટીથી 750m નીચે લોજિકલ રીતે -3/4 કિમી તરીકે રજૂ કરવામાં આવશે',
    rn_gapTitle: 'સંખ્યા પ્રણાલીમાં ખાલી જગ્યા',
    rn_gapDesc: 'સંખ્યા -3/4 ન તો પૂર્ણાંક છે અને ન તો માનક અપૂર્ણાંક (જ્યાં અંશ બિન-નકારાત્મક છે અને છેદ ધનાત્મક છે)।',
    rn_conclusion: 'નિષ્કર્ષ',
    rn_conclusionText: 'સંખ્યા પ્રણાલીને આ નવી સંખ્યાઓને સામેલ કરવા માટે વિસ્તારવી જોઈએ, જેને પરિમેય સંખ્યાઓ કહેવામાં આવે છે।',
    rn_numberLine: 'સંખ્યા રેખા રજૂઆત',
    rn_seeItForm: 'સંખ્યા રેખા પર પરિમેય સંખ્યાઓ બનતી જુઓ',
    rn_standardForm: 'માનક સ્વરૂપ',
    rn_seeFractionShrink: 'અપૂર્ણાંકને માનક સ્વરૂપમાં સંકોચાતી જુઓ',
    rn_equivalence: 'સમાનતા',
    rn_seePiecesMerge: 'સમાનતા બતાવવા માટે ટુકડાઓ મર્જ થતા જુઓ',
    rn_visualGuidePositive: 'આ ધાર્મિક પરિમેય સંખ્યા ({x}) શૂન્યના જમણા બાજુએ છે.',
    rn_visualGuideNegative: 'આ નકારાત્મક પરિમેય સંખ્યા ({x}) શૂન્યના ડાબા બાજુએ છે.',
    rn_practiceTitle: 'પ્રેક્ટિસ — કોશિશ કરો, જુઓ, સફળ થાઓ',
    rn_practiceDesc: 'એનિમેટેડ સંકેતો અને તાત્કાલિક દ્રશ્ય પ્રતિસાદ સાથે ઇન્ટરેક્ટિવ સમસ્યાઓ',
    rn_typeTwoRationals: 'બે પરિમેય સંખ્યાઓ ટાઇપ કરો — અમે મધ્યબિંદુને એનિમેટ કરીશું',
    rn_checkNumbers: '\'તપાસ\' પર ટેપ કરો — સાચું હોવા પર સંખ્યાઓ લીલા રંગમાં ચમકશે',
    rn_showHint: 'ખોટું થયું? એક ઝડપી સંકેત પગલું-દર-પગલું સુધારાને એનિમેટ કરે છે',
    rn_realWorldTitle: 'વાસ્તવિક વિશ્વ — જ્યાં ગણિત જીવન સાથે મળે છે',
    rn_realWorldDesc: 'એનિમેટેડ આકૃતિઓ સાથે ટૂંકા, વાસ્તવિક સ્થિતિઓ',
    rn_metersKm: 'મીટર → કિલોમીટર: રૂલર સંકોચાતો જુઓ',
    rn_slideControl: 'મૂલ્ય બદલવા માટે નિયંત્રણ સ્લાઇડ કરો અને વિશ્વને અપડેટ થતો જુઓ',
    rn_ratiosAnimate: 'વ્યાજ દરો, સંગીત ગુણોત્તર — દરેક ગુણોત્તરને એનિમેટ થતો જુઓ'
    ,
    rn_practiceHeader: 'પ્રેક્ટિસ પ્રશ્ન',
    rn_practiceSub: 'આત્મવિશ્વાસ અને ચોકસાઈ વધારવા માટે બનાવેલા પ્રેક્ટિસ પ્રશ્નો.',
    sc_sessionComplete: 'સત્ર પૂર્ણ',
    sc_totalQuestions: 'કુલ પ્રશ્નો',
    sc_finalGrade: 'અંતિમ ગ્રેડ',
    sc_accuracyRate: 'ચોકસાઈ દર',
    sc_avgTime: 'પ્રતિ પ્રશ્ન સરેરાશ સમય',
    sc_startNew: 'નવો સત્ર શરૂ કરો',
    sc_clickToSeeAnswer: 'જવાબ જોવા માટે ક્લિક કરો',
    sc_answer: 'જવાબ:',
    rw_title: 'વાસ્તવિક વિશ્વનો ઉપયોગ',
    rw_desc: 'જુઓ કે તમારા આસપાસની દુનિયામાં પરિમેય સંખ્યાઓ કેવી રીતે દેખાય છે.',
    rw_overview: 'સારાંશ',
    rw_calc: 'ગણતરી',
    rw_tapToExpand: 'વિસ્તાર માટે ટેપ કરો',
    rw_app_temperature_title: 'શૂન્યથી નીચે તાપમાન',
    rw_app_temperature_desc: 'લેહ: −5°C, દિલ્હી: +10°C. શૂન્યથી નીચે નકારાત્મક, ઉપર ધાર્મિક.',
    rw_app_banking_title: 'બેન્કિંગ — નફો અને નુકસાન',
    rw_app_banking_desc: 'અઠવાડિયું 1: +₹2000 નફો; અઠવાડિયું 2: −₹1500 નુકસાન.',
    rw_app_sea_title: 'સમુદ્ર સપાટી — ઉપર અને નીચે',
    rw_app_sea_desc: 'પડખીયું −300 m, જહાજ +100 m.',
    rw_app_debt_title: 'વित्त — દેવું અને જમા',
    rw_app_debt_desc: '₹500 દેવું (નકારાત્મક) અને ₹1000 જમા (ધાર્મિક).',
    rw_app_weather_title: 'હવામાન — વધારો અને ઘટાડો',
    rw_app_weather_desc: 'સવારે 8°C અને 4°C ઘટાડો → 4°C.',
    rw_app_airplane_title: 'ઊંચાઈ — વિમાનનું અવતરણ',
    rw_app_airplane_desc: '3000 m થી 1500 m સુધી અવતરણ → −1500 m બદલાવ.'
    ,
    bf_title: 'બે સંખ્યાઓ વચ્ચે પરિમેય સંખ્યા શોધો',
    bf_placeholder1: 'પ્રથમ પરિમેય સંખ્યા (ઉદાહરણ, -3/5)',
    bf_placeholder2: 'બીજી પરિમેય સંખ્યા (ઉદાહરણ, -1/2)',
    bf_tryIt: 'અજમાવો',
    bf_retry: 'ફરીથી',
    bf_betweenLabel: 'તેમનાં વચ્ચેની એક પરિમેય સંખ્યા:',
    bf_invalidInput: 'અમાન્ય ઇનપુટ — -3/5 અથવા 0.4 જેવા સ્વરૂપનો ઉપયોગ કરો',
    bf_equalNumbers: 'સંખ્યા સમાન છે — તેમના વચ્ચે અસીમિત પરિમેય સંખ્યાઓ છે.',
    sf_title: 'માનક સ્વરૂપમાં રૂપાંતર કરો',
    sf_placeholder: '36/24 અથવા -15/20',
    sf_convert: 'રૂપાંતરિત કરો',
    sf_retry: 'ફરીથી',
    sf_error_enter: 'કૃપા કરીને એક અપૂર્ણાંક દાખલ કરો (ઉદાહરણ, 36/24 અથવા -15/20)',
    sf_error_invalid: 'અમાન્ય સ્વરૂપ. કૃપા કરીને સ્વરૂપનો ઉપયોગ કરો: અંશ/છેદ',
    sf_error_den: 'અમાન્ય સંખ્યાઓ. છેદ શૂન્ય ન હોઈ શકે.',
    sf_resultLabel: 'માનક સ્વરૂપ:',
    
    // Rational Numbers - Topic 8.5
    rn85_main_title: 'સંખ્યા રેખા પર પરિમેય સંખ્યાઓ',
    rn85_main_subtitle: 'વિષય 8.5',
    
    // Topic 8.5: Rational Numbers on a Number Line
    rn85_title: 'સંખ્યા રેખા પર પરિમેય સંખ્યાઓ',
    rn85_intro_title: 'મૂળભૂત ખ્યાલ',
    rn85_intro_text: 'પરિમેય સંખ્યાઓ સંખ્યા રેખા પર દર્શાવી શકાય છે, બરાબર પૂર્ણાંકો અને અપૂર્ણાંકોની જેમ.',
    rn85_placement_title: 'સ્થાનનિર્ધારણના મુખ્ય નિયમો',
    rn85_placement_subtitle: 'શૂન્યની તુલનામાં સ્થાન:',
    rn85_positive_right: 'હકારાત્મક પરિમેય સંખ્યાઓ → 0 ની જમણી બાજુએ ચિહ્નિત',
    rn85_negative_left: 'નકારાત્મક પરિમેય સંખ્યાઓ → 0 ની ડાબી બાજુએ ચિહ્નિત',
    rn85_zero_center: '0 → કેન્દ્રમાં',
    rn85_properties_title: 'મહત્વપૂર્ણ ગુણધર્મો',
    rn85_equal_distance_title: 'શૂન્યથી સમાન અંતર:',
    rn85_equal_distance_text: '1/2 અને -1/2 જેવી પરિમેય સંખ્યાઓ 0 થી સમાન અંતરે છે',
    rn85_equal_distance_ex: 'ઉદાહરણો: 3/2 અને -3/2, 0 થી સમાન અંતરે છે',
    rn85_marking_title: 'ચિહ્નિત કરવાના ઉદાહરણો:',
    rn85_marking_ex1: '-1/2: 0 અને -1 ની વચ્ચે આવેલ છે',
    rn85_marking_ex2: '-3/2: -1 અને -2 ની વચ્ચે આવેલ છે',
    rn85_marking_ex3: '-1/3: 0 થી 1/3 જેટલા અંતરે, પરંતુ ડાબી બાજુએ',
    rn85_interactive_title: 'ઇન્ટરેક્ટિવ સંખ્યા રેખા',
    rn85_interactive_subtitle: 'સંખ્યા રેખા પર પરિમેય સંખ્યાઓ શોધો',
    
    // Topic 8.6: Rational Numbers in Standard Form
    rn86_title: 'વિષય 8.6: પ્રમાણભૂત સ્વરૂપમાં પરિમેય સંખ્યાઓ',
    rn86_definition_title: 'વ્યાખ્યા',
    rn86_definition_text: 'પરિમેય સંખ્યા પ્રમાણભૂત સ્વરૂપમાં હોય જ્યારે:',
    rn86_rule1: 'છેદ હકારાત્મક પૂર્ણાંક હોય',
    rn86_rule2: 'અંશ અને છેદમાં 1 સિવાય કોઈ સામાન્ય અવયવ ન હોય',
    rn86_rule3: 'નકારાત્મક ચિહ્ન (જો હોય તો) ફક્ત અંશમાં હોય',
    rn86_examples_title: 'ઉદાહરણો',
    rn86_standard_form: 'પ્રમાણભૂત સ્વરૂપ:',
    rn86_standard_ex: '-3/5, 5/8, -2/7, 7/11',
    rn86_not_standard: 'પ્રમાણભૂત સ્વરૂપમાં નહીં:',
    rn86_not_standard_ex: '3/-5, 45/-30, -12/24',
    rn86_convert_title: 'પ્રમાણભૂત સ્વરૂપમાં કેવી રીતે બદલવું',
    rn86_step1: 'પગલું 1: અંશ અને છેદનો મ.સા. (મહત્તમ સામાન્ય અવયવ) શોધો (નકારાત્મક ચિહ્ન અવગણો)',
    rn86_step2: 'પગલું 2: અંશ અને છેદ બંનેને તેમના મ.સા. વડે ભાગો',
    rn86_step2_note: 'જો છેદ નકારાત્મક હોય, તો -મ.સા. વડે ભાગો',
    rn86_examples_convert_title: 'રૂપાંતરણના ઉદાહરણો:',
    rn86_ex1: '-45/30 → મ.સા. = 15 → (-45÷15)/(30÷15) = -3/2 ✓',
    rn86_ex2: '36/-24 → -12 વડે ભાગો → (36÷-12)/(-24÷-12) = -3/2 ✓',
    rn86_ex3: '-3/-15 → -3 વડે ભાગો → (-3÷-3)/(-15÷-3) = 1/5 ✓',
    rn86_interactive_title: 'પ્રમાણભૂત સ્વરૂપમાં બદલો',
    rn86_interactive_subtitle: 'પરિમેય સંખ્યાઓ બદલવાની પ્રેક્ટિસ કરો',
    rn86_numerator_label: 'અંશ',
    rn86_denominator_label: 'છેદ',
    rn86_convert_button: 'પ્રમાણભૂત સ્વરૂપમાં બદલો',
    rn86_hcf_label: 'મ.સા.:',
    rn86_result_label: 'પ્રમાણભૂત સ્વરૂપ:',
    
    // Real World Applications (Topic 8.5)
    rw_app_temperature_title: 'તાપમાન સ્કેલ',
    rw_app_temperature_desc: 'તાપમાનને સંખ્યા રેખા પર બતાવી શકાય છે, 0°C કેન્દ્રમાં, હકારાત્મક તાપમાન જમણી બાજુ (ગરમ), અને નકારાત્મક તાપમાન ડાબી બાજુ (ઠંડું).',
    rw_app_recipe_title: 'પાણીનું સ્તર',
    rw_app_recipe_desc: 'ટાંકીમાં પાણીનું સ્તર: સામાન્ય કરતાં +3/4 મીટર ઉપર (0 ની જમણી બાજુ) અથવા સામાન્ય કરતાં -3/4 મીટર નીચે (0 ની ડાબી બાજુ) સંખ્યા રેખા પર.',
    rw_app_distance_title: 'અંતર ચિહ્નકો',
    rw_app_distance_desc: 'રોડ ચિહ્નકો સ્થાનો બતાવે છે: સંદર્ભ બિંદુથી પશ્ચિમ માટે નકારાત્મક (-3/2 km) અને પૂર્વ માટે હકારાત્મક (+3/2 km) સંખ્યા રેખા પર.',
    rw_app_altitude_title: 'સમુદ્ર સપાટીની ઊંચાઈ',
    rw_app_altitude_desc: 'સંખ્યા રેખા પર ઊંચાઈ માપ: સમુદ્ર સપાટીથી -1/2 km નીચે (0 ની ડાબી બાજુ) અને સમુદ્ર સપાટીથી +1/2 km ઉપર (0 ની જમણી બાજુ).',
    rw_app_money_title: 'બેંક બેલેન્સ',
    rw_app_money_desc: 'સંખ્યા રેખા પર બેંક ખાતું: +5/2 હજાર રૂપિયા (ક્રેડિટ, 0 ની જમણી બાજુ) અથવા -5/2 હજાર રૂપિયા (દેવું, 0 ની ડાબી બાજુ).',
    rw_app_time_title: 'સમય તફાવત',
    rw_app_time_desc: 'સંખ્યા રેખા પર સમય તફાવત: GMT થી +5/2 કલાક આગળ (0 ની જમણી બાજુ) અને GMT થી -5/2 કલાક પાછળ (0 ની ડાબી બાજુ).',
    
    // Practice page questions (Rational Numbers Topic 8.5)
    pq1_prompt: 'સંખ્યા રેખા પર પરિમેય સંખ્યા -1/2 ક્યાં આવેલી છે?',
    pq1_explain: '-1/2, 0 ની ડાબી બાજુએ 0 અને -1 ની વચ્ચે આવેલ છે.',
    pq2_prompt: 'કઈ પરિમેય સંખ્યાઓ 0 થી સમાન અંતરે છે?',
    pq2_explain: '3/4 અને -3/4 જેવી પરિમેય સંખ્યાઓ 0 થી સમાન અંતરે છે, એક જમણી બાજુ અને એક ડાબી બાજુ.',
    pq3_prompt: 'સંખ્યા રેખા પર આપણે હકારાત્મક પરિમેય સંખ્યાઓ ક્યાં ચિહ્નિત કરીએ છીએ?',
    pq3_explain: 'હકારાત્મક પરિમેય સંખ્યાઓ હંમેશા સંખ્યા રેખા પર 0 ની જમણી બાજુએ ચિહ્નિત કરવામાં આવે છે.',
    pq4_prompt: 'સંખ્યા રેખા પર -3/2 ક્યાં આવેલ છે?',
    pq4_explain: '-3/2 = -1.5, જે 0 ની ડાબી બાજુએ -1 અને -2 ની વચ્ચે આવેલ છે.',
    pq5_prompt: 'જો 2/5 ને 0 ની જમણી બાજુએ ચિહ્નિત કરવામાં આવે, તો -2/5 ક્યાં આવેલ હશે?',
    pq5_explain: '-2/5, 0 થી 2/5 ની સમાન અંતરે હશે, પરંતુ 0 ની ડાબી બાજુએ.',
    pq6_prompt: 'સંખ્યા રેખા પર 0 થી કોણ વધુ દૂર છે?',
    pq6_explain: '3/2, 0 થી 1/2 કરતાં વધુ દૂર છે, કારણ કે 3/2 = 1.5 જે 1/2 = 0.5 કરતાં વધારે છે.',
    // Question options
    pq1_opt1: '-1 અને -2 ની વચ્ચે',
    pq1_opt2: '0 અને 1 ની વચ્ચે',
    pq1_opt3: '0 અને -1 ની વચ્ચે',
    pq1_opt4: '1 અને 2 ની વચ્ચે',
    pq2_opt1: '1/2 અને 1/3',
    pq2_opt2: '3/4 અને -3/4',
    pq2_opt3: '1/2 અને 2/3',
    pq2_opt4: '5/6 અને 1/6',
    pq3_opt1: '0 ની ડાબી બાજુ',
    pq3_opt2: '0 પર',
    pq3_opt3: '0 ની જમણી બાજુ',
    pq3_opt4: 'રેખા પર ક્યાંય પણ',
    pq4_opt1: '0 અને -1 ની વચ્ચે',
    pq4_opt2: '-1 અને -2 ની વચ્ચે',
    pq4_opt3: '-2 અને -3 ની વચ્ચે',
    pq4_opt4: '1 અને 2 ની વચ્ચે',
    pq5_opt1: '0 ની જમણી બાજુ',
    pq5_opt2: '0 ની ડાબી બાજુ',
    pq5_opt3: '2/5 ની સમાન જગ્યાએ',
    pq5_opt4: '0 પર',
    pq6_opt1: '1/2',
    pq6_opt2: '3/2',
    pq6_opt3: 'બંને સમાન છે',
    pq6_opt4: 'નક્કી કરી શકાતું નથી'
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'hi' | 'gu'>(() => {
    // Load language from localStorage on initialization
    const savedLanguage = localStorage.getItem('selectedLanguage') as 'en' | 'hi' | 'gu' | null;
    return savedLanguage || 'en';
  });
  const [isTransitioning, setIsTransitioning] = useState(false);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const localizeDigitsInText = (text: string): string => {
    // For now, just return the text as-is
    // In a real implementation, this would convert digits to the appropriate script
    return text;
  };

  const formatNumber = (num: number): string => {
    return num.toString();
  };

  const handleSetLanguage = (lang: 'en' | 'hi' | 'gu') => {
    setIsTransitioning(true);
    // Save language to localStorage
    localStorage.setItem('selectedLanguage', lang);
    setTimeout(() => {
      setLanguage(lang);
      setIsTransitioning(false);
    }, 100); // Further reduced for smoother switching
  };

  const value: LanguageContextType = {
    language,
    setLanguage: handleSetLanguage,
    t,
    isTransitioning,
    localizeDigitsInText,
    formatNumber
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
