import { createContext, useContext, useMemo, useState, ReactNode, useEffect } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'gu';

type LanguageContextValue = {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  formatNumber: (n: number) => string;
  localizeDigitsInText: (text: string) => string;
  isTransitioning: boolean;
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    demo: 'Demonstration',
    practice: 'Practice',
    assessment: 'Assessment',
    header: 'Integers: Properties of Addition & Subtraction',
    topicSubtitle: 'Properties of Addition and Subtraction of Integers',
    realWorld: 'Real World',
    realWorldSubtitle: 'Discover how integers work in everyday situations',
    prev: 'Prev',
    next: 'Next',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset',
    check: 'Check',
    submit: 'Submit',
    correct: 'Correct!',
    tryAgain: 'Try again',
    question: 'Question',
    problem: 'Problem',
    step: 'Step',
    mode: 'Mode',
    attempted: 'Attempted',
    skipped: 'Skipped',
    accuracy: 'Accuracy',
    questionsOverview: 'Questions Overview',
    incorrect: 'Incorrect',
    current: 'Current',
    skip: 'Skip',
    emptyAnswer: 'Please enter an answer',
    whitespaceAnswer: 'Answer cannot be just spaces',
    invalidNumber: 'Please enter a valid number',
    enterInteger: 'Enter integer',
    checking: 'Checking...',
    completed: 'Completed',
    attempts: 'Attempts',
    hint: 'Hint',
    subtractTip: 'Remember: a - b = a + (-b)',
    firstTry: 'First try!',
    wellDone: 'Well done!',
    practice_q1: 'Evaluate: (-6) + 9',
    practice_q2: 'Evaluate: 12 - (-5)',
    practice_q3: 'Evaluate: (-8) - 7',
    practice_q4: 'Evaluate: 4 + (-4)',
    practice_q5: 'Evaluate: (-10) + 7',
    practice_q6: 'Evaluate: 15 - 20',
    assess_q1: 'Compute: (-3) + (-7)',
    assess_q2: 'Compute: 15 - (-4)',
    assess_q3: 'Compute: (-12) - 5',
    assess_q4: 'Compute: 8 + (-15)',
    assess_q5: 'Compute: (-20) - (-13)',
    assess_q6: 'Compute: (-9) + 16 - (-4)',
    assessmentComplete: 'Assessment Complete!',
    detailedResults: 'Detailed Results',
    totalQuestions: 'Total Questions',
    points: 'Points',
    reviewAnswers: 'Review Answers',
    backToResults: 'Back to Results',
    correctAnswer: 'Correct Answer',
    yourAnswer: 'Your Answer',
    retakeAssessment: 'Retake Assessment',
    avgTime: 'Avg Time',
    suggestions: 'Suggestions',
    suggestMorePractice: 'Practice more basic operations',
    suggestSpeedUp: 'Work on improving calculation speed',
    suggestCompleteAll: 'Try to attempt all questions',
    // Additional UI text
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    addition: 'Addition',
    subtraction: 'Subtraction',
    enterYourAnswer: 'Enter your answer...',
    guidedPractice: 'Guided Practice',
    knowledgeAssessment: 'Knowledge Assessment',
    interactiveLearning: 'Interactive learning with immediate feedback and comprehensive assessment',
    click: 'Click',
    toJump: 'to jump',
    notAttempt: 'Not Attempt',
    skipQuestion: 'Skip Question',
    of: 'of',
    useButtonsToNavigate: 'Use buttons to navigate',
    notAttempted: 'Not Attempted',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit',
    previous: 'Previous',
    hideAnswer: 'Hide Answer',
    showAnswer: 'Show Answer',
    useButtons: 'Use navigation buttons',
    whatNext: 'What\'s Next?',
    chooseNextStep: 'Choose your next step!',
    readyToMove: 'Ready to move!',
    questionAnswered: 'Question Answered!',
    moveToNext: 'Move to the next question!',
    temp: 'Temperature',
    bank: 'Bank Balance',
    elevation: 'Elevation',
    learn: 'Learn',
    replay: 'Replay',
    startLabel: 'Start',
    changeLabel: 'Change',
    finalLabel: 'Final',
    upLabel: 'Going Up',
    downLabel: 'Going Down',
    sportsScore: 'Sports Score',
    debtPayment: 'Debt Payment',
    replayTip: 'Click any card to replay animations!',
    // Demonstration step titles and descriptions
    tempChangeTitle: 'Temperature Change',
    tempChangeDesc: 'Use integers to track warming/cooling.',
    tempChangeExample: '(-3) + 5 = 2',
    bankBalanceTitle: 'Bank Balance',
    bankBalanceDesc: 'Deposits add; payments subtract.',
    bankBalanceExample: '(-500) + 800 = 300',
    elevationTitle: 'Elevation',
    elevationDesc: 'Climb adds; descend subtracts.',
    elevationExample: '15 - 40 = -25',
    numberLineTitle: 'Number Line Rule',
    numberLineDesc: 'a - b = a + (-b). Move right for +, left for −.',
    numberLineExample: '6 - 9 = 6 + (−9) = −3',
    propertiesTitle: 'Properties (Addition)',
    propertiesDesc: 'Commutative, Associative, Identity (0), Inverse (−a).',
    propertiesExample: '3 + (−8) = (−8) + 3',
    // Property badges
    closure: 'Closure',
    commutative: 'Commutative ( + )',
    associative: 'Associative ( + )',
    identity: 'Identity 0',
    inverse: 'Inverse −a',
    distributive: 'Distributive',
    additive: 'Additive Identity',
    multiplicative: 'Multiplicative Identity',
    session_complete: 'Session Complete!',
    session_summary: 'Here\'s your complete session summary',
    total_questions: 'Total Questions',
    correct_answers: 'Correct Answers',
    incorrect_answers: 'Incorrect Answers',
    skipped_questions: 'Skipped Questions',
    final_grade: 'Final Grade',
    accuracy_rate: 'Accuracy Rate',
    avg_time_per_question: 'Avg Time/Question',
    question_review: 'Question by Question Review',
    start_new_session: 'Start New Session',
    not_attempted: 'Not Attempted',
  },
  hi: {
    demo: 'प्रदर्शन',
    practice: 'अभ्यास',
    assessment: 'मूल्यांकन',
    header: 'पूर्णांक: जोड़ और घटाव के गुण',
    topicSubtitle: 'पूर्णांकों के जोड़ और घटाव के गुण',
    realWorld: 'वास्तविक जीवन',
    realWorldSubtitle: 'जानें कि पूर्णांक रोजमर्रा की स्थितियों में कैसे काम करते हैं',
    prev: 'पिछला',
    next: 'अगला',
    play: 'चलाएँ',
    pause: 'रोकें',
    reset: 'रीसेट',
    check: 'जाँचें',
    submit: 'जमा करें',
    correct: 'सही!',
    tryAgain: 'फिर प्रयास करें',
    question: 'प्रश्न',
    problem: 'समस्या',
    step: 'चरण',
    mode: 'मोड',
    attempted: 'प्रयास किया',
    skipped: 'छोड़ा गया',
    accuracy: 'सटीकता',
    questionsOverview: 'प्रश्न अवलोकन',
    incorrect: 'गलत',
    current: 'वर्तमान',
    skip: 'छोड़ें',
    emptyAnswer: 'कृपया एक उत्तर दर्ज करें',
    whitespaceAnswer: 'उत्तर केवल खाली स्थान नहीं हो सकता',
    invalidNumber: 'कृपया एक वैध संख्या दर्ज करें',
    enterInteger: 'पूर्णांक दर्ज करें',
    checking: 'जाँच रहे हैं...',
    completed: 'पूर्ण',
    attempts: 'प्रयास',
    hint: 'संकेत',
    subtractTip: 'याद रखें: a - b = a + (-b)',
    firstTry: 'पहली कोशिश!',
    wellDone: 'बहुत बढ़िया!',
    practice_q1: 'मूल्यांकन करें: (-६) + ९',
    practice_q2: 'मूल्यांकन करें: १२ - (-५)',
    practice_q3: 'मूल्यांकन करें: (-८) - ७',
    practice_q4: 'मूल्यांकन करें: ४ + (-४)',
    practice_q5: 'मूल्यांकन करें: (-१०) + ७',
    practice_q6: 'मूल्यांकन करें: १५ - २०',
    assess_q1: 'गणना करें: (-३) + (-७)',
    assess_q2: 'गणना करें: १५ - (-४)',
    assess_q3: 'गणना करें: (-१२) - ५',
    assess_q4: 'गणना करें: ८ + (-१५)',
    assess_q5: 'गणना करें: (-२०) - (-१३)',
    assess_q6: 'गणना करें: (-९) + १६ - (-४)',
    assessmentComplete: 'मूल्यांकन पूर्ण!',
    detailedResults: 'विस्तृत परिणाम',
    totalQuestions: 'कुल प्रश्न',
    points: 'अंक',
    reviewAnswers: 'उत्तर समीक्षा',
    backToResults: 'परिणाम पर वापस',
    correctAnswer: 'सही उत्तर',
    yourAnswer: 'आपका उत्तर',
    retakeAssessment: 'पुनः मूल्यांकन',
    avgTime: 'औसत समय',
    suggestions: 'सुझाव',
    suggestMorePractice: 'बुनियादी संक्रियाओं का अधिक अभ्यास करें',
    suggestSpeedUp: 'गणना की गति में सुधार पर काम करें',
    suggestCompleteAll: 'सभी प्रश्नों का प्रयास करने की कोशिश करें',
    // Additional UI text
    easy: 'आसान',
    medium: 'मध्यम',
    hard: 'कठिन',
    addition: 'योग',
    subtraction: 'घटाव',
    enterYourAnswer: 'अपना उत्तर दर्ज करें...',
    guidedPractice: 'निर्देशित अभ्यास',
    knowledgeAssessment: 'ज्ञान मूल्यांकन',
    interactiveLearning: 'तत्काल प्रतिक्रिया और व्यापक मूल्यांकन के साथ इंटरैक्टिव शिक्षा',
    click: 'क्लिक करें',
    toJump: 'जाने के लिए',
    notAttempt: 'प्रयास नहीं',
    skipQuestion: 'प्रश्न छोड़ें',
    of: 'में से',
    useButtonsToNavigate: 'नेविगेट करने के लिए बटन का उपयोग करें',
    notAttempted: 'प्रयास नहीं किया',
    fullscreen: 'पूर्ण स्क्रीन',
    exitFullscreen: 'बाहर निकलें',
    previous: 'पिछला',
    hideAnswer: 'उत्तर छुपाएं',
    showAnswer: 'उत्तर दिखाएं',
    useButtons: 'नेविगेट करने के लिए बटन का उपयोग करें',
    whatNext: 'अब क्या?',
    chooseNextStep: 'अपना अगला कदम चुनें!',
    readyToMove: 'आगे बढ़ने के लिए तैयार!',
    questionAnswered: 'प्रश्न का उत्तर दिया!',
    moveToNext: 'अगले प्रश्न पर जाएं!',
    temp: 'तापमान',
    bank: 'बैंक बैलेंस',
    elevation: 'ऊँचाई',
    learn: 'सीखें',
    replay: 'दोबारा चलाएँ',
    startLabel: 'आरंभ',
    changeLabel: 'परिवर्तन',
    finalLabel: 'अंतिम',
    upLabel: 'ऊपर जाना',
    downLabel: 'नीचे जाना',
    sportsScore: 'खेल स्कोर',
    debtPayment: 'कर्ज़ की अदायगी',
    replayTip: 'एनीमेशन दोबारा देखने के लिए किसी भी कार्ड पर क्लिक करें!',
    // Demonstration step titles and descriptions
    tempChangeTitle: 'तापमान परिवर्तन',
    tempChangeDesc: 'गर्म होने/ठंडा होने को ट्रैक करने के लिए पूर्णांकों का उपयोग करें।',
    tempChangeExample: '(-३) + ५ = २',
    bankBalanceTitle: 'बैंक बैलेंस',
    bankBalanceDesc: 'जमा राशि जोड़ती है; भुगतान घटाता है।',
    bankBalanceExample: '(-५००) + ८०० = ३००',
    elevationTitle: 'ऊँचाई',
    elevationDesc: 'चढ़ना जोड़ता है; उतरना घटाता है।',
    elevationExample: '१५ - ४० = -२५',
    numberLineTitle: 'संख्या रेखा नियम',
    numberLineDesc: 'a - b = a + (-b)। + के लिए दाएं, − के लिए बाएं जाएं।',
    numberLineExample: '६ - ९ = ६ + (−९) = −३',
    propertiesTitle: 'गुणधर्म (योग)',
    propertiesDesc: 'क्रमविनिमेय, साहचर्य, तत्समक (०), व्युत्क्रम (−a)।',
    propertiesExample: '३ + (−८) = (−८) + ३',
    // Property badges
    closure: 'संवृतता',
    commutative: 'क्रमविनिमेय ( + )',
    associative: 'साहचर्य ( + )',
    identity: 'तत्समक ०',
    inverse: 'व्युत्क्रम −a',
    distributive: 'वितरण',
    additive: 'योगात्मक तत्समक',
    multiplicative: 'गुणात्मक तत्समक',
    session_complete: 'सत्र पूर्ण हो गया!',
    session_summary: 'यहाँ आपके सत्र का पूरा सारांश है',
    total_questions: 'कुल प्रश्न',
    correct_answers: 'सही उत्तर',
    incorrect_answers: 'गलत उत्तर',
    skipped_questions: 'छोड़े गए प्रश्न',
    final_grade: 'अंतिम ग्रेड',
    accuracy_rate: 'सटीकता दर',
    avg_time_per_question: 'औसत समय/प्रश्न',
    question_review: 'प्रश्न दर प्रश्न समीक्षा',
    start_new_session: 'नया सत्र शुरू करें',
    not_attempted: 'प्रयास नहीं किया',
  },
  gu: {
    demo: 'પ્રદર્શન',
    practice: 'અભ્યાસ',
    assessment: 'મૂલ્યાંકન',
    header: 'પૂર્ણાંક: સરવાળો અને બાદબાકી ના ગુણધર્મો',
    topicSubtitle: 'પૂર્ણાંકના સરવાળા અને બાદબાકી ના ગુણધર્મો',
    realWorld: 'વાસ્તવિક દુનિયા',
    realWorldSubtitle: 'જાણો કે પૂર્ણાંક રોજિંદા પરિસ્થિતિઓમાં કેવી રીતે કામ કરે છે',
    prev: 'પાછળ',
    next: 'આગળ',
    play: 'ચાલુ',
    pause: 'વિરામ',
    reset: 'રીસેટ',
    check: 'ચેક',
    submit: 'સબમિટ',
    correct: 'સારું!',
    tryAgain: 'ફરી પ્રયત્ન કરો',
    question: 'પ્રશ્ન',
    problem: 'સમસ્યા',
    step: 'પગલું',
    mode: 'મોડ',
    attempted: 'પ્રયાસ કર્યો',
    skipped: 'છોડ્યું',
    accuracy: 'ચોકસાઈ',
    questionsOverview: 'પ્રશ્નોની ઝાંખી',
    incorrect: 'ખોટું',
    current: 'વર્તમાન',
    skip: 'છોડો',
    emptyAnswer: 'કૃપા કરીને જવાબ દાખલ કરો',
    whitespaceAnswer: 'જવાબ ફક્ત ખાલી જગ્યા હોઈ શકે નહીં',
    invalidNumber: 'કૃપા કરીને માન્ય સંખ્યા દાખલ કરો',
    enterInteger: 'પૂર્ણાંક દાખલ કરો',
    checking: 'તપાસી રહ્યાં છીએ...',
    completed: 'પૂર્ણ',
    attempts: 'પ્રયાસો',
    hint: 'સંકેત',
    subtractTip: 'યાદ રાખો: a - b = a + (-b)',
    firstTry: 'પ્રથમ પ્રયાસ!',
    wellDone: 'સારું કર્યું!',
    practice_q1: 'મૂલ્યાંકન કરો: (-૬) + ૯',
    practice_q2: 'મૂલ્યાંકન કરો: ૧૨ - (-૫)',
    practice_q3: 'મૂલ્યાંકન કરો: (-૮) - ૭',
    practice_q4: 'મૂલ્યાંકન કરો: ૪ + (-૪)',
    practice_q5: 'મૂલ્યાંકન કરો: (-૧૦) + ૭',
    practice_q6: 'મૂલ્યાંકન કરો: ૧૫ - ૨૦',
    assess_q1: 'ગણતરી કરો: (-૩) + (-૭)',
    assess_q2: 'ગણતરી કરો: ૧૫ - (-૪)',
    assess_q3: 'ગણતરી કરો: (-૧૨) - ૫',
    assess_q4: 'ગણતરી કરો: ૮ + (-૧૫)',
    assess_q5: 'ગણતરી કરો: (-૨૦) - (-૧૩)',
    assess_q6: 'ગણતરી કરો: (-૯) + ૧૬ - (-૪)',
    assessmentComplete: 'મૂલ્યાંકન પૂર્ણ!',
    detailedResults: 'વિગતવાર પરિણામો',
    totalQuestions: 'કુલ પ્રશ્નો',
    points: 'પોઈન્ટ્સ',
    reviewAnswers: 'જવાબોની સમીક્ષા',
    backToResults: 'પરિણામો પર પાછા',
    correctAnswer: 'સાચો જવાબ',
    yourAnswer: 'તમારો જવાબ',
    retakeAssessment: 'ફરીથી મૂલ્યાંકન',
    avgTime: 'સરેરાશ સમય',
    suggestions: 'સૂચનો',
    suggestMorePractice: 'મૂળભૂત કામગીરીનો વધુ અભ્યાસ કરો',
    suggestSpeedUp: 'ગણતરીની ગતિ સુધારવા પર કામ કરો',
    suggestCompleteAll: 'બધા પ્રશ્નોનો પ્રયાસ કરવાનો પ્રયત્ન કરો',
    // Additional UI text
    easy: 'સરળ',
    medium: 'મધ્યમ',
    hard: 'કઠિન',
    addition: 'સરવાળો',
    subtraction: 'બાદબાકી',
    enterYourAnswer: 'તમારો જવાબ દાખલ કરો...',
    guidedPractice: 'માર્ગદર્શિત અભ્યાસ',
    knowledgeAssessment: 'જ્ઞાન મૂલ્યાંકન',
    interactiveLearning: 'તાત્કાલિક પ્રતિસાદ અને વ્યાપક મૂલ્યાંકન સાથે ઇન્ટરેક્ટિવ શિક્ષણ',
    click: 'ક્લિક કરો',
    toJump: 'જવા માટે',
    notAttempt: 'પ્રયાસ નહીં',
    skipQuestion: 'પ્રશ્ન છોડો',
    of: 'માંથી',
    useButtonsToNavigate: 'નેવિગેટ કરવા માટે બટનોનો ઉપયોગ કરો',
    notAttempted: 'પ્રયાસ કર્યો નથી',
    fullscreen: 'ફુલસ્ક્રીન',
    exitFullscreen: 'બહાર',
    previous: 'પાછળ',
    hideAnswer: 'જવાબ છુપાવો',
    showAnswer: 'જવાબ બતાવો',
    useButtons: 'નેવિગેટ કરવા માટે બટનોનો ઉપયોગ કરો',
    whatNext: 'હવે શું?',
    chooseNextStep: 'તમારું આગળનું પગલું પસંદ કરો!',
    readyToMove: 'આગળ વધવા માટે તૈયાર!',
    questionAnswered: 'પ્રશ્નનો જવાબ આપ્યો!',
    moveToNext: 'આગળના પ્રશ્ન પર જાઓ!',
    temp: 'તાપમાન',
    bank: 'બેન્ક બેલેન્સ',
    elevation: 'ઊંચાઈ',
    learn: 'શીખો',
    replay: 'પુનઃ ચાલાવો',
    startLabel: 'શરૂઆત',
    changeLabel: 'ફેરફાર',
    finalLabel: 'અંતિમ',
    upLabel: 'ઉપર જવું',
    downLabel: 'નીચે જવું',
    sportsScore: 'રમત સ્કોર',
    debtPayment: 'દેવું ચૂકવણી',
    replayTip: 'એનિમેશન ફરીથી જોવા માટે કોઈપણ કાર્ડ પર ક્લિક કરો!',
    // Demonstration step titles and descriptions
    tempChangeTitle: 'તાપમાન પરિવર્તન',
    tempChangeDesc: 'ગરમ/ઠંડા થવાને ટ્રેક કરવા માટે પૂર્ણાંકનો ઉપયોગ કરો।',
    tempChangeExample: '(-૩) + ૫ = ૨',
    bankBalanceTitle: 'બેન્ક બેલેન્સ',
    bankBalanceDesc: 'જમા વધારે છે; ચૂકવણી ઓછી છે।',
    bankBalanceExample: '(-૫૦૦) + ૮૦૦ = ૩૦૦',
    elevationTitle: 'ઊંચાઈ',
    elevationDesc: 'ચઢવું વધારે છે; ઉતરવું ઓછું છે।',
    elevationExample: '૧૫ - ૪૦ = -૨૫',
    numberLineTitle: 'સંખ્યા રેખા નિયમ',
    numberLineDesc: 'a - b = a + (-b)। + માટે જમણે, − માટે ડાબે જાઓ।',
    numberLineExample: '૬ - ૯ = ૬ + (−૯) = −૩',
    propertiesTitle: 'ગુણધર્મો (સરવાળો)',
    propertiesDesc: 'ક્રમવિનિમય, સહયોગી, ઓળખ (૦), વ્યુત્ક્રમ (−a)।',
    propertiesExample: '૩ + (−૮) = (−૮) + ૩',
    // Property badges
    closure: 'બંધ',
    commutative: 'ક્રમવિનિમય ( + )',
    associative: 'સહયોગી ( + )',
    identity: 'ઓળખ ૦',
    inverse: 'વ્યુત્ક્રમ −a',
    distributive: 'વિતરણ',
    additive: 'યોગાત્મક ઓળખ',
    multiplicative: 'ગુણાત્મક ઓળખ',
    session_complete: 'સત્ર પૂર્ણ!',
    session_summary: 'અહીં તમારા સત્રનો સંપૂર્ણ સારાંશ છે',
    total_questions: 'કુલ પ્રશ્નો',
    correct_answers: 'સાચા જવાબો',
    incorrect_answers: 'ખોટા જવાબો',
    skipped_questions: 'છોડેલા પ્રશ્નો',
    final_grade: 'અંતિમ ગ્રેડ',
    accuracy_rate: 'સચોટતા દર',
    avg_time_per_question: 'સરેરાશ સમય/પ્રશ્ન',
    question_review: 'પ્રશ્ન દર પ્રશ્ન સમીક્ષા',
    start_new_session: 'નવો સત્ર શરૂ કરો',
    not_attempted: 'પ્રયાસ કર્યો નથી',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<SupportedLanguage>('en');
  const [isTransitioning, setIsTransitioning] = useState(false);
  const t = useMemo(() => (key: string) => translations[language][key] ?? key, [language]);

  const digitMaps: Record<SupportedLanguage, Record<string, string>> = {
    en: { '0': '0', '1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9' },
    hi: { '0': '०', '1': '१', '2': '२', '3': '३', '4': '४', '5': '५', '6': '६', '7': '७', '8': '८', '9': '९' },
    gu: { '0': '૦', '1': '૧', '2': '૨', '3': '૩', '4': '૪', '5': '૫', '6': '૬', '7': '૭', '8': '૮', '9': '૯' },
  };

  const formatNumber = (n: number) => String(n).replace(/[0-9]/g, (d) => digitMaps[language][d]);
  const localizeDigitsInText = (text: string) => text.replace(/[0-9]/g, (d) => digitMaps[language][d]);

  // Enhanced setLanguage with transition animation
  const setLanguageWithAnimation = (lang: SupportedLanguage) => {
    if (lang === language) return;
    
    setIsTransitioning(true);
    
    // Add a slight delay to show the transition effect
    setTimeout(() => {
      setLanguage(lang);
      setTimeout(() => {
        setIsTransitioning(false);
      }, 300); // Animation duration
    }, 150);
  };

  const value = useMemo(() => ({ 
    language, 
    setLanguage: setLanguageWithAnimation, 
    t, 
    formatNumber, 
    localizeDigitsInText, 
    isTransitioning 
  }), [language, isTransitioning]);
  
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}


